(() => {
  'use strict';

  const $ = (id) => document.getElementById(id);
  const canvas = $('canvas');
  const ctx = canvas.getContext('2d', { alpha: false });
  const parts = decodeURIComponent(location.pathname).split('/').filter(Boolean);
  const slug = parts.at(-1) === 'index.html' ? parts.at(-2) : parts.at(-1);

  const configs = {
    'dynamic-array': { title:'动态数组', mono:'DA', eye:'STRUCTURE / DYNAMIC ARRAY', aLabel:'依次追加的整数', a:'4,8,15,16,23,42', bLabel:'初始容量', b:'2', metrics:['已插入','当前长度','当前容量'], principle:'容量不足时分配更大的连续空间并搬移已有元素，以摊还常数时间完成尾部追加。', complexity:'APPEND AMORTIZED O(1) · ACCESS O(1)' },
    'circular-buffer': { title:'循环缓冲区', mono:'CB', eye:'STRUCTURE / RING BUFFER', theme:'theme-violet', aLabel:'操作序列（分号分隔）', a:'push 3;push 5;push 8;pop;push 13;push 21', bLabel:'容量', b:'4', metrics:['当前操作','队首位置','元素数量'], principle:'通过取模让首尾索引在固定数组内循环移动，无需搬移已有元素。', complexity:'PUSH / POP · O(1)' },
    'bitset-bitmap': { title:'位集与位图', mono:'BM', eye:'STRUCTURE / BITSET', theme:'theme-green', aLabel:'需要置位的下标', a:'1,3,4,7,9,15', bLabel:'位图大小（8-64）', b:'16', metrics:['当前下标','机器字表示','置位数量'], principle:'用一个机器字中的每一位表示布尔状态，通过位运算批量查询和修改。', complexity:'SET / TEST · O(1) · SPACE O(N/W)' },
    'order-statistic-tree': { title:'顺序统计树', mono:'OS', eye:'STRUCTURE / ORDER STATISTICS', theme:'theme-rose', aLabel:'互异整数键', a:'50,20,70,10,30,60,80,40', bLabel:'第 K 小（从 1 开始）', b:'4', metrics:['已插入','根子树大小','第 K 小'], principle:'在平衡搜索树节点维护子树大小，从左右子树规模决定第 k 小元素所在方向。', complexity:'INSERT / KTH · O(LOG N) BALANCED' },
    'pairing-heap': { title:'配对堆', mono:'PH', eye:'STRUCTURE / MELDABLE HEAP', theme:'theme-amber', aLabel:'插入键序列', a:'9,4,7,1,6,2,8,3,5', bLabel:'删除最小值次数', b:'2', metrics:['操作','根孩子数','当前最小值'], principle:'插入通过一次 meld 完成；删除根后把孩子两两合并，再从右向左归并。', complexity:'MELD O(1) · DELETE-MIN AMORTIZED O(LOG N)' },
    'radix-tree': { title:'Patricia / Radix Tree', mono:'RT', eye:'STRUCTURE / COMPRESSED TRIE', theme:'theme-violet', aLabel:'单词（逗号分隔）', a:'car,card,care,cart,cat,dog,dove', bLabel:'查询前缀', b:'car', metrics:['已插入','压缩边数','前缀命中'], principle:'把只有一个孩子的 Trie 路径压缩为字符串边，减少节点数量并保留前缀检索能力。', complexity:'INSERT / SEARCH · O(KEY LENGTH)' },
    'rope': { title:'Rope 字符串结构', mono:'RP', eye:'STRUCTURE / ROPE', theme:'theme-green', aLabel:'初始文本', a:'ALGORITHM', bLabel:'插入位置,文本', b:'5,_FAST_', metrics:['树高','叶块数量','结果长度'], principle:'用平衡二叉树组织字符串块，编辑只需拆分并重新连接少量子树。', complexity:'SPLIT / CONCAT · O(LOG N)' },
    'disjoint-sparse-table': { title:'不相交稀疏表', mono:'DS', eye:'QUERY / DISJOINT SPARSE TABLE', theme:'theme-rose', aLabel:'整数数组', a:'3,1,4,1,5,9,2,6', bLabel:'区间查询 L,R（分号分隔）', b:'1,5;2,7', metrics:['构建层 / 查询','覆盖层','区间和'], principle:'每层围绕块中点预计算左后缀和右前缀，任意区间由最高不同位对应的两个值合并。', complexity:'BUILD O(N LOG N) · QUERY O(1)' },
    'merge-sort-tree': { title:'归并排序树', mono:'MT', eye:'QUERY / MERGE SORT TREE', theme:'theme-amber', aLabel:'整数数组', a:'7,2,6,3,9,1,5,8', bLabel:'查询 L,R,X（统计 ≤X）', b:'1,6,4', metrics:['已建节点','访问节点','命中数量'], principle:'在线段树每个节点保存有序数组，查询区间内不大于 x 的数量时进行二分统计。', complexity:'BUILD O(N LOG N) · QUERY O(LOG² N)' },
    'li-chao-tree': { title:'Li Chao Tree', mono:'LC', eye:'QUERY / LINE CONTAINER', theme:'theme-violet', aLabel:'直线 m,b（分号分隔）', a:'2,3;-1,12;1,1', bLabel:'查询 x（逗号分隔）', b:'-2,0,3,6', metrics:['操作','树节点','最小值'], principle:'每个区间保留中点更优的直线，把另一条直线递归放入仍可能获胜的一侧。', complexity:'INSERT / QUERY · O(LOG DOMAIN)' },
    'segment-tree-beats': { title:'Segment Tree Beats', mono:'SB', eye:'QUERY / RANGE CHMIN', theme:'theme-green', aLabel:'整数数组', a:'8,6,7,5,3,0,9', bLabel:'操作（chmin/sum L R V）', b:'chmin 0 6 6;sum 0 6;chmin 1 4 4;sum 0 6', metrics:['当前操作','受影响节点','区间和'], principle:'节点同时维护最大值、严格次大值和最大值个数，满足条件时整段降低最大值。', complexity:'RANGE CHMIN / SUM · AMORTIZED O(LOG² N)' },
    'persistent-trie': { title:'持久化 Trie', mono:'PT', eye:'STRUCTURE / PERSISTENT TRIE', theme:'theme-rose', aLabel:'按版本插入的单词', a:'cat,car,dog,cart,dove,cow', bLabel:'版本,前缀', b:'6,do', metrics:['版本','新建节点','前缀计数'], principle:'每次插入只复制根到单词末尾的路径，未变化的分支由新旧版本共享。', complexity:'UPDATE / QUERY · O(KEY LENGTH)' },
    'coordinate-compression': { title:'坐标压缩', mono:'CC', eye:'TECHNIQUE / COMPRESSION', theme:'theme-amber', aLabel:'整数序列', a:'1000,-20,500,1000,7,500,42', metrics:['当前值','压缩编号','不同值数'], principle:'排序去重后把稀疏大值映射为保持相对顺序的紧凑整数编号。', complexity:'SORT O(N LOG N) · MAP O(LOG N)' },
    'inversion-count': { title:'逆序对统计', mono:'IC', eye:'DIVIDE CONQUER / INVERSIONS', theme:'theme-violet', aLabel:'整数数组', a:'7,5,6,4', metrics:['归并区间','跨区间新增','逆序对'], principle:'归并排序合并时，右侧元素先出队意味着它与左侧所有剩余元素构成逆序对。', complexity:'TIME O(N LOG N) · SPACE O(N)' },
    'median-of-medians': { title:'Median of Medians', mono:'MM', eye:'SELECTION / DETERMINISTIC PIVOT', theme:'theme-green', aLabel:'互异整数数组', a:'12,3,5,7,4,19,26,1,9,15,8', bLabel:'第 K 小（从 1 开始）', b:'5', metrics:['递归规模','枢轴','第 K 小'], principle:'把元素五个一组取中位数，再递归选择这些中位数的中位数作为最坏线性时间枢轴。', complexity:'DETERMINISTIC SELECTION · O(N)' },
    'meet-in-the-middle': { title:'Meet-in-the-Middle', mono:'MI', eye:'TECHNIQUE / SPLIT ENUMERATION', theme:'theme-rose', aLabel:'正整数集合', a:'3,34,4,12,5,2', bLabel:'目标子集和', b:'9', metrics:['左半状态','右半状态','目标结果'], principle:'把指数搜索拆为两半，分别枚举子集结果，再通过排序或哈希组合。', complexity:'SUBSET SUM · O(2^(N/2))' },
    'introsort': { title:'Introsort', mono:'IS', eye:'SORT / INTROSPECTIVE', theme:'theme-amber', aLabel:'整数数组', a:'9,4,7,1,6,2,8,3,5', metrics:['分区 / 回退','比较','最大值'], principle:'以快速排序开始，递归过深时切换堆排序，小区间使用插入排序。', complexity:'WORST O(N LOG N) · IN-PLACE' },
    'timsort': { title:'Timsort', mono:'TS', eye:'SORT / NATURAL RUNS', theme:'theme-violet', aLabel:'整数数组', a:'5,1,4,2,8,3,9,6,7,0', metrics:['已排序 Run','归并次数','最大值'], principle:'识别并扩展局部有序 Run，再按栈不变量稳定归并，兼顾真实数据的已有顺序。', complexity:'O(N) BEST · O(N LOG N) WORST' },
    'external-merge-sort': { title:'外部归并排序', mono:'EM', eye:'SORT / EXTERNAL MEMORY', theme:'theme-green', aLabel:'整数数据流', a:'19,3,14,8,2,17,5,11,7,13,1,16', bLabel:'内存块大小', b:'4', metrics:['当前阶段','有序 Run','最大值'], principle:'内存中分块排序写出多个 Run，再以多路归并顺序读取，限制随机磁盘访问。', complexity:'I/O O((N/B) LOG_(M/B)(N/B))' },
    'branch-and-bound': { title:'分支限界法', mono:'BB', eye:'SEARCH / BRANCH AND BOUND', theme:'theme-rose', aLabel:'物品 weight,value（分号分隔）', a:'2,6;2,10;3,12;5,18;4,15', bLabel:'背包容量', b:'10', metrics:['已展开节点','已剪枝','最优价值'], principle:'搜索决策树时用分数背包计算乐观上界，上界不可能超过当前最优值的分支直接剪枝。', complexity:'0/1 KNAPSACK · EXPONENTIAL WORST CASE' },
    'kosaraju-scc': { title:'Kosaraju 强连通分量', mono:'KS', eye:'GRAPH / TWO PASS SCC', theme:'theme-amber', aLabel:'有向边 u,v（分号分隔）', a:'A,B;B,C;C,A;C,D;D,E;E,D;E,F', metrics:['遍历阶段','已访问','分量数量'], principle:'先在原图按完成时间排序，再在转置图按逆完成序遍历，每棵搜索树就是一个强连通分量。', complexity:'SCC · O(V + E)' },
    'biconnected-components': { title:'双连通分量', mono:'BC', eye:'GRAPH / BICONNECTED', theme:'theme-violet', aLabel:'无向边 u,v（分号分隔）', a:'A,B;B,C;C,A;B,D;D,E;E,F;F,D', metrics:['DFS 节点','边栈深度','分量数量'], principle:'Tarjan DFS 维护 dfn 与 low；当子树无法越过父边时，弹出边栈形成一个双连通分量。', complexity:'BICONNECTED COMPONENTS · O(V + E)' },
    'dag-shortest-path': { title:'DAG 最短路径', mono:'DG', eye:'GRAPH / TOPOLOGICAL RELAXATION', theme:'theme-green', aLabel:'有向边 u,v,w（分号分隔）', a:'A,B,3;A,C,6;B,C,4;B,D,4;B,E,11;C,D,8;D,E,-4;D,F,5;E,F,2', bLabel:'起点,终点', b:'A,F', metrics:['拓扑节点','松弛次数','最短距离'], principle:'拓扑序保证处理节点时所有前驱已完成，因此允许负边权且每条边只松弛一次。', complexity:'DAG SHORTEST PATH · O(V + E)' },
    'tree-diameter': { title:'树的直径', mono:'TD', eye:'TREE / DOUBLE BFS', theme:'theme-rose', aLabel:'无向树边 u,v（分号分隔）', a:'A,B;A,C;B,D;B,E;C,F;F,G', metrics:['搜索轮次','最远节点','直径长度'], principle:'从任意点找到最远端点，再从该端点搜索，得到的最远距离就是树的直径。', complexity:'TWO BFS / DFS · O(N)' },
    'rerooting-dp': { title:'换根动态规划', mono:'RD', eye:'TREE DP / REROOTING', theme:'theme-amber', aLabel:'无向树边 u,v（分号分隔）', a:'A,B;A,C;B,D;B,E;C,F;F,G', metrics:['当前根','距离总和','最优根'], principle:'先求一个根的子树大小和答案，再沿边用 ans[v]=ans[u]+n-2·size[v] 常数时间换根。', complexity:'ALL ROOTS · O(N)' },
    'dsu-on-tree': { title:'DSU on Tree', mono:'DT', eye:'TREE / SMALL TO LARGE', theme:'theme-violet', aLabel:'树边 u,v（分号分隔）', a:'A,B;A,C;B,D;B,E;C,F;C,G', bLabel:'节点颜色（按 A-G）', b:'1,2,1,2,3,1,3', metrics:['已合并节点','颜色种类','最高频次'], principle:'递归保留最大子树的统计表，把较小子树数据逐项合并，从而摊还控制总复杂度。', complexity:'SUBTREE FREQUENCY · O(N LOG N)' },
    'offline-dynamic-connectivity': { title:'离线动态连通性', mono:'OD', eye:'GRAPH / TIME SEGMENT TREE', theme:'theme-green', aLabel:'操作（add/remove/query u v）', a:'add A B;add B C;query A C;remove B C;query A C;add C D;add B D;query A C', metrics:['时间点','回滚历史','连通查询为真'], principle:'把每条边的有效时间区间加入时间线段树，DFS 时配合可回滚并查集回答叶子时刻查询。', complexity:'O((Q + K) LOG Q LOG V)' },
    'lower-bound-flow': { title:'有上下界网络流', mono:'LF', eye:'FLOW / LOWER BOUNDS', theme:'theme-rose', aLabel:'边 u,v,lower,upper（分号分隔）', a:'A,B,2,4;B,C,1,3;C,A,1,2', metrics:['需求边','已满足流量','可行性'], principle:'先推送所有下界并形成节点流量需求，再连接超级源汇求最大流检查全部需求能否满足。', complexity:'FEASIBLE CIRCULATION · ONE MAX FLOW' },
    'tree-isomorphism-ahu': { title:'AHU 树同构', mono:'AH', eye:'TREE / CANONICAL ENCODING', theme:'theme-amber', aLabel:'两棵树边，以 | 分隔', a:'A,B;A,C;B,D;B,E;C,F|1,2;1,3;2,4;3,5;3,6', metrics:['候选中心','规范编码长度','同构判定'], principle:'找到树中心后递归排序所有子树编码，比较无根树的规范表示。', complexity:'TREE ISOMORPHISM · O(N LOG N)' },
    'profile-dp': { title:'轮廓线动态规划', mono:'PD', eye:'DP / PROFILE MASK', theme:'theme-violet', aLabel:'棋盘 行,列（1-8）', a:'3,4', metrics:['处理格子','轮廓状态','铺法数量'], principle:'按格子扫描，用位掩码记录跨越当前轮廓的占用状态，计算多米诺骨牌铺法。', complexity:'DOMINO TILING · O(RC·2^C)' },
    'sos-dp': { title:'SOS DP', mono:'SO', eye:'DP / SUBSETS OF SUBSETS', theme:'theme-green', aLabel:'2 的幂长度数组', a:'1,2,3,4,5,6,7,8', metrics:['当前位','已更新状态','全集子集和'], principle:'逐位把不含该位的状态贡献加入含该位状态，一次计算每个集合的所有子集之和。', complexity:'SUM OVER SUBSETS · O(N·2^N)' },
    'probability-dp': { title:'概率动态规划', mono:'PR', eye:'DP / PROBABILITY', theme:'theme-rose', aLabel:'骰子数量（1-8）', a:'3', bLabel:'目标和下界', b:'12', metrics:['骰子','可达和','达标概率'], principle:'状态保存投完若干骰子后各点数和的概率，并按下一枚骰子的六种结果转移。', complexity:'DICE SUM · O(D·6D)' },
    'divide-conquer-dp-optimization': { title:'分治 DP 优化', mono:'DC', eye:'DP / DIVIDE CONQUER OPT', theme:'theme-amber', aLabel:'正整数数组', a:'1,2,3,4,5', bLabel:'分组数量', b:'2', metrics:['当前层','候选转移','最优代价'], principle:'当最优决策点单调时，用分治限制每个中点的转移搜索区间。', complexity:'DP OPTIMIZATION · O(KN LOG N)' },
    'knuth-optimization': { title:'Knuth 优化', mono:'KO', eye:'DP / MONOTONE SPLIT', theme:'theme-violet', aLabel:'石子重量', a:'4,3,3,4', metrics:['区间长度','决策范围','最小合并代价'], principle:'满足四边形不等式时，区间 DP 的最优分割点夹在相邻区间决策点之间。', complexity:'INTERVAL DP · O(N²)' },
    'convex-hull-trick': { title:'Convex Hull Trick', mono:'CH', eye:'DP / LINE CONTAINER', theme:'theme-green', aLabel:'递增坐标 x', a:'0,1,3,6,10', bLabel:'固定代价 C', b:'5', metrics:['当前坐标','候选直线','DP 值'], principle:'把二次转移拆成直线在 x 处取最小值，利用斜率与查询单调性维护下凸壳。', complexity:'MONOTONE CHT · O(N)' },
    'rolling-hash': { title:'字符串滚动哈希', mono:'RH', eye:'STRING / PREFIX HASH', theme:'theme-rose', aLabel:'文本', a:'abracadabra', bLabel:'模式串', b:'abra', metrics:['窗口位置','哈希比较','匹配次数'], principle:'预处理前缀哈希与幂，常数时间得到任意子串哈希并快速筛选匹配位置。', complexity:'PREPROCESS O(N) · SUBSTRING O(1)' },
    'duval-lyndon-factorization': { title:'Duval / Lyndon 分解', mono:'DU', eye:'STRING / LYNDON WORDS', theme:'theme-amber', aLabel:'字符串', a:'banana', metrics:['扫描位置','当前因子','因子数量'], principle:'在线性扫描中复用字典序比较结果，把字符串唯一分解为非增 Lyndon 单词序列。', complexity:'LYNDON FACTORIZATION · O(N)' },
    'fm-index': { title:'FM-index', mono:'FM', eye:'STRING / BWT INDEX', theme:'theme-violet', aLabel:'文本（不含 $）', a:'banana', bLabel:'查询模式', b:'ana', metrics:['反向字符','SA 区间','匹配次数'], principle:'在 BWT 上利用 C 表和 Occ 前缀计数反向缩小后缀数组区间，实现压缩全文索引。', complexity:'BUILD O(N LOG N) · QUERY O(M)' },
    'dpll-sat': { title:'DPLL SAT 求解', mono:'DP', eye:'CONSTRAINT / SAT', theme:'theme-green', aLabel:'CNF 子句（整数文字，分号分隔）', a:'1,2;-1,3;-2,-3;2,3', metrics:['递归节点','单位传播','可满足性'], principle:'反复执行单位传播和纯文字消除，仍未决定时选择变量分支并在冲突后回溯。', complexity:'SAT · EXPONENTIAL WORST CASE' },
    'ac3-constraint-propagation': { title:'AC-3 约束传播', mono:'AC', eye:'CONSTRAINT / ARC CONSISTENCY', theme:'theme-rose', aLabel:'不等约束边 u,v（分号分隔）', a:'A,B;A,C;B,C;C,D', bLabel:'固定赋值（如 A=1）', b:'A=1', metrics:['已检查弧','删去取值','剩余取值'], principle:'维护有向约束弧队列；变量域缩小时重新检查相关邻居，直到所有弧一致或出现空域。', complexity:'ARC CONSISTENCY · O(ED³)' }
  };

  const cfg = configs[slug];
  if (!cfg) throw new Error(`Unknown core-batch demo: ${slug}`);

  let steps = [], stepIndex = 0, running = false, speed = 1, lastTick = 0;
  let width = 1, height = 1, dpr = 1, palette = {};
  const numList = (text) => text.split(/[\s,]+/).map(Number).filter(Number.isFinite);
  const groups = (text) => text.split(';').map(x => x.trim()).filter(Boolean);
  const must = (condition, message) => { if (!condition) throw new Error(message); };
  const metric = (value) => value === Infinity ? '∞' : value === -Infinity ? '-∞' : String(value);
  function push(label, metrics, view = {}, note = '') {
    steps.push({ label, metrics: metrics.map(metric), view, note });
  }
  function parseEdges(text, weighted = false) {
    return groups(text).map(row => {
      const p = row.split(',').map(x => x.trim());
      must(p.length >= (weighted ? 3 : 2), `边格式错误：${row}`);
      return weighted ? [p[0], p[1], Number(p[2])] : [p[0], p[1]];
    });
  }
  function nodesOf(edges) { return [...new Set(edges.flatMap(e => e.slice(0, 2)))]; }
  function lineView(lines, values, selected = []) { return { lines, values, selected }; }

  function buildDynamicArray() {
    const values = numList($('input-a').value).map(Math.round).slice(0, 30), initial = Math.max(1, Math.round(Number($('input-b').value)) || 1);
    must(values.length, '请输入至少一个整数'); let cap = initial, arr = [];
    push('分配初始连续空间', [0, 0, cap], { values:Array(cap).fill('·') }, 'ALLOCATE');
    for (const value of values) {
      if (arr.length === cap) { cap *= 2; push(`容量扩展到 ${cap}`, [arr.length, arr.length, cap], { values:[...arr, ...Array(cap-arr.length).fill('·')], selected:arr.map((_,i)=>i) }, 'COPY EXISTING ELEMENTS'); }
      arr.push(value); push(`追加 ${value}`, [arr.length, arr.length, cap], { values:[...arr, ...Array(cap-arr.length).fill('·')], selected:[arr.length-1] }, 'APPEND');
    }
  }

  function buildCircularBuffer() {
    const ops = groups($('input-a').value), cap = Math.max(1, Math.min(20, Math.round(Number($('input-b').value)) || 4));
    const data = Array(cap).fill('·'); let head = 0, size = 0;
    push('初始化固定容量缓冲区', ['INIT', head, size], { values:data }, 'RING BUFFER');
    for (const raw of ops) {
      const [op, token] = raw.split(/\s+/), value = Number(token);
      if (op.toLowerCase() === 'push') { must(Number.isFinite(value), `操作格式错误：${raw}`); must(size < cap, '缓冲区已满，请增加容量'); data[(head + size) % cap] = value; size++; }
      else if (op.toLowerCase() === 'pop') { must(size > 0, '不能从空缓冲区弹出'); data[head] = '·'; head = (head + 1) % cap; size--; }
      else throw new Error(`未知操作：${raw}`);
      push(`执行 ${raw}`, [raw, head, size], { values:[...data], selected:size ? [head] : [] }, `HEAD ${head} · TAIL ${(head+size)%cap}`);
    }
  }

  function buildBitset() {
    const indices = numList($('input-a').value).map(Math.round), size = Math.max(8, Math.min(64, Math.round(Number($('input-b').value)) || 16));
    let word = 0n, count = 0; push('初始化全部位为 0', ['INIT', '0x0', 0], { values:Array(size).fill(0) }, 'BITSET');
    for (const index of indices) { must(index >= 0 && index < size, `下标 ${index} 超出位图范围`); const mask = 1n << BigInt(index); if (!(word & mask)) count++; word |= mask; const bits = Array.from({length:size},(_,i)=>(word & (1n<<BigInt(i))) ? 1 : 0); push(`置位 ${index}`, [index, `0x${word.toString(16)}`, count], { values:bits, selected:[index] }, `WORD |= 1 << ${index}`); }
  }

  function buildOrderStatistic() {
    const values = numList($('input-a').value).map(Math.round), k = Math.round(Number($('input-b').value)); must(values.length && new Set(values).size===values.length && k >= 1 && k <= values.length, '请输入互异键，且 K 必须位于键数量范围内');
    let root = null; const size = n => n ? n.size : 0, update=n=>{n.size=1+size(n.left)+size(n.right);return n;}, priority=key=>Math.imul((key|0)^0x5bd1e995,0x27d4eb2d)>>>0;
    function rotateRight(n){const x=n.left;n.left=x.right;x.right=n;update(n);return update(x);}function rotateLeft(n){const x=n.right;n.right=x.left;x.left=n;update(n);return update(x);}
    function insert(n, key) { if (!n) return {key,priority:priority(key),left:null,right:null,size:1}; if (key < n.key){n.left=insert(n.left,key);if(n.left.priority<n.priority)n=rotateRight(n);}else{n.right=insert(n.right,key);if(n.right.priority<n.priority)n=rotateLeft(n);}return update(n); }
    values.forEach((value,index) => { root=insert(root,value); push(`插入键 ${value}`, [index+1, size(root), '--'], { values:[...values.slice(0,index+1)].sort((a,b)=>a-b), selected:[] }, 'BALANCE AND UPDATE SUBTREE SIZES'); });
    let n=root, rank=k; while(n) { const left=size(n.left); push(`在键 ${n.key} 比较秩`, [values.length, left+1, n.key], { values:[...values].sort((a,b)=>a-b), selected:[k-1] }, `LEFT SIZE ${left}`); if(rank===left+1) break; if(rank<=left)n=n.left; else{rank-=left+1;n=n.right;} }
  }

  function buildPairingHeap() {
    const values=numList($('input-a').value), deletes=Math.max(0,Math.round(Number($('input-b').value))||0); let root=null;
    const meld=(a,b)=>{if(!a)return b;if(!b)return a;if(a.key>b.key)[a,b]=[b,a];b.sibling=a.child;a.child=b;return a;};
    const mergePairs=(first)=>{if(!first||!first.sibling)return first;const a=first,b=first.sibling,rest=b.sibling;a.sibling=b.sibling=null;return meld(meld(a,b),mergePairs(rest));};
    const childCount=n=>{let c=0;for(let x=n?.child;x;x=x.sibling)c++;return c;};
    for(const value of values){root=meld(root,{key:value,child:null,sibling:null});push(`meld 新节点 ${value}`,['INSERT',childCount(root),root.key],{values:values.slice(0,values.indexOf(value)+1),selected:[values.indexOf(value)]},'ONE-PASS MELD');}
    for(let i=0;i<deletes;i++){must(root,'删除次数超过元素数量');const old=root.key;root=mergePairs(root.child);push(`删除最小值 ${old}`,['DELETE-MIN',childCount(root),root?root.key:'--'],{lines:[`removed ${old}`,`new min ${root?root.key:'empty'}`]},'PAIRWISE MERGE');}
  }

  function buildRadixTree() {
    const words=$('input-a').value.split(/[\s,]+/).filter(Boolean), prefix=$('input-b').value.trim(); must(words.length&&prefix,'请输入单词与查询前缀');
    const root={edges:[],end:false}; let edgeCount=0;
    function common(a,b){let i=0;while(i<a.length&&i<b.length&&a[i]===b[i])i++;return i;}
    function insert(node,word){for(let i=0;i<node.edges.length;i++){const edge=node.edges[i],n=common(edge.label,word);if(!n)continue;if(n===edge.label.length)return insert(edge.child,word.slice(n));const split={edges:[{label:edge.label.slice(n),child:edge.child}],end:false};node.edges[i]={label:edge.label.slice(0,n),child:split};if(n===word.length)split.end=true;else split.edges.push({label:word.slice(n),child:{edges:[],end:true}});return;}node.edges.push({label:word,child:{edges:[],end:true}});}
    words.forEach((word,i)=>{insert(root,word);edgeCount=0;(function count(n){for(const e of n.edges){edgeCount++;count(e.child);}})(root);push(`插入 ${word}`,[i+1,edgeCount,'--'],{lines:words.slice(0,i+1)},'COMPRESS SINGLE-CHILD PATHS');});
    function countAll(node){return(node.end?1:0)+node.edges.reduce((sum,e)=>sum+countAll(e.child),0);}function countPrefix(node,rest){if(!rest)return countAll(node);for(const edge of node.edges){const n=common(edge.label,rest);if(n===rest.length)return countAll(edge.child);if(n===edge.label.length)return countPrefix(edge.child,rest.slice(n));}return 0;}const hits=countPrefix(root,prefix);push(`查询前缀 ${prefix}`,[words.length,edgeCount,hits],{lines:words.filter(w=>w.startsWith(prefix))},'FOLLOW COMPRESSED PREFIX EDGES');
  }

  function buildRope() {
    const text=$('input-a').value, split=$('input-b').value.indexOf(','), pos=Number($('input-b').value.slice(0,split)), insert=$('input-b').value.slice(split+1);must(split>0&&Number.isInteger(pos)&&pos>=0&&pos<=text.length,'插入格式应为 位置,文本');
    const leaf=s=>s?{text:s,left:null,right:null,len:s.length,height:1}:null; const len=n=>n?n.len:0, height=n=>n?n.height:0;
    const concat=(a,b)=>!a?b:!b?a:{text:null,left:a,right:b,len:len(a)+len(b),height:1+Math.max(height(a),height(b))};
    function from(s){const chunks=[];for(let i=0;i<s.length;i+=4)chunks.push(leaf(s.slice(i,i+4)));while(chunks.length>1){const next=[];for(let i=0;i<chunks.length;i+=2)next.push(concat(chunks[i],chunks[i+1]||null));chunks.splice(0,chunks.length,...next);}return chunks[0]||null;}
    function flatten(n){return!n?'':n.text!==null?n.text:flatten(n.left)+flatten(n.right);} function splitAt(n,p){if(!n)return[null,null];if(n.text!==null)return[leaf(n.text.slice(0,p)),leaf(n.text.slice(p))];const leftLen=len(n.left);if(p<leftLen){const[a,b]=splitAt(n.left,p);return[a,concat(b,n.right)];}const[a,b]=splitAt(n.right,p-leftLen);return[concat(n.left,a),b];}
    let root=from(text);push('建立分块 Rope',[height(root),Math.ceil(text.length/4),text.length],{lines:[...Array.from({length:Math.ceil(text.length/4)},(_,i)=>text.slice(i*4,i*4+4))]},'BALANCED CHUNKS');const [left,right]=splitAt(root,pos);root=concat(concat(left,from(insert)),right);const result=flatten(root);push(`在 ${pos} 插入文本`,[height(root),Math.ceil(result.length/4),result.length],{lines:[result]},'SPLIT · CONCAT · CONCAT');
  }

  function buildDisjointSparse() {
    const a=numList($('input-a').value), queries=groups($('input-b').value).map(numList);must(a.length&&queries.length,'请输入数组和查询');const levels=Math.ceil(Math.log2(Math.max(2,a.length))),table=Array.from({length:levels},()=>Array(a.length));
    for(let k=0;k<levels;k++){const block=1<<(k+1),half=block>>1;for(let start=0;start<a.length;start+=block){const mid=Math.min(start+half,a.length),end=Math.min(start+block,a.length);if(mid>start){table[k][mid-1]=a[mid-1];for(let i=mid-2;i>=start;i--)table[k][i]=a[i]+table[k][i+1];}if(mid<end){table[k][mid]=a[mid];for(let i=mid+1;i<end;i++)table[k][i]=table[k][i-1]+a[i];}}push(`构建第 ${k} 层`,[k,k,'--'],{values:table[k].map(v=>v??'·')},`BLOCK SIZE ${block}`);}
    const query=(l,r)=>l===r?a[l]:table[Math.floor(Math.log2(l^r))][l]+table[Math.floor(Math.log2(l^r))][r];for(const [l,r] of queries){must(Number.isInteger(l)&&Number.isInteger(r)&&l>=0&&l<=r&&r<a.length,'查询区间越界');const k=l===r?0:Math.floor(Math.log2(l^r)),answer=query(l,r);push(`查询 [${l},${r}]`,[`Q ${l}-${r}`,k,answer],{values:a,range:[l,r]},'LEFT SUFFIX + RIGHT PREFIX');}
  }

  function buildMergeSortTree() {
    const a=numList($('input-a').value),[ql,qr,x]=numList($('input-b').value);must(a.length&&ql>=0&&ql<=qr&&qr<a.length,'查询格式或范围错误');const tree=Array(a.length*4),merge=(u,v)=>{const r=[];let i=0,j=0;while(i<u.length||j<v.length)r.push(j>=v.length||(i<u.length&&u[i]<=v[j])?u[i++]:v[j++]);return r;};let built=0;
    function build(p,l,r){if(l===r)tree[p]=[a[l]];else{const m=(l+r)>>1;build(p*2,l,m);build(p*2+1,m+1,r);tree[p]=merge(tree[p*2],tree[p*2+1]);}built++;push(`建立节点 [${l},${r}]`,[built,0,'--'],{values:tree[p]},'STORE SORTED VALUES');}
    const upper=(arr,v)=>{let l=0,r=arr.length;while(l<r){const m=(l+r)>>1;if(arr[m]<=v)l=m+1;else r=m;}return l;};let visited=0;function query(p,l,r){if(qr<l||r<ql)return 0;visited++;if(ql<=l&&r<=qr)return upper(tree[p],x);const m=(l+r)>>1;return query(p*2,l,m)+query(p*2+1,m+1,r);}build(1,0,a.length-1);const answer=query(1,0,a.length-1);push(`统计 [${ql},${qr}] 中 ≤ ${x}`,[built,visited,answer],{values:a,range:[ql,qr]},'BINARY SEARCH COVERED NODES');
  }

  function buildLiChao() {
    const lines=groups($('input-a').value).map(numList),xs=numList($('input-b').value);must(lines.length&&xs.length,'请输入直线和查询点');const domain=[...new Set(xs)].sort((a,b)=>a-b),tree=Array(domain.length*4).fill(null),f=(line,x)=>line[0]*x+line[1];let nodes=0;
    function add(line,p=1,l=0,r=domain.length-1){if(!tree[p]){tree[p]=line;nodes++;return;}const m=(l+r)>>1,mid=domain[m];if(f(line,mid)<f(tree[p],mid))[line,tree[p]]=[tree[p],line];if(l===r)return;if(f(line,domain[l])<f(tree[p],domain[l]))add(line,p*2,l,m);else if(f(line,domain[r])<f(tree[p],domain[r]))add(line,p*2+1,m+1,r);}
    function query(i,p=1,l=0,r=domain.length-1){if(p>=tree.length)return Infinity;let best=tree[p]?f(tree[p],domain[i]):Infinity;if(l===r)return best;const m=(l+r)>>1;return Math.min(best,i<=m?query(i,p*2,l,m):query(i,p*2+1,m+1,r));}
    lines.forEach((line,i)=>{must(line.length===2&&line.every(Number.isFinite),'直线格式错误');add(line);push(`插入 y=${line[0]}x+${line[1]}`,[`L${i+1}`,nodes,'--'],{lines:lines.slice(0,i+1).map(v=>`y=${v[0]}x+${v[1]}`)},'KEEP MIDPOINT WINNER');});xs.forEach((x,i)=>{const answer=query(domain.indexOf(x));push(`查询 x=${x}`,[`Q${i+1}`,nodes,answer],{lines:lines.map(v=>`y=${v[0]}x+${v[1]} → ${f(v,x)}`)},'MINIMUM LINE VALUE');});
  }

  function buildSegmentTreeBeats() {
    const a=numList($('input-a').value),ops=groups($('input-b').value);must(a.length&&ops.length,'请输入数组和操作');const n=a.length,t=Array(n*4);let touched=0;
    function pull(p){const A=t[p*2],B=t[p*2+1],N=t[p];N.sum=A.sum+B.sum;if(A.max1===B.max1){N.max1=A.max1;N.count=A.count+B.count;N.max2=Math.max(A.max2,B.max2);}else if(A.max1>B.max1){N.max1=A.max1;N.count=A.count;N.max2=Math.max(A.max2,B.max1);}else{N.max1=B.max1;N.count=B.count;N.max2=Math.max(A.max1,B.max2);}}
    function build(p,l,r){t[p]={sum:0,max1:-Infinity,max2:-Infinity,count:0};if(l===r){t[p]={sum:a[l],max1:a[l],max2:-Infinity,count:1};return;}const m=(l+r)>>1;build(p*2,l,m);build(p*2+1,m+1,r);pull(p);}
    function apply(p,x){if(t[p].max1<=x)return;t[p].sum+=(x-t[p].max1)*t[p].count;t[p].max1=x;touched++;}function down(p){apply(p*2,t[p].max1);apply(p*2+1,t[p].max1);}function chmin(p,l,r,ql,qr,x){if(qr<l||r<ql||t[p].max1<=x)return;if(ql<=l&&r<=qr&&t[p].max2<x){apply(p,x);return;}down(p);const m=(l+r)>>1;chmin(p*2,l,m,ql,qr,x);chmin(p*2+1,m+1,r,ql,qr,x);pull(p);}function sum(p,l,r,ql,qr){if(qr<l||r<ql)return 0;if(ql<=l&&r<=qr)return t[p].sum;down(p);const m=(l+r)>>1;return sum(p*2,l,m,ql,qr)+sum(p*2+1,m+1,r,ql,qr);}
    function materialize(p,l,r,out){if(l===r){out[l]=t[p].max1;return;}down(p);const m=(l+r)>>1;materialize(p*2,l,m,out);materialize(p*2+1,m+1,r,out);}build(1,0,n-1);for(const raw of ops){const p=raw.split(/\s+/),type=p[0].toLowerCase(),l=Number(p[1]),r=Number(p[2]);must(l>=0&&l<=r&&r<n,`范围错误：${raw}`);touched=0;let answer;if(type==='chmin'){const x=Number(p[3]);must(Number.isFinite(x),'chmin 缺少上界');chmin(1,0,n-1,l,r,x);answer=t[1].sum;}else if(type==='sum')answer=sum(1,0,n-1,l,r);else throw new Error(`未知操作：${raw}`);const values=[];materialize(1,0,n-1,values);push(`执行 ${raw}`,[raw,touched,answer],{values,range:[l,r]},type==='chmin'?'BEAT CURRENT MAXIMUM':'RANGE SUM');}}

  function buildPersistentTrie() {
    const words=$('input-a').value.split(/[\s,]+/).filter(Boolean),[versionRaw,prefixRaw]=$('input-b').value.split(','),version=Number(versionRaw),prefix=(prefixRaw||'').trim();must(words.length&&Number.isInteger(version)&&version>=0&&version<=words.length,'版本必须位于 0 到单词数量之间');const empty=()=>({count:0,next:{}}),roots=[empty()];let created=0;
    function insert(root,word){const nr={count:root.count+1,next:{...root.next}};created++;let old=root,cur=nr;for(const ch of word){const oldChild=old.next[ch]||empty(),child={count:oldChild.count+1,next:{...oldChild.next}};created++;cur.next[ch]=child;old=oldChild;cur=child;}return nr;}
    words.forEach((word,i)=>{const before=created;roots.push(insert(roots.at(-1),word));push(`版本 ${i+1} 插入 ${word}`,[i+1,created-before,'--'],{lines:words.slice(0,i+1)},'PATH COPYING');});let node=roots[version];for(const ch of prefix)node=node?.next[ch];const answer=node?.count||0;push(`版本 ${version} 查询 ${prefix}`,[version,created,answer],{lines:words.slice(0,version).filter(w=>w.startsWith(prefix))},'PREFIX COUNT');
  }

  function buildCoordinateCompression(){const a=numList($('input-a').value);must(a.length,'请输入整数序列');const sorted=[...new Set(a)].sort((x,y)=>x-y),rank=new Map(sorted.map((v,i)=>[v,i]));a.forEach((v,i)=>push(`映射 ${v} → ${rank.get(v)}`,[v,rank.get(v),sorted.length],{values:a.map(x=>rank.get(x)),selected:[i]},'ORDER-PRESERVING RANK'));}

  function buildInversionCount(){const a=numList($('input-a').value);must(a.length,'请输入整数数组');let total=0;function sort(arr,offset){if(arr.length<=1)return arr;const m=arr.length>>1,L=sort(arr.slice(0,m),offset),R=sort(arr.slice(m),offset+m),out=[];let i=0,j=0,add=0;while(i<L.length||j<R.length){if(j>=R.length||(i<L.length&&L[i]<=R[j]))out.push(L[i++]);else{out.push(R[j++]);add+=L.length-i;}}total+=add;push(`归并 [${offset},${offset+arr.length-1}]`,[`${offset}-${offset+arr.length-1}`,add,total],{values:out},'COUNT CROSS INVERSIONS');return out;}sort(a,0);}

  function buildMedianOfMedians(){const a=numList($('input-a').value),k=Math.round(Number($('input-b').value));must(k>=1&&k<=a.length,'K 必须位于数组范围内');function select(arr,rank){if(arr.length<=5){const s=[...arr].sort((x,y)=>x-y);push(`直接排序 ${arr.length} 项`,[arr.length,s[Math.floor(s.length/2)],s[rank]],{values:s,selected:[rank]},'BASE GROUP');return s[rank];}const med=[];for(let i=0;i<arr.length;i+=5){const g=arr.slice(i,i+5).sort((x,y)=>x-y);med.push(g[g.length>>1]);}const pivot=select(med,med.length>>1),lo=arr.filter(x=>x<pivot),eq=arr.filter(x=>x===pivot),hi=arr.filter(x=>x>pivot);push(`按枢轴 ${pivot} 分区`,[arr.length,pivot,'--'],{values:[...lo,...eq,...hi],selected:Array.from({length:eq.length},(_,i)=>lo.length+i)},'30/70 PIVOT GUARANTEE');if(rank<lo.length)return select(lo,rank);if(rank<lo.length+eq.length)return pivot;return select(hi,rank-lo.length-eq.length);}const answer=select(a,k-1);push(`找到第 ${k} 小`,[a.length,'DONE',answer],{values:[...a].sort((x,y)=>x-y),selected:[k-1]},'DETERMINISTIC LINEAR SELECTION');}

  function buildMeetInMiddle(){const a=numList($('input-a').value),target=Number($('input-b').value);must(a.length&&Number.isFinite(target),'请输入集合与目标值');const mid=a.length>>1,enumerate=arr=>{const out=[];for(let mask=0;mask<1<<arr.length;mask++){let sum=0;for(let i=0;i<arr.length;i++)if(mask>>i&1)sum+=arr[i];out.push(sum);}return out;},L=enumerate(a.slice(0,mid)),R=enumerate(a.slice(mid)).sort((x,y)=>x-y);push('枚举左半子集和',[L.length,0,'--'],{values:L.slice(0,24)},'LEFT HALF');push('枚举右半并排序',[L.length,R.length,'--'],{values:R.slice(0,24)},'RIGHT HALF');let found=false;for(const x of L){let l=0,r=R.length-1;while(l<=r){const m=(l+r)>>1,s=x+R[m];if(s===target){found=true;break;}if(s<target)l=m+1;else r=m-1;}if(found)break;}push(`目标 ${target}${found?'可达':'不可达'}`,[L.length,R.length,found?'可达':'不可达'],{lines:[`target = ${target}`,`left states = ${L.length}`,`right states = ${R.length}`]},'COMBINE TWO HALVES');}

  function buildIntrosort(){const a=numList($('input-a').value),maxDepth=2*Math.floor(Math.log2(Math.max(2,a.length)));must(a.length,'请输入数组');let compares=0;const swap=(i,j)=>[a[i],a[j]]=[a[j],a[i]];function insertion(l,r){for(let i=l+1;i<=r;i++){const x=a[i];let j=i-1;while(j>=l&&(compares++,a[j]>x)){a[j+1]=a[j--];}a[j+1]=x;}}function heap(l,r){const n=r-l+1;function down(i,size){while(i*2+1<size){let c=i*2+1;if(c+1<size&&(compares++,a[l+c+1]>a[l+c]))c++;if((compares++,a[l+i]>=a[l+c]))break;swap(l+i,l+c);i=c;}}for(let i=(n>>1)-1;i>=0;i--)down(i,n);for(let end=n-1;end>0;end--){swap(l,l+end);down(0,end);}}function intro(l,r,depth){if(r-l<4){insertion(l,r);push(`小区间插入排序 [${l},${r}]`,['INSERTION',compares,a[r]],{values:[...a],range:[l,r]},'SMALL PARTITION');return;}if(depth===0){heap(l,r);push(`深度耗尽，切换堆排序`,['HEAP FALLBACK',compares,a[r]],{values:[...a],range:[l,r]},'WORST-CASE GUARD');return;}const pivot=a[(l+r)>>1];let i=l,j=r;while(i<=j){while((compares++,a[i]<pivot))i++;while((compares++,a[j]>pivot))j--;if(i<=j)swap(i++,j--);}push(`按枢轴 ${pivot} 分区`,['PARTITION',compares,Math.max(...a)],{values:[...a],range:[l,r]},`DEPTH ${depth}`);if(l<j)intro(l,j,depth-1);if(i<r)intro(i,r,depth-1);}intro(0,a.length-1,maxDepth);push('排序完成',['DONE',compares,a.at(-1)],{values:a,selected:a.map((_,i)=>i)},'INTROSORT COMPLETE');}

  function buildTimsort(){const a=numList($('input-a').value),minRun=Math.min(4,a.length);must(a.length,'请输入数组');let merges=0,found=0;const runs=[];function insertion(l,r){for(let i=l+1;i<r;i++){const x=a[i];let j=i-1;while(j>=l&&a[j]>x)a[j+1]=a[j--];a[j+1]=x;}}function mergeAt(index){const left=runs[index],right=runs[index+1],x=a.slice(left.l,left.r),y=a.slice(right.l,right.r);let i=0,j=0,k=left.l;while(i<x.length||j<y.length)a[k++]=j>=y.length||(i<x.length&&x[i]<=y[j])?x[i++]:y[j++];runs.splice(index,2,{l:left.l,r:right.r});merges++;push('按栈不变量归并相邻 Run',[found,merges,Math.max(...a)],{values:[...a],range:[left.l,right.r-1]},'TIMSORT STACK COLLAPSE');}let start=0;while(start<a.length){let end=start+1;if(end<a.length){if(a[end]<a[start]){while(end<a.length&&a[end]<a[end-1])end++;a.splice(start,end-start,...a.slice(start,end).reverse());}else while(end<a.length&&a[end]>=a[end-1])end++;}if(end-start<minRun){end=Math.min(a.length,start+minRun);insertion(start,end);}runs.push({l:start,r:end});found++;push(`识别自然 Run ${found}`,[found,merges,Math.max(...a)],{values:[...a],range:[start,end-1]},'NATURAL RUN');while(runs.length>=3){const n=runs.length,A=runs[n-3].r-runs[n-3].l,B=runs[n-2].r-runs[n-2].l,C=runs[n-1].r-runs[n-1].l;if(A>B+C&&B>C)break;mergeAt(A<C?n-3:n-2);}while(runs.length>=2){const n=runs.length,B=runs[n-2].r-runs[n-2].l,C=runs[n-1].r-runs[n-1].l;if(B>C)break;mergeAt(n-2);}start=end;}while(runs.length>1)mergeAt(runs.length-2);push('排序完成',[found,merges,a.at(-1)],{values:a,selected:a.map((_,i)=>i)},'TIMSORT COMPLETE');}

  function buildExternalMerge(){const a=numList($('input-a').value),chunk=Math.max(2,Math.round(Number($('input-b').value))||4);must(a.length,'请输入数据流');const runs=[];for(let i=0;i<a.length;i+=chunk){runs.push(a.slice(i,i+chunk).sort((x,y)=>x-y));push(`内存排序 Run ${runs.length}`,['RUN GENERATION',runs.length,'--'],{lines:runs.map((r,j)=>`R${j+1}: ${r.join(', ')}`)},'WRITE SORTED RUN');}const pos=Array(runs.length).fill(0),out=[];while(out.length<a.length){let ri=-1,best=Infinity;for(let i=0;i<runs.length;i++)if(pos[i]<runs[i].length&&runs[i][pos[i]]<best){best=runs[i][pos[i]];ri=i;}out.push(best);pos[ri]++;if(out.length===1||out.length===a.length||out.length%chunk===0)push(`多路归并输出 ${out.length} 项`,['K-WAY MERGE',runs.length,out.at(-1)],{values:[...out]},'SEQUENTIAL READ');}}

  function buildBranchBound(){const items=groups($('input-a').value).map(numList).filter(x=>x.length===2).map(([w,v])=>({w,v,r:v/w})).sort((a,b)=>b.r-a.r),cap=Number($('input-b').value);must(items.length&&cap>0,'请输入物品与容量');let best=0,expanded=0,pruned=0;function bound(level,w,v){if(w>cap)return -Infinity;let value=v,weight=w;for(let i=level;i<items.length;i++){if(weight+items[i].w<=cap){weight+=items[i].w;value+=items[i].v;}else{value+=(cap-weight)*items[i].r;break;}}return value;}const q=[{level:0,w:0,v:0,b:bound(0,0,0)}];while(q.length){q.sort((a,b)=>b.b-a.b);const n=q.shift();if(n.b<=best){pruned++;continue;}expanded++;if(n.level===items.length)continue;const item=items[n.level],take={level:n.level+1,w:n.w+item.w,v:n.v+item.v};if(take.w<=cap){best=Math.max(best,take.v);take.b=bound(take.level,take.w,take.v);if(take.b>best)q.push(take);else pruned++;}const skip={level:n.level+1,w:n.w,v:n.v};skip.b=bound(skip.level,skip.w,skip.v);if(skip.b>best)q.push(skip);else pruned++;push(`展开第 ${n.level} 层节点`,[expanded,pruned,best],{lines:[`weight ${n.w} / ${cap}`,`value ${n.v}`,`upper bound ${n.b.toFixed(1)}`]},'BEST-FIRST SEARCH');}push('搜索完成',[expanded,pruned,best],{lines:[`optimal value = ${best}`]},'BOUND PROVED OPTIMAL');}

  function buildKosaraju(){const edges=parseEdges($('input-a').value),nodes=nodesOf(edges),g=Object.fromEntries(nodes.map(n=>[n,[]])),rg=Object.fromEntries(nodes.map(n=>[n,[]]));for(const[u,v]of edges){g[u].push(v);rg[v].push(u);}const seen=new Set(),order=[];function dfs(u){seen.add(u);for(const v of g[u])if(!seen.has(v))dfs(v);order.push(u);}for(const n of nodes)if(!seen.has(n))dfs(n);push('第一遍 DFS 生成完成序',['PASS 1',seen.size,0],{lines:[`finish: ${order.join(' → ')}`]},'ORIGINAL GRAPH');seen.clear();let count=0;function rev(u,comp){seen.add(u);comp.push(u);for(const v of rg[u])if(!seen.has(v))rev(v,comp);}while(order.length){const u=order.pop();if(seen.has(u))continue;const comp=[];rev(u,comp);count++;push(`转置图找到分量 ${count}`,['PASS 2',seen.size,count],{lines:[`SCC ${count}: ${comp.join(', ')}`]},'REVERSE GRAPH');}}

  function buildBiconnected(){const edges=parseEdges($('input-a').value),nodes=nodesOf(edges),g=Object.fromEntries(nodes.map(n=>[n,[]]));edges.forEach(([u,v],i)=>{g[u].push([v,i]);g[v].push([u,i]);});const dfn={},low={},stack=[];let time=0,count=0;function dfs(u,parentEdge=-1){dfn[u]=low[u]=++time;for(const[v,id]of g[u]){if(id===parentEdge)continue;if(!dfn[v]){stack.push(id);dfs(v,id);low[u]=Math.min(low[u],low[v]);if(low[v]>=dfn[u]){const comp=[];let e;do{e=stack.pop();comp.push(edges[e].join('-'));}while(e!==id);count++;push(`形成双连通分量 ${count}`,[u,stack.length,count],{lines:comp},'LOW[CHILD] ≥ DFN[PARENT]');}}else if(dfn[v]<dfn[u]){stack.push(id);low[u]=Math.min(low[u],dfn[v]);}}}for(const n of nodes)if(!dfn[n])dfs(n);}

  function buildDagShortest(){const edges=parseEdges($('input-a').value,true),[source,target]=$('input-b').value.split(',').map(x=>x.trim()),nodes=nodesOf(edges),g=Object.fromEntries(nodes.map(n=>[n,[]])),indeg=Object.fromEntries(nodes.map(n=>[n,0]));for(const[u,v,w]of edges){must(Number.isFinite(w),'边权必须是数字');g[u].push([v,w]);indeg[v]++;}const q=nodes.filter(n=>!indeg[n]),order=[];while(q.length){const u=q.shift();order.push(u);for(const[v]of g[u])if(--indeg[v]===0)q.push(v);}must(order.length===nodes.length,'输入图不是 DAG');const dist=Object.fromEntries(nodes.map(n=>[n,Infinity]));dist[source]=0;let relax=0;for(const u of order){for(const[v,w]of g[u])if(dist[u]+w<dist[v]){dist[v]=dist[u]+w;relax++;}push(`处理拓扑节点 ${u}`,[u,relax,dist[target]],{lines:nodes.map(n=>`${n}: ${metric(dist[n])}`)},'RELAX OUTGOING EDGES');}}

  function buildTreeDiameter(){const edges=parseEdges($('input-a').value),nodes=nodesOf(edges),g=Object.fromEntries(nodes.map(n=>[n,[]]));for(const[u,v]of edges){g[u].push(v);g[v].push(u);}must(edges.length===nodes.length-1,'输入必须是一棵树');function far(start){const q=[start],dist={[start]:0};for(let i=0;i<q.length;i++)for(const v of g[q[i]])if(dist[v]===undefined){dist[v]=dist[q[i]]+1;q.push(v);}const node=q.reduce((a,b)=>dist[a]>dist[b]?a:b);return{node,dist,path:q};}const first=far(nodes[0]);push(`从 ${nodes[0]} 找到端点 ${first.node}`,[1,first.node,first.dist[first.node]],{lines:first.path.map(n=>`${n}: ${first.dist[n]}`)},'FIRST BFS');const second=far(first.node);push(`从 ${first.node} 找到另一端 ${second.node}`,[2,second.node,second.dist[second.node]],{lines:second.path.map(n=>`${n}: ${second.dist[n]}`)},'SECOND BFS');}

  function buildRerooting(){const edges=parseEdges($('input-a').value),nodes=nodesOf(edges),g=Object.fromEntries(nodes.map(n=>[n,[]]));for(const[u,v]of edges){g[u].push(v);g[v].push(u);}const root=nodes[0],size={},depth={},parent={[root]:null};let initial=0;function dfs(u,d){size[u]=1;depth[u]=d;initial+=d;for(const v of g[u])if(v!==parent[u]){parent[v]=u;dfs(v,d+1);size[u]+=size[v];}}dfs(root,0);const ans={[root]:initial};function reroot(u){for(const v of g[u])if(parent[v]===u){ans[v]=ans[u]+nodes.length-2*size[v];push(`把根从 ${u} 移到 ${v}`,[v,ans[v],'--'],{lines:nodes.filter(x=>ans[x]!==undefined).map(x=>`${x}: ${ans[x]}`)},`SIZE[${v}] = ${size[v]}`);reroot(v);}}push(`计算根 ${root} 的距离和`,[root,initial,root],{lines:nodes.map(n=>`${n}: depth ${depth[n]}`)},'POSTORDER');reroot(root);const best=nodes.reduce((a,b)=>ans[a]<=ans[b]?a:b);push(`最优根为 ${best}`,[best,ans[best],best],{lines:nodes.map(n=>`${n}: ${ans[n]}`)},'ALL ROOT ANSWERS');}

  function buildDsuOnTree(){const edges=parseEdges($('input-a').value),nodes=nodesOf(edges).sort(),colors=numList($('input-b').value);must(colors.length===nodes.length,'颜色数量必须与节点数量一致');const color=Object.fromEntries(nodes.map((n,i)=>[n,colors[i]])),g=Object.fromEntries(nodes.map(n=>[n,[]]));for(const[u,v]of edges){g[u].push(v);g[v].push(u);}let merged=0;function dfs(u,p){let map=new Map([[color[u],1]]);for(const v of g[u])if(v!==p){let child=dfs(v,u);if(child.size>map.size)[map,child]=[child,map];for(const[c,n]of child){map.set(c,(map.get(c)||0)+n);merged++;}}const best=Math.max(...map.values());push(`合并节点 ${u} 的子树`,[merged,map.size,best],{lines:[...map].map(([c,n])=>`color ${c}: ${n}`)},'SMALL MAP INTO LARGE MAP');return map;}dfs(nodes[0],null);}

  function buildOfflineConnectivity(){const ops=groups($('input-a').value).map(raw=>{const[type,u,v]=raw.split(/\s+/);must(['add','remove','query'].includes(type)&&u&&v,`操作格式错误：${raw}`);return{type,u,v,raw};}),n=ops.length,key=(u,v)=>u<v?`${u}|${v}`:`${v}|${u}`,active=new Map(),intervals=[];ops.forEach((op,t)=>{const k=key(op.u,op.v);if(op.type==='add')active.set(k,[t,op.u,op.v]);else if(op.type==='remove'){must(active.has(k),`删除了不存在的边 ${k}`);const[s,u,v]=active.get(k);intervals.push([s,t,u,v]);active.delete(k);}});for(const[s,u,v]of active.values())intervals.push([s,n,u,v]);const seg=Array.from({length:n*4+4},()=>[]);function add(p,l,r,ql,qr,e){if(ql>=r||qr<=l)return;if(ql<=l&&r<=qr){seg[p].push(e);return;}const m=(l+r)>>1;add(p*2,l,m,ql,qr,e);add(p*2+1,m,r,ql,qr,e);}for(const[l,r,u,v]of intervals)if(l<r)add(1,0,n,l,r,[u,v]);const names=[...new Set(ops.flatMap(o=>[o.u,o.v]))],id=new Map(names.map((x,i)=>[x,i])),parent=names.map((_,i)=>i),size=names.map(()=>1),history=[];function find(x){while(parent[x]!==x)x=parent[x];return x;}function unite(a,b){a=find(id.get(a));b=find(id.get(b));if(a===b){history.push(null);return;}if(size[a]<size[b])[a,b]=[b,a];history.push([b,size[a]]);parent[b]=a;size[a]+=size[b];}function rollback(snapshot){while(history.length>snapshot){const item=history.pop();if(!item)continue;const[b,old]=item,a=parent[b];size[a]=old;parent[b]=b;}}let yes=0;function dfs(p,l,r){const snap=history.length;for(const e of seg[p])unite(...e);if(r-l===1){const op=ops[l];if(op.type==='query'){const ok=find(id.get(op.u))===find(id.get(op.v));if(ok)yes++;push(`时刻 ${l}: ${op.raw}`,[l,history.length,yes],{lines:[`${op.u} ↔ ${op.v}: ${ok?'connected':'disconnected'}`]},'ANSWER AT LEAF TIME');}}else{const m=(l+r)>>1;dfs(p*2,l,m);dfs(p*2+1,m,r);}rollback(snap);}dfs(1,0,n);}

  function buildLowerBoundFlow(){const rows=groups($('input-a').value).map(row=>{const p=row.split(',').map(x=>x.trim());return[p[0],p[1],Number(p[2]),Number(p[3])];});must(rows.length&&rows.every(e=>e.length===4&&e[2]>=0&&e[3]>=e[2]),'边格式或上下界错误');const nodes=nodesOf(rows),idx=new Map(nodes.map((n,i)=>[n,i])),SS=nodes.length,TT=nodes.length+1,N=nodes.length+2,g=Array.from({length:N},()=>[]);function edge(u,v,c){const a={to:v,cap:c,rev:g[v].length},b={to:u,cap:0,rev:g[u].length};g[u].push(a);g[v].push(b);}const bal=Array(nodes.length).fill(0);for(const[u,v,l,h]of rows){edge(idx.get(u),idx.get(v),h-l);bal[idx.get(u)]-=l;bal[idx.get(v)]+=l;}let need=0;for(let i=0;i<nodes.length;i++)if(bal[i]>0){edge(SS,i,bal[i]);need+=bal[i];}else if(bal[i]<0)edge(i,TT,-bal[i]);let flow=0,round=0;while(true){const level=Array(N).fill(-1),q=[SS];level[SS]=0;for(let i=0;i<q.length;i++)for(const e of g[q[i]])if(e.cap>0&&level[e.to]<0){level[e.to]=level[q[i]]+1;q.push(e.to);}if(level[TT]<0)break;const it=Array(N).fill(0);function dfs(u,f){if(u===TT)return f;for(;it[u]<g[u].length;it[u]++){const e=g[u][it[u]];if(e.cap>0&&level[e.to]===level[u]+1){const d=dfs(e.to,Math.min(f,e.cap));if(d){e.cap-=d;g[e.to][e.rev].cap+=d;return d;}}}return 0;}let f;while((f=dfs(SS,Infinity))){flow+=f;round++;push(`满足 ${f} 单位需求`,[need,flow,flow===need?'可行':'检查中'],{lines:nodes.map((n,i)=>`${n}: balance ${bal[i]}`)},`AUGMENT ${round}`);}}push(flow===need?'存在可行环流':'不存在可行环流',[need,flow,flow===need?'可行':'不可行'],{lines:[`required ${need}`,`delivered ${flow}`]},'SUPER SOURCE / SINK');}

  function buildTreeIsomorphism(){const halves=$('input-a').value.split('|');must(halves.length===2,'请用 | 分隔两棵树');function encode(text){const edges=parseEdges(text),nodes=nodesOf(edges),g=Object.fromEntries(nodes.map(n=>[n,[]]));for(const[u,v]of edges){g[u].push(v);g[v].push(u);}must(edges.length===nodes.length-1,'两侧都必须是树');let deg=Object.fromEntries(nodes.map(n=>[n,g[n].length])),leaves=nodes.filter(n=>deg[n]<=1),remain=nodes.length;while(remain>2){remain-=leaves.length;const next=[];for(const u of leaves)for(const v of g[u])if(--deg[v]===1)next.push(v);leaves=next;}function rooted(u,p){return`(${g[u].filter(v=>v!==p).map(v=>rooted(v,u)).sort().join('')})`;}return{centers:leaves,codes:leaves.map(c=>rooted(c,null)).sort()};}const A=encode(halves[0]),B=encode(halves[1]);push('计算两棵树的中心',[`${A.centers.length}+${B.centers.length}`,'--','比较中'],{lines:[`T1 centers: ${A.centers}`,`T2 centers: ${B.centers}`]},'PEEL LEAVES');const same=A.codes.some(x=>B.codes.includes(x));push('比较规范编码',[`${A.centers.length}+${B.centers.length}`,A.codes[0].length,same?'同构':'不同构'],{lines:[`T1 ${A.codes[0]}`,`T2 ${B.codes[0]}`]},'AHU CANONICAL FORM');}

  function buildProfileDp(){const[r,c]=numList($('input-a').value).map(Math.round);must(r>=1&&c>=1&&r<=8&&c<=8&&r*c%2===0,'请输入不超过 8×8 的偶数格棋盘');let dp=new Map([[0,1]]),processed=0;for(let pos=0;pos<r*c;pos++){const row=Math.floor(pos/c),col=pos%c,next=new Map();for(const[mask,count]of dp){if(mask&1)next.set(mask>>1,(next.get(mask>>1)||0)+count);else{if(row+1<r)next.set((mask>>1)|(1<<(c-1)),(next.get((mask>>1)|(1<<(c-1)))||0)+count);if(col+1<c&&!(mask&2))next.set((mask>>1)|1,(next.get((mask>>1)|1)||0)+count);}}dp=next;processed++;push(`处理格子 (${row},${col})`,[processed,dp.size,dp.get(0)||0],{values:[...dp.keys()].slice(0,24).map(x=>x.toString(2).padStart(c,'0'))},'PROFILE TRANSITION');}push('铺法统计完成',[processed,dp.size,dp.get(0)||0],{lines:[`${r}×${c} domino tilings = ${dp.get(0)||0}`]},'EMPTY FINAL PROFILE');}

  function buildSosDp(){const a=numList($('input-a').value);must(a.length&&(a.length&(a.length-1))===0,'数组长度必须是 2 的幂');const f=[...a],bits=Math.log2(a.length);for(let bit=0;bit<bits;bit++){let updated=0;for(let mask=0;mask<a.length;mask++)if(mask>>bit&1){f[mask]+=f[mask^(1<<bit)];updated++;}push(`加入第 ${bit} 位子集贡献`,[bit,updated,f.at(-1)],{values:[...f],selected:f.map((_,i)=>i).filter(i=>i>>bit&1)},'ZETA TRANSFORM');}}

  function buildProbabilityDp(){const dice=Math.round(Number($('input-a').value)),target=Math.round(Number($('input-b').value));must(dice>=1&&dice<=8&&target>=dice&&target<=6*dice,'骰子数量或目标范围错误');let dp=[1];for(let d=1;d<=dice;d++){const next=Array(d*6+1).fill(0);for(let s=0;s<dp.length;s++)for(let face=1;face<=6;face++)next[s+face]+=(dp[s]||0)/6;dp=next;const prob=dp.slice(target).reduce((a,b)=>a+b,0);push(`投出第 ${d} 枚骰子`,[d,dp.filter(x=>x>0).length,`${(prob*100).toFixed(1)}%`],{values:dp.map(x=>x?Number((x*100).toFixed(1)):0)},'PROBABILITY TRANSITION');}}

  function buildDivideConquerDp(){const a=numList($('input-a').value),K=Math.round(Number($('input-b').value));must(a.length&&K>=1&&K<=a.length,'分组数量错误');const n=a.length,p=[0];for(const x of a)p.push(p.at(-1)+x);const cost=(l,r)=>(p[r]-p[l])**2;let prev=Array(n+1).fill(Infinity);prev[0]=0;for(let group=1;group<=K;group++){const cur=Array(n+1).fill(Infinity);let checks=0;function solve(l,r,optL,optR){if(l>r)return;const mid=(l+r)>>1;let best=-1;for(let j=optL;j<=Math.min(mid-1,optR);j++){checks++;const v=prev[j]+cost(j,mid);if(v<cur[mid]){cur[mid]=v;best=j;}}solve(l,mid-1,optL,best);solve(mid+1,r,best,optR);}solve(group,n,group-1,n-1);prev=cur;push(`完成第 ${group} 层 DP`,[group,checks,prev[n]],{values:prev.slice(1).map(metric)},'MONOTONE OPTIMUM RANGE');}}

  function buildKnuth(){const w=numList($('input-a').value);must(w.length>=2,'请输入至少两堆石子');const n=w.length,p=[0];for(const x of w)p.push(p.at(-1)+x);const sum=(l,r)=>p[r+1]-p[l],dp=Array.from({length:n},()=>Array(n).fill(0)),opt=Array.from({length:n},(_,i)=>Array(n).fill(i));for(let len=2;len<=n;len++)for(let l=0;l+len<=n;l++){const r=l+len-1;dp[l][r]=Infinity;const lo=opt[l][r-1],hi=Math.min(r-1,opt[l+1]?.[r]??r-1);for(let k=lo;k<=hi;k++){const v=dp[l][k]+dp[k+1][r]+sum(l,r);if(v<dp[l][r]){dp[l][r]=v;opt[l][r]=k;}}push(`区间 [${l},${r}]`,[len,`${lo}-${hi}`,dp[l][r]],{matrix:dp.map(row=>row.map(metric)),active:[l,r]},`OPT ${opt[l][r]}`);} }

  function buildCht(){const x=numList($('input-a').value),C=Number($('input-b').value);must(x.length&&x.every((v,i)=>!i||v>=x[i-1])&&Number.isFinite(C),'x 必须递增且 C 有效');const dp=Array(x.length).fill(0),lines=[];const value=(L,q)=>L.m*q+L.b;function add(L){while(lines.length>=2&&(lines.at(-1).b-lines.at(-2).b)*(lines.at(-2).m-L.m)>=(L.b-lines.at(-2).b)*(lines.at(-2).m-lines.at(-1).m))lines.pop();lines.push(L);}add({m:-2*x[0],b:dp[0]+x[0]**2});for(let i=1;i<x.length;i++){while(lines.length>=2&&value(lines[0],x[i])>=value(lines[1],x[i]))lines.shift();dp[i]=x[i]**2+C+value(lines[0],x[i]);add({m:-2*x[i],b:dp[i]+x[i]**2});push(`查询 x=${x[i]}`,[x[i],lines.length,dp[i]],{values:[...dp],selected:[i]},'QUERY HULL THEN ADD LINE');}}

  function buildRollingHash(){const text=$('input-a').value,pattern=$('input-b').value;must(pattern.length&&pattern.length<=text.length,'模式串不能为空且不能长于文本');const mod=1000000007n,base=911382323n,pow=[1n],pre=[0n];for(let i=0;i<text.length;i++){pow.push(pow.at(-1)*base%mod);pre.push((pre.at(-1)*base+BigInt(text.charCodeAt(i)))%mod);}const hash=(l,r)=>(pre[r]-pre[l]*pow[r-l]%mod+mod)%mod,target=(()=>{let h=0n;for(const c of pattern)h=(h*base+BigInt(c.charCodeAt(0)))%mod;return h;})();let hits=0;for(let i=0;i+pattern.length<=text.length;i++){const same=hash(i,i+pattern.length)===target&&text.slice(i,i+pattern.length)===pattern;if(same)hits++;push(`检查窗口 ${i}`,[i,hash(i,i+pattern.length)===target?'相等':'不同',hits],{lines:[text,`${' '.repeat(i)}${'^'.repeat(pattern.length)}`]},'O(1) SUBSTRING HASH');}}

  function buildDuval(){const s=$('input-a').value;must(s.length,'请输入字符串');const factors=[];let i=0;while(i<s.length){let j=i+1,k=i;while(j<s.length&&s[k]<=s[j]){k=s[k]<s[j]?i:k+1;j++;}while(i<=k){const f=s.slice(i,i+j-k);factors.push(f);i+=j-k;push(`得到 Lyndon 因子 ${f}`,[i,f,factors.length],{lines:factors},'NON-INCREASING FACTORIZATION');}}}

  function buildFmIndex(){const original=$('input-a').value,pattern=$('input-b').value,text=`${original}$`;must(original&&!original.includes('$')&&pattern,'文本不能包含 $，模式不能为空');const rotations=Array.from({length:text.length},(_,i)=>({s:text.slice(i)+text.slice(0,i),i})).sort((a,b)=>a.s.localeCompare(b.s)),bwt=rotations.map(r=>text[(r.i+text.length-1)%text.length]).join(''),alphabet=[...new Set(text)].sort(),C={};let total=0;for(const ch of alphabet){C[ch]=total;total+=text.split(ch).length-1;}const occ=Object.fromEntries(alphabet.map(ch=>[ch,[0]]));for(let i=0;i<bwt.length;i++)for(const ch of alphabet)occ[ch].push(occ[ch].at(-1)+(bwt[i]===ch?1:0));push('构建 BWT 与 Occ 表',['BUILD',`0-${text.length}`,text.length],{lines:[`BWT ${bwt}`,`SA ${rotations.map(r=>r.i).join(',')}`]},'FM INDEX');let l=0,r=text.length;for(let i=pattern.length-1;i>=0;i--){const ch=pattern[i];if(C[ch]===undefined){l=r=0;}else{l=C[ch]+occ[ch][l];r=C[ch]+occ[ch][r];}push(`反向加入字符 ${ch}`,[ch,`${l}-${r}`,Math.max(0,r-l)],{lines:[`pattern suffix: ${pattern.slice(i)}`,`SA interval: [${l}, ${r})`]},'BACKWARD SEARCH');}}

  function buildDpll(){const clauses=groups($('input-a').value).map(numList).map(c=>c.map(Math.round));must(clauses.length&&clauses.every(c=>c.length),'请输入 CNF 子句');let nodes=0,propagations=0;function solve(formula,assign){nodes++;while(true){let unit=null;for(const clause of formula){const live=clause.filter(l=>assign[Math.abs(l)]===undefined),sat=clause.some(l=>assign[Math.abs(l)]===(l>0));if(sat)continue;if(!live.length)return null;if(live.length===1){unit=live[0];break;}}if(unit===null)break;assign={...assign,[Math.abs(unit)]:unit>0};propagations++;push(`单位传播 ${unit}`,[nodes,propagations,'检查中'],{lines:Object.entries(assign).map(([v,x])=>`x${v}=${x}`)},'UNIT PROPAGATION');}const allSat=formula.every(c=>c.some(l=>assign[Math.abs(l)]===(l>0)));if(allSat)return assign;const literal=formula.flat().find(l=>assign[Math.abs(l)]===undefined);if(literal===undefined)return null;const variable=Math.abs(literal);for(const value of[true,false]){push(`分支 x${variable}=${value}`,[nodes,propagations,'分支'],{lines:[`decision x${variable}=${value}`]},'DECIDE');const result=solve(formula,{...assign,[variable]:value});if(result)return result;}return null;}const result=solve(clauses,{});push(result?'找到满足赋值':'证明不可满足',[nodes,propagations,result?'可满足':'不可满足'],{lines:result?Object.entries(result).map(([v,x])=>`x${v}=${x}`):['UNSAT']},'DPLL COMPLETE');}

  function buildAc3(){const edges=parseEdges($('input-a').value),nodes=nodesOf(edges),domains=Object.fromEntries(nodes.map(n=>[n,new Set([1,2,3])])),fixed=$('input-b').value.match(/^\s*([^=]+)=(\d+)\s*$/);must(fixed&&domains[fixed[1].trim()]&&domains[fixed[1].trim()].has(Number(fixed[2])),'固定赋值格式错误');domains[fixed[1].trim()]=new Set([Number(fixed[2])]);const queue=[];for(const[u,v]of edges){queue.push([u,v],[v,u]);}const neighbors=Object.fromEntries(nodes.map(n=>[n,[]]));for(const[u,v]of edges){neighbors[u].push(v);neighbors[v].push(u);}let checked=0,removed=0;while(queue.length){const[x,y]=queue.shift();checked++;let revised=false;for(const vx of[...domains[x]])if(![...domains[y]].some(vy=>vx!==vy)){domains[x].delete(vx);removed++;revised=true;}if(!domains[x].size)throw new Error(`变量 ${x} 的取值域为空`);if(revised)for(const z of neighbors[x])if(z!==y)queue.push([z,x]);push(`检查弧 ${x} → ${y}`,[checked,removed,Object.values(domains).reduce((s,d)=>s+d.size,0)],{lines:nodes.map(n=>`${n}: {${[...domains[n]].join(',')}}`)},revised?'DOMAIN REVISED':'ARC CONSISTENT');}}

  const builders = {
    'dynamic-array':buildDynamicArray,'circular-buffer':buildCircularBuffer,'bitset-bitmap':buildBitset,'order-statistic-tree':buildOrderStatistic,'pairing-heap':buildPairingHeap,'radix-tree':buildRadixTree,'rope':buildRope,'disjoint-sparse-table':buildDisjointSparse,'merge-sort-tree':buildMergeSortTree,'li-chao-tree':buildLiChao,'segment-tree-beats':buildSegmentTreeBeats,'persistent-trie':buildPersistentTrie,'coordinate-compression':buildCoordinateCompression,'inversion-count':buildInversionCount,'median-of-medians':buildMedianOfMedians,'meet-in-the-middle':buildMeetInMiddle,'introsort':buildIntrosort,'timsort':buildTimsort,'external-merge-sort':buildExternalMerge,'branch-and-bound':buildBranchBound,'kosaraju-scc':buildKosaraju,'biconnected-components':buildBiconnected,'dag-shortest-path':buildDagShortest,'tree-diameter':buildTreeDiameter,'rerooting-dp':buildRerooting,'dsu-on-tree':buildDsuOnTree,'offline-dynamic-connectivity':buildOfflineConnectivity,'lower-bound-flow':buildLowerBoundFlow,'tree-isomorphism-ahu':buildTreeIsomorphism,'profile-dp':buildProfileDp,'sos-dp':buildSosDp,'probability-dp':buildProbabilityDp,'divide-conquer-dp-optimization':buildDivideConquerDp,'knuth-optimization':buildKnuth,'convex-hull-trick':buildCht,'rolling-hash':buildRollingHash,'duval-lyndon-factorization':buildDuval,'fm-index':buildFmIndex,'dpll-sat':buildDpll,'ac3-constraint-propagation':buildAc3
  };

  function setUpPage(){document.body.className=cfg.theme||'';$('title').textContent=cfg.title;$('monogram').textContent=cfg.mono;$('eyebrow').textContent=cfg.eye;$('primary-label').textContent=cfg.aLabel;$('input-a').value=cfg.a;$('secondary-label').textContent=cfg.bLabel||'';$('input-b').value=cfg.b||'';$('secondary-wrap').hidden=!cfg.bLabel;$('option-wrap').hidden=true;cfg.metrics.forEach((label,i)=>$(`metric-label-${i+1}`).textContent=label);$('principle').textContent=cfg.principle;$('complexity').textContent=cfg.complexity;document.title=`${cfg.title} · Algorithm Lab`;canvas.setAttribute('aria-label',`${cfg.title} 执行状态`);}
  function refreshPalette(){const s=getComputedStyle(document.body);palette={bg:s.getPropertyValue('--bg').trim(),panel:s.getPropertyValue('--panel').trim(),panel2:s.getPropertyValue('--panel-2').trim(),text:s.getPropertyValue('--text').trim(),muted:s.getPropertyValue('--muted').trim(),line:s.getPropertyValue('--line').trim(),accent:s.getPropertyValue('--accent').trim(),accent2:s.getPropertyValue('--accent-2').trim(),good:s.getPropertyValue('--good').trim()};}
  function rounded(x,y,w,h,fill,stroke=palette.line,r=5){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill();ctx.strokeStyle=stroke;ctx.stroke();}
  function label(text,x,y,color=palette.text,align='left',font='12px ui-monospace,Consolas,monospace'){ctx.fillStyle=color;ctx.textAlign=align;ctx.textBaseline='middle';ctx.font=font;ctx.fillText(String(text),x,y);}
  function render(){ctx.fillStyle=palette.bg;ctx.fillRect(0,0,width,height);const state=steps[stepIndex];if(!state)return;const view=state.view||{},top=120,pad=Math.max(24,width*.05),usable=width-pad*2;if(view.matrix){const matrix=view.matrix,rows=matrix.length,cols=Math.max(...matrix.map(r=>r.length)),cell=Math.min(56,usable/Math.max(1,cols)),x=pad,y=top;for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){const active=view.active?.[0]===r&&view.active?.[1]===c;rounded(x+c*cell,y+r*cell,cell-3,Math.min(42,cell-3),active?palette.accent2:palette.panel2);label(matrix[r]?.[c]??'',x+c*cell+(cell-3)/2,y+r*cell+Math.min(42,cell-3)/2,active?palette.bg:palette.text,'center','10px ui-monospace,Consolas,monospace');}}
    if(view.values){const values=view.values.slice(0,48),cols=Math.max(1,Math.min(values.length,Math.floor(usable/52))),cell=Math.min(52,usable/cols),rows=Math.ceil(values.length/cols);values.forEach((v,i)=>{const row=Math.floor(i/cols),col=i%cols,x=pad+col*cell,y=top+row*52,selected=view.selected?.includes(i),inRange=view.range&&i>=view.range[0]&&i<=view.range[1];rounded(x,y,cell-5,42,selected?palette.accent:inRange?palette.accent2:palette.panel2);label(v,x+(cell-5)/2,y+21,selected||inRange?palette.bg:palette.text,'center');});if(rows*52>height-top-80)label('仅显示前 48 项',pad,height-42,palette.muted);}
    if(view.lines){const lines=view.lines.slice(0,18),lineH=Math.min(34,Math.max(24,(height-top-90)/Math.max(1,lines.length)));lines.forEach((line,i)=>{rounded(pad,top+i*lineH,usable,lineH-5,i===lines.length-1?palette.panel2:palette.panel);label(line,pad+13,top+i*lineH+(lineH-5)/2,i===lines.length-1?palette.accent:palette.text);});}
    if(!view.values&&!view.lines&&!view.matrix){label(state.note||cfg.eye,pad,top,palette.accent);}
  }
  function updateUi(){const state=steps[stepIndex];if(!state)return;$('status').textContent=state.label;state.metrics.forEach((value,i)=>$(`metric-${i+1}`).textContent=value);$('note').textContent=`${state.note||cfg.eye} · STEP ${stepIndex+1} / ${steps.length}`;$('play').textContent=running?'暂停':stepIndex===steps.length-1?'重播':'播放';}
  function build(){steps=[];$('error').textContent='';try{builders[slug]();}catch(error){$('error').textContent=error.message;return false;}if(!steps.length){$('error').textContent='未生成执行步骤';return false;}stepIndex=0;running=false;lastTick=0;updateUi();return true;}
  function stepOnce(){if(stepIndex<steps.length-1)stepIndex++;else running=false;updateUi();}
  function resize(){const rect=canvas.getBoundingClientRect();width=rect.width;height=rect.height;dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);refreshPalette();}
  function frame(time){if(running&&(lastTick===0||time-lastTick>520/speed)){stepOnce();lastTick=time;}render();requestAnimationFrame(frame);}
  $('apply').addEventListener('click',build);$('reset').addEventListener('click',()=>{$('input-a').value=cfg.a;$('input-b').value=cfg.b||'';build();});$('step').addEventListener('click',()=>{running=false;if(stepIndex===steps.length-1)build();stepOnce();});$('play').addEventListener('click',()=>{if(stepIndex===steps.length-1)build();running=!running;lastTick=0;updateUi();});$('speed').addEventListener('input',e=>{speed=Number(e.target.value);$('speed-value').textContent=`${speed.toFixed(1)}x`;});addEventListener('resize',resize);
  setUpPage();resize();build();requestAnimationFrame(frame);
})();
