(() => {
  'use strict';
  const MAX_POP=450,MAX_LIFE=360,canvas=document.getElementById('canvas'),ctx=canvas.getContext('2d',{alpha:false});
  const state={population:220,lifespan:260,speed:3,mutation:.015,elite:.05,thrust:.16,tool:'target',paused:false};
  const x=new Float32Array(MAX_POP),y=new Float32Array(MAX_POP),vx=new Float32Array(MAX_POP),vy=new Float32Array(MAX_POP),fitness=new Float64Array(MAX_POP),minDistance=new Float32Array(MAX_POP),completion=new Int16Array(MAX_POP),flags=new Uint8Array(MAX_POP);
  let dna=new Float32Array(MAX_POP*MAX_LIFE*2),nextDna=new Float32Array(MAX_POP*MAX_LIFE*2),width=1,height=1,dpr=1,generation=1,lifeFrame=0,targetX=.5,targetY=.16,bestDistance=Infinity,success=0,totalSuccess=0;
  let obstacles=[];
  const controls={population:document.getElementById('population'),lifespan:document.getElementById('lifespan'),speed:document.getElementById('speed'),mutation:document.getElementById('mutation'),elite:document.getElementById('elite'),thrust:document.getElementById('thrust')};
  const outputs={population:document.getElementById('population-value'),lifespan:document.getElementById('lifespan-value'),speed:document.getElementById('speed-value'),mutation:document.getElementById('mutation-value'),elite:document.getElementById('elite-value'),thrust:document.getElementById('thrust-value')};
  const format={population:v=>Math.round(v),lifespan:v=>Math.round(v),speed:v=>`${Math.round(v)}×`,mutation:v=>`${Number(v).toFixed(1)}%`,elite:v=>`${Math.round(v)}%`,thrust:v=>Number(v).toFixed(2)};
  function syncRange(key){const input=controls[key],min=+input.min,max=+input.max;input.style.setProperty('--progress',`${(+input.value-min)/(max-min)*100}%`);outputs[key].textContent=format[key](input.value)}
  function geneIndex(i,frame){return(i*MAX_LIFE+frame)*2}
  function randomGene(array,i,frame){const angle=-Math.PI/2+(Math.random()-.5)*Math.PI*1.15,idx=geneIndex(i,frame);array[idx]=Math.cos(angle);array[idx+1]=Math.sin(angle)}
  function defaultObstacles(){obstacles=[{x:.08,y:.52,w:.34,h:.025},{x:.58,y:.52,w:.34,h:.025},{x:.22,y:.33,w:.20,h:.022},{x:.58,y:.33,w:.20,h:.022}]}
  function initDna(){for(let i=0;i<state.population;i++)for(let f=0;f<state.lifespan;f++)randomGene(dna,i,f)}
  function resetRockets(){lifeFrame=0;bestDistance=Infinity;success=0;const tx=targetX*width,ty=targetY*height;for(let i=0;i<state.population;i++){x[i]=width*.5+(Math.random()-.5)*12;y[i]=height-42;vx[i]=0;vy[i]=0;flags[i]=0;completion[i]=-1;minDistance[i]=Math.hypot(x[i]-tx,y[i]-ty)}}
  function restart(){generation=1;totalSuccess=0;initDna();resetRockets();updateMetrics()}
  function resize(){const rect=canvas.getBoundingClientRect(),oldW=width,oldH=height;width=Math.max(1,rect.width);height=Math.max(1,rect.height);dpr=Math.min(2,window.devicePixelRatio||1);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);if(oldW>1&&oldH>1)for(let i=0;i<state.population;i++){x[i]=x[i]/oldW*width;y[i]=y[i]/oldH*height}}
  function collide(px,py){for(const o of obstacles)if(px>o.x*width&&px<(o.x+o.w)*width&&py>o.y*height&&py<(o.y+o.h)*height)return true;return false}
  function simulateStep(){const tx=targetX*width,ty=targetY*height;for(let i=0;i<state.population;i++){if(flags[i])continue;const gi=geneIndex(i,lifeFrame),ax=dna[gi]*state.thrust,ay=dna[gi+1]*state.thrust;vx[i]+=ax;vy[i]+=ay;const velocity=Math.hypot(vx[i],vy[i]);if(velocity>5){vx[i]=vx[i]/velocity*5;vy[i]=vy[i]/velocity*5}x[i]+=vx[i];y[i]+=vy[i];const distance=Math.hypot(x[i]-tx,y[i]-ty);minDistance[i]=Math.min(minDistance[i],distance);bestDistance=Math.min(bestDistance,distance);if(distance<34){flags[i]=2;completion[i]=lifeFrame;success++;totalSuccess++}else if(x[i]<-8||x[i]>width+8||y[i]<90||y[i]>height+10||collide(x[i],y[i]))flags[i]=1}lifeFrame++;if(lifeFrame>=state.lifespan)evolve()}
  function calculateFitness(){for(let i=0;i<state.population;i++){let score=1/(minDistance[i]+8);score*=score*10000;if(flags[i]===2)score+=3+(state.lifespan-completion[i])/state.lifespan*3;if(flags[i]===1)score*=.22;fitness[i]=score}}
  function tournament(){let best=Math.floor(Math.random()*state.population);for(let k=0;k<4;k++){const candidate=Math.floor(Math.random()*state.population);if(fitness[candidate]>fitness[best])best=candidate}return best}
  function copyGenome(from,to,arrayFrom,arrayTo){const start=geneIndex(from,0),dest=geneIndex(to,0),length=state.lifespan*2;arrayTo.set(arrayFrom.subarray(start,start+length),dest)}
  function evolve(){calculateFitness();const ranked=Array.from({length:state.population},(_,i)=>i).sort((a,b)=>fitness[b]-fitness[a]),eliteCount=Math.round(state.population*state.elite);for(let i=0;i<state.population;i++){if(i<eliteCount){copyGenome(ranked[i],i,dna,nextDna);continue}const a=tournament(),b=tournament(),point=Math.floor(Math.random()*state.lifespan);for(let f=0;f<state.lifespan;f++){const source=f<point?a:b,src=geneIndex(source,f),dest=geneIndex(i,f);nextDna[dest]=dna[src];nextDna[dest+1]=dna[src+1];if(Math.random()<state.mutation)randomGene(nextDna,i,f)}}[dna,nextDna]=[nextDna,dna];generation++;resetRockets();updateMetrics()}
  function update(){for(let s=0;s<state.speed;s++)simulateStep()}
  function render(){ctx.fillStyle='#12191b';ctx.fillRect(0,0,width,height);const tx=targetX*width,ty=targetY*height;ctx.beginPath();ctx.moveTo(tx,ty+18);ctx.lineTo(width*.5,height-42);ctx.setLineDash([2,10]);ctx.lineWidth=.6;ctx.strokeStyle='rgba(117,217,229,.16)';ctx.stroke();ctx.setLineDash([]);for(const o of obstacles){ctx.fillStyle='rgba(237,245,244,.88)';ctx.fillRect(o.x*width,o.y*height,o.w*width,Math.max(5,o.h*height));ctx.fillStyle='rgba(18,25,27,.3)';for(let t=o.x*width+8;t<(o.x+o.w)*width;t+=15)ctx.fillRect(t,o.y*height,1,o.h*height)}ctx.beginPath();ctx.arc(tx,ty,12,0,Math.PI*2);ctx.fillStyle='#75d9e5';ctx.fill();ctx.beginPath();ctx.arc(tx,ty,23,0,Math.PI*2);ctx.lineWidth=1;ctx.strokeStyle='rgba(117,217,229,.35)';ctx.stroke();for(let i=0;i<state.population;i++){const angle=Math.atan2(vy[i],vx[i])+Math.PI/2,size=width<600?3.2:4.2;ctx.save();ctx.translate(x[i],y[i]);ctx.rotate(angle);ctx.beginPath();ctx.moveTo(0,-size*2);ctx.lineTo(size,size*1.5);ctx.lineTo(0,size*.8);ctx.lineTo(-size,size*1.5);ctx.closePath();ctx.fillStyle=flags[i]===2?'#f3c35c':flags[i]===1?'rgba(238,119,104,.24)':'rgba(237,245,244,.72)';ctx.fill();ctx.restore()}}
  function updateMetrics(){document.getElementById('generation').textContent=generation;document.getElementById('success').textContent=totalSuccess;document.getElementById('distance').textContent=Number.isFinite(bestDistance)?`${Math.round(bestDistance)} px`:'--';document.getElementById('life').textContent=`${lifeFrame} / ${state.lifespan}`;document.getElementById('status').textContent=`第 ${generation} 代飞行中`}
  let metric=0;function frame(){if(!state.paused)update();render();if(metric++%8===0)updateMetrics();requestAnimationFrame(frame)}
  for(const[key,input]of Object.entries(controls)){syncRange(key);input.addEventListener('input',()=>{const raw=+input.value;state[key]=key==='mutation'||key==='elite'?raw/100:raw;syncRange(key)});if(key==='population'||key==='lifespan')input.addEventListener('change',restart)}
  document.getElementById('tools').addEventListener('click',event=>{const tool=event.target.closest('button[data-tool]'),action=event.target.closest('button[data-action]');if(tool){state.tool=tool.dataset.tool;document.querySelectorAll('#tools button[data-tool]').forEach(b=>b.setAttribute('aria-pressed',String(b===tool)))}else if(action){if(action.dataset.action==='preset'){targetX=.5;targetY=.16;defaultObstacles()}else obstacles=[];restart()}});
  canvas.addEventListener('pointerdown',event=>{const rect=canvas.getBoundingClientRect(),nx=(event.clientX-rect.left)/rect.width,ny=(event.clientY-rect.top)/rect.height;if(state.tool==='target'){targetX=Math.max(.04,Math.min(.96,nx));targetY=Math.max(.12,Math.min(.84,ny))}else{obstacles.push({x:Math.max(0,nx-.07),y:Math.max(.12,ny-.012),w:.14,h:.024});if(obstacles.length>9)obstacles.shift()}restart()});
  document.getElementById('restart').addEventListener('click',restart);document.getElementById('pause').addEventListener('click',()=>{state.paused=!state.paused;document.getElementById('pause-icon').textContent=state.paused?'▶':'Ⅱ';document.getElementById('pause-label').textContent=state.paused?'继续':'暂停'});new ResizeObserver(resize).observe(canvas);resize();defaultObstacles();restart();requestAnimationFrame(frame);
})();
