(() => {
  'use strict';
  const SAMPLES=256,TAU=Math.PI*2,canvas=document.getElementById('canvas'),ctx=canvas.getContext('2d',{alpha:false});
  const state={terms:72,speed:1,scale:1,circles:true,spectrum:true,paused:false,shape:'heart',drawing:false};
  let width=1,height=1,dpr=1,coefficients=[],time=0,trace=[],raw=[];
  const controls={terms:document.getElementById('terms'),speed:document.getElementById('speed'),scale:document.getElementById('scale')},outputs={terms:document.getElementById('terms-value'),speed:document.getElementById('speed-value'),scale:document.getElementById('scale-value')};
  const format={terms:v=>Math.round(v),speed:v=>`${Number(v).toFixed(1)}×`,scale:v=>Number(v).toFixed(2)};
  function syncRange(key){const input=controls[key],min=+input.min,max=+input.max;input.style.setProperty('--progress',`${(+input.value-min)/(max-min)*100}%`);outputs[key].textContent=format[key](input.value)}
  function shapePoints(name){const points=[];if(name==='star'){const vertices=[];for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,r=i%2?0.42:1;vertices.push({x:Math.cos(a)*r,y:Math.sin(a)*r})}for(let i=0;i<SAMPLES;i++){const p=i/SAMPLES*10,j=Math.floor(p),u=p-j,a=vertices[j%10],b=vertices[(j+1)%10];points.push({x:a.x+(b.x-a.x)*u,y:a.y+(b.y-a.y)*u})}}else for(let i=0;i<SAMPLES;i++){const t=i/SAMPLES*TAU;if(name==='heart')points.push({x:Math.pow(Math.sin(t),3),y:-(13*Math.cos(t)-5*Math.cos(2*t)-2*Math.cos(3*t)-Math.cos(4*t))/16});else if(name==='infinity')points.push({x:Math.sin(t),y:Math.sin(t)*Math.cos(t)*1.25});else{const r=Math.cos(5*t);points.push({x:r*Math.cos(t),y:r*Math.sin(t)})}}return points}
  function dft(points){const result=[];for(let k=0;k<SAMPLES;k++){let re=0,im=0;for(let n=0;n<SAMPLES;n++){const angle=-TAU*k*n/SAMPLES,c=Math.cos(angle),s=Math.sin(angle);re+=points[n].x*c-points[n].y*s;im+=points[n].x*s+points[n].y*c}re/=SAMPLES;im/=SAMPLES;result.push({re,im,freq:k<=SAMPLES/2?k:k-SAMPLES,amp:Math.hypot(re,im),phase:Math.atan2(im,re)})}return result.sort((a,b)=>b.amp-a.amp)}
  function loadShape(name,points=null){state.shape=name;coefficients=dft(points||shapePoints(name));time=0;trace=[];state.drawing=false;state.paused=false;const labels={heart:'心形轮廓',star:'星形轮廓',infinity:'无穷符号',rose:'玫瑰曲线',draw:'自定义轮廓'};document.getElementById('status').textContent=labels[name];document.getElementById('frequency').textContent=`DOMINANT FREQ ${coefficients.find(c=>c.freq!==0)?.freq||0}`}
  function resize(){const rect=canvas.getBoundingClientRect();width=Math.max(1,rect.width);height=Math.max(1,rect.height);dpr=Math.min(2,window.devicePixelRatio||1);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)}
  function resample(points){let lengths=[0],total=0;for(let i=1;i<points.length;i++){total+=Math.hypot(points[i].x-points[i-1].x,points[i].y-points[i-1].y);lengths.push(total)}total+=Math.hypot(points[0].x-points[points.length-1].x,points[0].y-points[points.length-1].y);const result=[];for(let s=0;s<SAMPLES;s++){const target=s/SAMPLES*total;let i=1;while(i<lengths.length&&lengths[i]<target)i++;if(i>=points.length){const u=(target-lengths[lengths.length-1])/(total-lengths[lengths.length-1]||1),a=points[points.length-1],b=points[0];result.push({x:a.x+(b.x-a.x)*u,y:a.y+(b.y-a.y)*u})}else{const u=(target-lengths[i-1])/(lengths[i]-lengths[i-1]||1),a=points[i-1],b=points[i];result.push({x:a.x+(b.x-a.x)*u,y:a.y+(b.y-a.y)*u})}}return result}
  function endpoint(draw=true){let x=width*.5,y=height*.52;const baseScale=Math.min(width,height)*.29*state.scale,limit=Math.min(state.terms,coefficients.length);for(let i=0;i<limit;i++){const c=coefficients[i],oldX=x,oldY=y,angle=c.freq*time+c.phase,r=c.amp*baseScale;x+=Math.cos(angle)*r;y+=Math.sin(angle)*r;if(draw&&state.circles){ctx.beginPath();ctx.arc(oldX,oldY,r,0,TAU);ctx.lineWidth=.6;ctx.strokeStyle='rgba(117,217,229,.20)';ctx.stroke();ctx.beginPath();ctx.moveTo(oldX,oldY);ctx.lineTo(x,y);ctx.lineWidth=.8;ctx.strokeStyle='rgba(237,245,244,.48)';ctx.stroke();ctx.beginPath();ctx.arc(x,y,1.7,0,TAU);ctx.fillStyle=i%8===0?'#f3c35c':'rgba(237,245,244,.72)';ctx.fill()}}return{x,y}}
  function drawSpectrum(){if(!state.spectrum)return;const baseY=height-36,maxAmp=coefficients[0]?.amp||1,count=Math.min(90,coefficients.length),barW=Math.max(1,(width-70)/count);ctx.beginPath();ctx.moveTo(35,baseY);ctx.lineTo(width-35,baseY);ctx.strokeStyle='rgba(255,255,255,.12)';ctx.stroke();for(let i=0;i<count;i++){const h=coefficients[i].amp/maxAmp*24;ctx.fillStyle=i<state.terms?'rgba(117,217,229,.58)':'rgba(237,245,244,.12)';ctx.fillRect(35+i*barW,baseY-h,Math.max(1,barW-1),h)}}
  function update(){if(state.drawing||state.paused)return;time+=TAU/SAMPLES*state.speed;if(time>=TAU){time%=TAU;trace=[]}const p=endpoint(false);trace.push(p);if(trace.length>SAMPLES*1.2)trace.shift()}
  function render(){ctx.fillStyle='#12191b';ctx.fillRect(0,0,width,height);if(state.drawing){if(raw.length>1){ctx.beginPath();ctx.moveTo(raw[0].sx,raw[0].sy);for(let i=1;i<raw.length;i++)ctx.lineTo(raw[i].sx,raw[i].sy);ctx.lineWidth=2;ctx.strokeStyle='#f3c35c';ctx.stroke()}return}endpoint(true);if(trace.length>1){ctx.beginPath();ctx.moveTo(trace[0].x,trace[0].y);for(let i=1;i<trace.length;i++)ctx.lineTo(trace[i].x,trace[i].y);ctx.lineWidth=2.2;ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='#f3c35c';ctx.stroke()}drawSpectrum();document.getElementById('trace-count').textContent=trace.length}
  function frame(){update();render();requestAnimationFrame(frame)}
  for(const[key,input]of Object.entries(controls)){syncRange(key);input.addEventListener('input',()=>{state[key]=+input.value;syncRange(key);if(key==='terms'){trace=[];document.getElementById('metric-terms').textContent=state.terms}})}document.getElementById('circles').addEventListener('change',e=>state.circles=e.target.checked);document.getElementById('spectrum').addEventListener('change',e=>state.spectrum=e.target.checked);
  document.getElementById('shapes').addEventListener('click',event=>{const button=event.target.closest('button[data-shape]');if(!button)return;document.querySelectorAll('#shapes button[data-shape]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));if(button.dataset.shape==='draw'){state.drawing=true;state.paused=true;raw=[];trace=[];document.getElementById('status').textContent='自定义轮廓采样'}else loadShape(button.dataset.shape)});
  function canvasPoint(event){const rect=canvas.getBoundingClientRect(),sx=event.clientX-rect.left,sy=event.clientY-rect.top,scale=Math.min(width,height)*.29*state.scale;return{sx,sy,x:(sx-width*.5)/scale,y:(sy-height*.52)/scale}}
  canvas.addEventListener('pointerdown',event=>{if(!state.drawing)return;raw=[canvasPoint(event)];canvas.setPointerCapture(event.pointerId)});canvas.addEventListener('pointermove',event=>{if(state.drawing&&canvas.hasPointerCapture(event.pointerId))raw.push(canvasPoint(event))});canvas.addEventListener('pointerup',event=>{if(!state.drawing)return;if(canvas.hasPointerCapture(event.pointerId))canvas.releasePointerCapture(event.pointerId);if(raw.length>8)loadShape('draw',resample(raw));else raw=[]});
  document.getElementById('clear-trace').addEventListener('click',()=>trace=[]);document.getElementById('restart').addEventListener('click',()=>{time=0;trace=[]});document.getElementById('pause').addEventListener('click',()=>{state.paused=!state.paused;document.getElementById('pause-icon').textContent=state.paused?'▶':'Ⅱ';document.getElementById('pause-label').textContent=state.paused?'继续':'暂停'});new ResizeObserver(resize).observe(canvas);resize();loadShape('heart');requestAnimationFrame(frame);
})();
