(() => {
  'use strict';
  const N=1,E=2,S=4,W=8,DIRS=[[0,-1,N,S],[1,0,E,W],[0,1,S,N],[-1,0,W,E]],canvas=document.getElementById('canvas'),ctx=canvas.getContext('2d',{alpha:false});
  const state={columns:38,speed:4,algorithm:'backtracker',autoSolve:true,loop:false,paused:false,phase:'generating'};
  let width=1,height=1,dpr=1,cols=1,rows=1,cw=1,ch=1,walls,visited,solveVisited,parent,queue,head=0,tail=0,stack=[],frontier=[],kruskalEdges=[],dsuParent,dsuRank,carved=0,searched=0,path=[],loopDelay=0,current=0;
  const controls={columns:document.getElementById('columns'),speed:document.getElementById('speed')},outputs={columns:document.getElementById('columns-value'),speed:document.getElementById('speed-value')};
  function syncRange(key){const input=controls[key],min=+input.min,max=+input.max;input.style.setProperty('--progress',`${(+input.value-min)/(max-min)*100}%`);outputs[key].textContent=Math.round(+input.value)}
  function idx(c,r){return r*cols+c}function pos(i){return{i,c:i%cols,r:Math.floor(i/cols)}}
  function neighbors(i,onlyUnvisited=false){const p=pos(i),out=[];for(const[dc,dr,bit,opp]of DIRS){const c=p.c+dc,r=p.r+dr;if(c<0||c>=cols||r<0||r>=rows)continue;const ni=idx(c,r);if(!onlyUnvisited||!visited[ni])out.push({from:i,to:ni,bit,opp})}return out}
  function carve(edge){walls[edge.from]&=~edge.bit;walls[edge.to]&=~edge.opp;visited[edge.from]=1;visited[edge.to]=1;carved++}
  function resize(){const rect=canvas.getBoundingClientRect();width=Math.max(1,rect.width);height=Math.max(1,rect.height);dpr=Math.min(2,window.devicePixelRatio||1);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);build()}
  function build(){cols=state.columns;rows=Math.max(10,Math.round(cols*height/width));cw=width/cols;ch=height/rows;const size=cols*rows;walls=new Uint8Array(size);walls.fill(15);visited=new Uint8Array(size);solveVisited=new Uint8Array(size);parent=new Int32Array(size);parent.fill(-1);queue=new Int32Array(size);dsuParent=new Int32Array(size);dsuRank=new Uint8Array(size);for(let i=0;i<size;i++)dsuParent[i]=i;stack=[];frontier=[];kruskalEdges=[];path=[];head=tail=carved=searched=0;current=0;state.phase='generating';loopDelay=0;if(state.algorithm==='backtracker'){visited[0]=1;stack.push(0)}else if(state.algorithm==='prim'){visited[0]=1;frontier.push(...neighbors(0,false))}else{for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){const i=idx(c,r);if(c<cols-1)kruskalEdges.push({from:i,to:i+1,bit:E,opp:W});if(r<rows-1)kruskalEdges.push({from:i,to:i+cols,bit:S,opp:N})}for(let i=kruskalEdges.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[kruskalEdges[i],kruskalEdges[j]]=[kruskalEdges[j],kruskalEdges[i]]}}document.getElementById('size-label').textContent=`${cols} × ${rows}`;updateMetrics()}
  function find(a){while(dsuParent[a]!==a){dsuParent[a]=dsuParent[dsuParent[a]];a=dsuParent[a]}return a}function union(a,b){a=find(a);b=find(b);if(a===b)return false;if(dsuRank[a]<dsuRank[b])[a,b]=[b,a];dsuParent[b]=a;if(dsuRank[a]===dsuRank[b])dsuRank[a]++;return true}
  function generationStep(){if(state.algorithm==='backtracker'){if(!stack.length)return finishGeneration();current=stack[stack.length-1];const choices=neighbors(current,true);if(choices.length){const edge=choices[Math.floor(Math.random()*choices.length)];carve(edge);visited[edge.to]=1;stack.push(edge.to);current=edge.to}else stack.pop()}else if(state.algorithm==='prim'){if(!frontier.length)return finishGeneration();const pick=Math.floor(Math.random()*frontier.length),edge=frontier[pick];frontier[pick]=frontier[frontier.length-1];frontier.pop();if(!visited[edge.to]){carve(edge);visited[edge.to]=1;current=edge.to;frontier.push(...neighbors(edge.to,false).filter(e=>!visited[e.to]))}}else{while(kruskalEdges.length){const edge=kruskalEdges.pop();if(union(edge.from,edge.to)){carve(edge);current=edge.to;break}}if(!kruskalEdges.length)finishGeneration()}}
  function finishGeneration(){visited.fill(1);if(state.autoSolve)startSolve();else{state.phase='complete';updateMetrics()}}
  function startSolve(){state.phase='solving';solveVisited.fill(0);parent.fill(-1);head=0;tail=0;queue[tail++]=0;solveVisited[0]=1;searched=0;path=[]}
  function solveStep(){if(head>=tail){state.phase='blocked';return}const node=queue[head++];current=node;searched++;if(node===walls.length-1){let p=node;while(p>=0){path.push(p);p=parent[p]}path.reverse();state.phase='solved';loopDelay=0;updateMetrics();return}const p=pos(node);for(const[dc,dr,bit]of DIRS){if(walls[node]&bit)continue;const c=p.c+dc,r=p.r+dr;if(c<0||c>=cols||r<0||r>=rows)continue;const ni=idx(c,r);if(!solveVisited[ni]){solveVisited[ni]=1;parent[ni]=node;queue[tail++]=ni}}}
  function update(){if(state.paused)return;if(state.phase==='generating'){for(let i=0;i<state.speed;i++){if(state.phase!=='generating')break;generationStep()}}else if(state.phase==='solving'){for(let i=0;i<state.speed*2;i++){if(state.phase!=='solving')break;solveStep()}}else if(state.phase==='solved'&&state.loop&&++loopDelay>110)build()}
  function render(){ctx.fillStyle='#12191b';ctx.fillRect(0,0,width,height);for(let i=0;i<walls.length;i++){const p=pos(i),x=p.c*cw,y=p.r*ch;if(state.phase==='generating'&&visited[i]){ctx.fillStyle=i===current?'rgba(117,217,229,.58)':'rgba(117,217,229,.10)';ctx.fillRect(x+1,y+1,cw-2,ch-2)}else if(solveVisited[i]){ctx.fillStyle=i===current?'rgba(238,119,104,.48)':'rgba(238,119,104,.13)';ctx.fillRect(x+1,y+1,cw-2,ch-2)}}if(path.length){ctx.beginPath();const first=pos(path[0]);ctx.moveTo((first.c+.5)*cw,(first.r+.5)*ch);for(let i=1;i<path.length;i++){const p=pos(path[i]);ctx.lineTo((p.c+.5)*cw,(p.r+.5)*ch)}ctx.lineCap='round';ctx.lineJoin='round';ctx.lineWidth=Math.max(2,Math.min(cw,ch)*.32);ctx.strokeStyle='#f3c35c';ctx.stroke()}ctx.beginPath();for(let i=0;i<walls.length;i++){const p=pos(i),x=p.c*cw,y=p.r*ch,w=walls[i];if(w&N){ctx.moveTo(x,y);ctx.lineTo(x+cw,y)}if(w&W){ctx.moveTo(x,y);ctx.lineTo(x,y+ch)}if(p.c===cols-1&&(w&E)){ctx.moveTo(x+cw,y);ctx.lineTo(x+cw,y+ch)}if(p.r===rows-1&&(w&S)){ctx.moveTo(x,y+ch);ctx.lineTo(x+cw,y+ch)}}ctx.lineWidth=Math.max(.7,Math.min(1.5,Math.min(cw,ch)*.12));ctx.strokeStyle='rgba(237,245,244,.86)';ctx.stroke();drawPoint(0,'#75d9e5');drawPoint(walls.length-1,'#f3c35c')}
  function drawPoint(i,color){const p=pos(i);ctx.beginPath();ctx.arc((p.c+.5)*cw,(p.r+.5)*ch,Math.max(2.5,Math.min(cw,ch)*.24),0,Math.PI*2);ctx.fillStyle=color;ctx.fill()}
  function updateMetrics(){const labels={generating:'正在生成迷宫',solving:'正在搜索出口',solved:'路径已找到',complete:'迷宫生成完成',blocked:'没有可达路径'};document.getElementById('status').textContent=labels[state.phase];document.getElementById('carved').textContent=carved;document.getElementById('searched').textContent=searched;document.getElementById('path-length').textContent=path.length?`${path.length} 格`:'--'}
  let metric=0;function frame(){update();render();if(metric++%10===0)updateMetrics();requestAnimationFrame(frame)}
  for(const[key,input]of Object.entries(controls)){syncRange(key);input.addEventListener('input',()=>{state[key]=+input.value;syncRange(key)});if(key==='columns')input.addEventListener('change',build)}document.getElementById('auto-solve').addEventListener('change',e=>state.autoSolve=e.target.checked);document.getElementById('loop').addEventListener('change',e=>state.loop=e.target.checked);
  document.getElementById('algorithms').addEventListener('click',event=>{const button=event.target.closest('button[data-algorithm]');if(!button)return;state.algorithm=button.dataset.algorithm;document.querySelectorAll('#algorithms button[data-algorithm]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));const labels={backtracker:'RECURSIVE BACKTRACKER',prim:'RANDOMIZED PRIM',kruskal:'RANDOMIZED KRUSKAL'};document.getElementById('algorithm-label').textContent=labels[state.algorithm];build()});
  document.getElementById('single-step').addEventListener('click',()=>{if(state.phase==='generating')generationStep();else if(state.phase==='solving')solveStep();render();updateMetrics()});document.getElementById('regenerate').addEventListener('click',build);document.getElementById('pause').addEventListener('click',()=>{state.paused=!state.paused;document.getElementById('pause-icon').textContent=state.paused?'▶':'Ⅱ';document.getElementById('pause-label').textContent=state.paused?'继续':'暂停'});new ResizeObserver(resize).observe(canvas);resize();requestAnimationFrame(frame);
})();
