(() => {
  'use strict';
  const canvas=document.getElementById('canvas'),ctx=canvas.getContext('2d',{alpha:false});
  const state={columns:48,density:.22,heuristic:1,steps:8,diagonal:true,tool:'wall',mode:'running'};
  let width=1,height=1,dpr=1,cols=1,rows=1,cellW=1,cellH=1,walls,marks,gScore,fScore,parent,heap=[],start=0,goal=1,visitedCount=0,pathLength=0,drawing=false;
  const controls={columns:document.getElementById('grid-size'),density:document.getElementById('density'),heuristic:document.getElementById('heuristic'),steps:document.getElementById('speed')};
  const outputs={columns:document.getElementById('grid-size-value'),density:document.getElementById('density-value'),heuristic:document.getElementById('heuristic-value'),steps:document.getElementById('speed-value')};
  const format={columns:v=>Math.round(v),density:v=>`${Math.round(v)}%`,heuristic:v=>Number(v).toFixed(1),steps:v=>Math.round(v)};
  function syncRange(key){const input=controls[key],min=+input.min,max=+input.max;input.style.setProperty('--progress',`${(+input.value-min)/(max-min)*100}%`);outputs[key].textContent=format[key](input.value)}
  function index(col,row){return row*cols+col}function coord(i){return{col:i%cols,row:Math.floor(i/cols)}}
  function estimate(a,b){const aa=coord(a),bb=coord(b),dx=Math.abs(aa.col-bb.col),dy=Math.abs(aa.row-bb.row);return state.diagonal?Math.max(dx,dy)+(Math.SQRT2-1)*Math.min(dx,dy):dx+dy}
  function heapPush(node){heap.push(node);let i=heap.length-1;while(i>0){const p=(i-1)>>1;if(fScore[heap[p]]<=fScore[heap[i]])break;[heap[p],heap[i]]=[heap[i],heap[p]];i=p}}
  function heapPop(){if(!heap.length)return-1;const root=heap[0],last=heap.pop();if(heap.length){heap[0]=last;let i=0;for(;;){let l=i*2+1,r=l+1,s=i;if(l<heap.length&&fScore[heap[l]]<fScore[heap[s]])s=l;if(r<heap.length&&fScore[heap[r]]<fScore[heap[s]])s=r;if(s===i)break;[heap[i],heap[s]]=[heap[s],heap[i]];i=s}}return root}
  function resize(){const rect=canvas.getBoundingClientRect();width=Math.max(1,rect.width);height=Math.max(1,rect.height);dpr=Math.min(2,window.devicePixelRatio||1);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);buildGrid(true)}
  function buildGrid(random=true){cols=state.columns;rows=Math.max(14,Math.round(cols*height/width));cellW=width/cols;cellH=height/rows;const size=cols*rows;walls=new Uint8Array(size);marks=new Uint8Array(size);gScore=new Float32Array(size);fScore=new Float32Array(size);parent=new Int32Array(size);start=index(Math.max(2,Math.round(cols*.08)),Math.round(rows*.56));goal=index(Math.min(cols-3,Math.round(cols*.91)),Math.round(rows*.43));if(random)for(let i=0;i<size;i++)walls[i]=Math.random()<state.density?1:0;clearEndpointZones();resetSearch();document.getElementById('grid-label').textContent=`${cols} × ${rows}`}
  function clearEndpointZones(){for(const point of[start,goal]){const p=coord(point);for(let y=-2;y<=2;y++)for(let x=-2;x<=2;x++){const c=p.col+x,r=p.row+y;if(c>=0&&c<cols&&r>=0&&r<rows)walls[index(c,r)]=0}}}
  function resetSearch(){marks.fill(0);gScore.fill(Infinity);fScore.fill(Infinity);parent.fill(-1);heap=[];visitedCount=0;pathLength=0;gScore[start]=0;fScore[start]=estimate(start,goal)*state.heuristic;heapPush(start);marks[start]=1;state.mode='running';updateStatus()}
  function neighbors(current){const p=coord(current),list=[],dirs=state.diagonal?[[1,0,1],[-1,0,1],[0,1,1],[0,-1,1],[1,1,Math.SQRT2],[-1,1,Math.SQRT2],[1,-1,Math.SQRT2],[-1,-1,Math.SQRT2]]:[[1,0,1],[-1,0,1],[0,1,1],[0,-1,1]];for(const[dx,dy,cost]of dirs){const c=p.col+dx,r=p.row+dy;if(c<0||c>=cols||r<0||r>=rows)continue;const ni=index(c,r);if(walls[ni])continue;if(dx&&dy&&(walls[index(p.col+dx,p.row)]||walls[index(p.col,p.row+dy)]))continue;list.push([ni,cost])}return list}
  function solveStep(){let current=heapPop();while(current>=0&&marks[current]===2)current=heapPop();if(current<0){state.mode='blocked';updateStatus();return false}if(current===goal){reconstruct();state.mode='solved';updateStatus();return false}marks[current]=2;visitedCount++;for(const[next,cost]of neighbors(current)){if(marks[next]===2)continue;const tentative=gScore[current]+cost;if(tentative<gScore[next]){parent[next]=current;gScore[next]=tentative;fScore[next]=tentative+estimate(next,goal)*state.heuristic;heapPush(next);marks[next]=1}}return true}
  function reconstruct(){let current=goal,count=0;while(current!==start&&current>=0){marks[current]=3;current=parent[current];count++}pathLength=count;marks[start]=4;marks[goal]=5}
  function update(){if(state.mode!=='running')return;for(let i=0;i<state.steps;i++)if(!solveStep())break}
  function updateStatus(){const labels={running:'正在搜索',paused:'已暂停',solved:'路径已找到',blocked:'无可达路径',editing:'地图已修改'};document.getElementById('status').textContent=labels[state.mode];document.getElementById('visited').textContent=visitedCount;document.getElementById('frontier').textContent=heap.length;document.getElementById('path-length').textContent=pathLength?`${pathLength} 格`:'--';const active=state.mode==='running';document.getElementById('run-icon').textContent=active?'Ⅱ':'▶';document.getElementById('run-label').textContent=active?'暂停':state.mode==='solved'||state.mode==='blocked'?'重新搜索':'继续'}
  function render(){ctx.fillStyle='#12191b';ctx.fillRect(0,0,width,height);for(let i=0;i<walls.length;i++){const c=i%cols,r=Math.floor(i/cols),x=c*cellW,y=r*cellH;if(walls[i]){ctx.fillStyle='#e7eeeb';ctx.fillRect(x+.6,y+.6,Math.max(1,cellW-1.2),Math.max(1,cellH-1.2))}else if(marks[i]){ctx.fillStyle=marks[i]===1?'rgba(117,217,229,.52)':marks[i]===2?'rgba(238,119,104,.25)':marks[i]===3?'#f3c35c':'transparent';ctx.fillRect(x+.7,y+.7,Math.max(1,cellW-1.4),Math.max(1,cellH-1.4))}}if(cellW>8){ctx.beginPath();for(let c=1;c<cols;c++){ctx.moveTo(c*cellW,0);ctx.lineTo(c*cellW,height)}for(let r=1;r<rows;r++){ctx.moveTo(0,r*cellH);ctx.lineTo(width,r*cellH)}ctx.lineWidth=.5;ctx.strokeStyle='rgba(255,255,255,.045)';ctx.stroke()}drawEndpoint(start,'#75d9e5','S');drawEndpoint(goal,'#f3c35c','G')}
  function drawEndpoint(i,color,label){const p=coord(i),x=(p.col+.5)*cellW,y=(p.row+.5)*cellH,r=Math.max(5,Math.min(cellW,cellH)*.36);ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();if(r>7){ctx.fillStyle='#12191b';ctx.font=`600 ${Math.max(8,r)}px sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(label,x,y+.5)}}
  let metricFrame=0;function frame(){update();render();if(metricFrame++%15===0)updateStatus();requestAnimationFrame(frame)}
  function cellFromEvent(event){const rect=canvas.getBoundingClientRect(),c=Math.floor((event.clientX-rect.left)/cellW),r=Math.floor((event.clientY-rect.top)/cellH);return c>=0&&c<cols&&r>=0&&r<rows?index(c,r):-1}
  function edit(event){const i=cellFromEvent(event);if(i<0)return;if(state.tool==='start'){if(i!==goal&&!walls[i])start=i;drawing=false}else if(state.tool==='goal'){if(i!==start&&!walls[i])goal=i;drawing=false}else if(i!==start&&i!==goal)walls[i]=state.tool==='wall'?1:0;resetSearch();state.mode='editing';updateStatus()}
  canvas.addEventListener('pointerdown',event=>{drawing=true;canvas.setPointerCapture(event.pointerId);edit(event)});canvas.addEventListener('pointermove',event=>{if(drawing&&(state.tool==='wall'||state.tool==='erase'))edit(event)});canvas.addEventListener('pointerup',event=>{drawing=false;if(canvas.hasPointerCapture(event.pointerId))canvas.releasePointerCapture(event.pointerId)});
  document.getElementById('tools').addEventListener('click',event=>{const button=event.target.closest('button[data-tool]');if(!button)return;state.tool=button.dataset.tool;document.querySelectorAll('#tools button').forEach(item=>item.setAttribute('aria-pressed',String(item===button)))});
  for(const[key,input]of Object.entries(controls)){syncRange(key);input.addEventListener('input',()=>{const raw=+input.value;state[key]=key==='density'?raw/100:raw;syncRange(key)});if(key==='columns'||key==='density')input.addEventListener('change',()=>buildGrid(true));if(key==='heuristic')input.addEventListener('change',resetSearch)}
  document.getElementById('diagonal').addEventListener('change',event=>{state.diagonal=event.target.checked;resetSearch()});document.getElementById('randomize').addEventListener('click',()=>buildGrid(true));document.getElementById('run').addEventListener('click',()=>{if(state.mode==='running')state.mode='paused';else if(state.mode==='solved'||state.mode==='blocked'||state.mode==='editing')resetSearch();else state.mode='running';updateStatus()});new ResizeObserver(resize).observe(canvas);resize();requestAnimationFrame(frame);
})();
