(() => {
  'use strict';
  const canvas=document.getElementById('canvas'),ctx=canvas.getContext('2d',{alpha:false}),el=id=>document.getElementById(id);
  const samples={max:[92,75,81,44,63,52,70,18,31],min:[8,19,14,35,27,42,26,61,48]};
  let heap=[],mode='max',width=1,height=1,dpr=1,swaps=0,speed=5;
  let timeline=[],timelineIndex=-1,active={},running=false,paused=false,lastAdvance=0;
  const input=el('node-value');
  const better=(a,b)=>mode==='max'?a>b:a<b;
  const valid=(parent,child)=>mode==='max'?parent>=child:parent<=child;
  function syncMetrics(){el('metric-count').textContent=heap.length;el('metric-height').textContent=heap.length?Math.floor(Math.log2(heap.length))+1:0;el('metric-swaps').textContent=swaps}
  function setPaused(v){paused=v;for(const id of['pause-icon','stage-pause-icon'])el(id).classList.toggle('play',paused);el('pause-label').textContent=paused?'继续':'暂停';el('stage-pause-label').textContent=paused?'继续':'暂停';el('live-dot').classList.toggle('paused',paused)}
  function record(steps,work,local,message,focus=[],code='',tone='',swap=null){steps.push({snapshot:work.slice(),swaps:local.value,message,focus,code,tone,swap})}
  function advance(){if(!running)return;timelineIndex+=1;if(timelineIndex>=timeline.length){running=false;active={};setPaused(false);el('status').textContent=`${mode==='max'?'最大':'最小'}堆性质已恢复`;el('step-label').textContent='DONE';return}active=timeline[timelineIndex];heap=active.snapshot.slice();swaps=active.swaps;el('status').textContent=active.message;el('operation-label').textContent=active.code;el('step-label').textContent=`${timelineIndex+1} / ${timeline.length}`;lastAdvance=performance.now();syncMetrics()}
  function play(steps){timeline=steps;timelineIndex=-1;running=true;setPaused(false);advance()}
  function value(){const v=Number(input.value);return Math.max(0,Math.min(99,Number.isFinite(v)?Math.round(v):0))}
  function enqueue(){if(heap.length>=15){el('status').textContent='最多演示 15 个元素';return}const work=heap.slice(),steps=[],local={value:swaps},target=value();work.push(target);let i=work.length-1;record(steps,work,local,`将 ${target} 追加到数组末尾`,[i],`heap.push(${target})`);while(i>0){const p=Math.floor((i-1)/2);record(steps,work,local,`比较子节点 ${work[i]} 与父节点 ${work[p]}`,[p,i],`parent(${i}) = ${p}`);if(valid(work[p],work[i])){record(steps,work,local,'堆序正确，停止上浮',[p,i],'parent 优先级更高');break}[work[p],work[i]]=[work[i],work[p]];local.value+=1;record(steps,work,local,`交换索引 ${i} 与 ${p}`,[p,i],'swap(child, parent)','swap',[p,i]);i=p}record(steps,work,local,'入队完成',[i],`元素停在索引 ${i}`);play(steps)}
  function extract(){const work=heap.slice(),steps=[],local={value:swaps};if(!work.length){record(steps,work,local,'优先队列为空',[],'heap.length == 0');play(steps);return}const top=work[0];record(steps,work,local,`读取堆顶 ${top}`,[0],'top = heap[0]','extract');if(work.length===1){work.pop();record(steps,work,local,`提取 ${top}，队列变空`,[],'heap.pop()','extract');play(steps);return}const last=work.pop();work[0]=last;record(steps,work,local,`末尾元素 ${last} 移到堆顶`,[0],'heap[0] = heap.pop()');let i=0;while(true){const left=i*2+1,right=left+1;if(left>=work.length)break;let child=left;if(right<work.length&&better(work[right],work[left]))child=right;record(steps,work,local,`选择优先级更高的孩子 ${work[child]}`,[i,child],`bestChild = ${child}`);if(valid(work[i],work[child])){record(steps,work,local,'堆序正确，停止下沉',[i,child],'parent 优先级更高');break}[work[i],work[child]]=[work[child],work[i]];local.value+=1;record(steps,work,local,`交换索引 ${i} 与 ${child}`,[i,child],'swap(parent, child)','swap',[i,child]);i=child}record(steps,work,local,`已提取 ${top}`,[i],`return ${top}`,'extract');play(steps)}
  function peek(){const steps=[],local={value:swaps};record(steps,heap,local,heap.length?`堆顶优先级为 ${heap[0]}`:'优先队列为空',heap.length?[0]:[],'peek = heap[0]');play(steps)}
  function heapify(values){const result=[];for(const v of values){result.push(v);let i=result.length-1;while(i>0){const p=Math.floor((i-1)/2);if(mode==='max'?result[p]>=result[i]:result[p]<=result[i])break;[result[p],result[i]]=[result[i],result[p]];i=p}}return result}
  function positions(){const map=[];const treeTop=width<760?118:130,arrayTop=Math.max(treeTop+170,height-118),treeBottom=arrayTop-45,maxDepth=Math.max(1,Math.floor(Math.log2(Math.max(1,heap.length))));for(let i=0;i<heap.length;i++){const depth=Math.floor(Math.log2(i+1)),first=2**depth-1,pos=i-first,slots=2**depth;map[i]={x:(pos+1)/(slots+1)*width,y:treeTop+depth*(treeBottom-treeTop)/maxDepth}}return{map,arrayTop}}
  function render(){ctx.fillStyle='#111816';ctx.fillRect(0,0,width,height);const{map,arrayTop}=positions(),radius=Math.max(14,Math.min(22,width/(Math.max(10,heap.length)*2.1)));for(let i=1;i<heap.length;i++){const p=Math.floor((i-1)/2),a=map[p],b=map[i],hot=active.swap&&(active.swap.includes(i)&&active.swap.includes(p));ctx.strokeStyle=hot?'#f1bd58':'#3b4a44';ctx.lineWidth=hot?2:1.2;ctx.beginPath();ctx.moveTo(a.x,a.y+radius*.7);ctx.lineTo(b.x,b.y-radius*.7);ctx.stroke()}for(let i=0;i<heap.length;i++){const p=map[i],hot=active.focus?.includes(i),extracting=active.tone==='extract'&&hot;ctx.beginPath();ctx.arc(p.x,p.y,radius,0,Math.PI*2);ctx.fillStyle=extracting?'#3b2421':hot?'#203b31':'#18221f';ctx.fill();ctx.strokeStyle=extracting?'#ef7968':hot?'#78d9b2':'#45534d';ctx.lineWidth=hot?2:1;ctx.stroke();ctx.fillStyle='#eff3eb';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`600 ${Math.max(11,radius*.68)}px ui-monospace,Consolas`;ctx.fillText(heap[i],p.x,p.y);ctx.fillStyle='#8b9993';ctx.font='8px ui-monospace,Consolas';ctx.fillText(i,p.x,p.y+radius+10)}if(heap.length){const cellW=Math.min(52,(width-36)/heap.length),total=cellW*heap.length,start=(width-total)/2;ctx.fillStyle='#8b9993';ctx.font='9px ui-monospace,Consolas';ctx.textAlign='left';ctx.fillText('ARRAY',start,arrayTop-13);for(let i=0;i<heap.length;i++){const x=start+i*cellW,hot=active.focus?.includes(i);ctx.fillStyle=hot?'#203b31':'#18221f';ctx.fillRect(x,arrayTop,cellW-2,34);ctx.strokeStyle=hot?'#78d9b2':'#3d4b45';ctx.strokeRect(x+.5,arrayTop+.5,cellW-3,33);ctx.fillStyle='#eff3eb';ctx.textAlign='center';ctx.font=`600 ${cellW<28?9:12}px ui-monospace,Consolas`;ctx.fillText(heap[i],x+(cellW-2)/2,arrayTop+17);ctx.fillStyle='#73827b';ctx.font='7px ui-monospace,Consolas';ctx.fillText(i,x+(cellW-2)/2,arrayTop+43)}}else{ctx.fillStyle='#718079';ctx.textAlign='center';ctx.font='12px ui-monospace,Consolas';ctx.fillText('EMPTY PRIORITY QUEUE',width/2,height/2)}}
  function resize(){const r=canvas.getBoundingClientRect();width=Math.max(1,r.width);height=Math.max(1,r.height);dpr=Math.min(2,devicePixelRatio||1);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)}
  function reset(values=samples[mode]){heap=values.slice();swaps=0;timeline=[];active={};running=false;setPaused(false);el('status').textContent=`${mode==='max'?'最大':'最小'}堆已就绪`;el('operation-label').textContent='parent(i) = ⌊(i−1)/2⌋';el('step-label').textContent='READY';syncMetrics()}
  function randomize(){const values=[];while(values.length<9){const v=5+Math.floor(Math.random()*90);if(!values.includes(v))values.push(v)}reset(heapify(values))}
  function toggle(){if(running){setPaused(!paused);lastAdvance=performance.now()}}function frame(now){if(running&&!paused&&now-lastAdvance>=1450-speed*115)advance();render();requestAnimationFrame(frame)}
  el('enqueue').onclick=enqueue;el('extract').onclick=extract;el('peek').onclick=peek;el('randomize').onclick=randomize;el('reset').onclick=()=>reset();el('stage-reset').onclick=()=>reset();el('heap-mode').onclick=e=>{const button=e.target.closest('[data-mode]');if(!button)return;mode=button.dataset.mode;document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));reset()};el('pause').onclick=toggle;el('stage-pause').onclick=toggle;el('step').onclick=()=>{if(running){setPaused(true);advance()}};input.addEventListener('keydown',e=>{if(e.key==='Enter')enqueue()});el('speed').addEventListener('input',e=>{speed=Number(e.target.value);el('speed-value').textContent=speed;e.target.style.setProperty('--progress',`${(speed-1)/9*100}%`)});el('speed').dispatchEvent(new Event('input'));new ResizeObserver(resize).observe(canvas);reset();resize();requestAnimationFrame(frame);
})();
