(() => {
  'use strict';
  const canvas=document.getElementById('canvas'),ctx=canvas.getContext('2d',{alpha:false}),el=id=>document.getElementById(id);
  const initial=[42,24,64,12,31,55,78];
  let root=null,nextId=1,width=1,height=1,dpr=1,rotations=0,comparisons=0;
  let timeline=[],timelineIndex=-1,active={},running=false,paused=false,speed=5,lastAdvance=0;
  const input=el('node-value');
  const heightOf=n=>n?n.height:0;
  const balance=n=>n?heightOf(n.left)-heightOf(n.right):0;
  const update=n=>{if(n)n.height=1+Math.max(heightOf(n.left),heightOf(n.right));return n};
  function makeNode(value){return{id:nextId++,value,left:null,right:null,height:1}}
  function clone(n){return n?{id:n.id,value:n.value,height:n.height,left:clone(n.left),right:clone(n.right)}:null}
  function rotateRight(y){const x=y.left,t=x.right;x.right=y;y.left=t;update(y);update(x);return x}
  function rotateLeft(x){const y=x.right,t=y.left;y.left=x;x.right=t;update(x);update(y);return y}
  function insertSilent(n,fresh){if(!n)return fresh;if(fresh.value<n.value)n.left=insertSilent(n.left,fresh);else if(fresh.value>n.value)n.right=insertSilent(n.right,fresh);else return n;update(n);const b=balance(n);if(b>1&&fresh.value<n.left.value)return rotateRight(n);if(b<-1&&fresh.value>n.right.value)return rotateLeft(n);if(b>1&&fresh.value>n.left.value){n.left=rotateLeft(n.left);return rotateRight(n)}if(b<-1&&fresh.value<n.right.value){n.right=rotateRight(n.right);return rotateLeft(n)}return n}
  function count(n=root){return n?1+count(n.left)+count(n.right):0}
  function maxBalance(n=root){return n?Math.max(Math.abs(balance(n)),maxBalance(n.left),maxBalance(n.right)):0}
  function syncMetrics(){el('metric-height').textContent=heightOf(root);el('metric-balance').textContent=maxBalance();el('metric-rotations').textContent=rotations}
  function setPaused(v){paused=v;for(const id of['pause-icon','stage-pause-icon'])el(id).classList.toggle('play',paused);el('pause-label').textContent=paused?'继续':'暂停';el('stage-pause-label').textContent=paused?'继续':'暂停';el('live-dot').classList.toggle('paused',paused)}
  function recordFactory(wrapper,steps,counters){return(message,focus=[],code='',tone='')=>steps.push({message,focus,code,tone,snapshot:clone(wrapper.root),rotations:counters.rotations,comparisons:counters.comparisons})}
  function advance(){if(!running)return;timelineIndex+=1;if(timelineIndex>=timeline.length){running=false;active={};setPaused(false);el('status').textContent='树处于平衡状态';el('step-label').textContent='DONE';return}active=timeline[timelineIndex];root=clone(active.snapshot);rotations=active.rotations;comparisons=active.comparisons;el('status').textContent=active.message;el('operation-label').textContent=active.code;el('step-label').textContent=`${timelineIndex+1} / ${timeline.length}`;lastAdvance=performance.now();syncMetrics()}
  function play(steps){timeline=steps;timelineIndex=-1;running=true;setPaused(false);advance()}
  function value(){const v=Number(input.value);return Math.max(0,Math.min(99,Number.isFinite(v)?Math.round(v):0))}
  function buildInsert(target){const wrapper={root:clone(root)},steps=[],counters={rotations,comparisons},record=recordFactory(wrapper,steps,counters),fresh=makeNode(target);let duplicate=false;
    function rec(parent,side){let n=parent[side];if(!n){parent[side]=fresh;record(`插入叶节点 ${target}`,[fresh.id],'在空位置创建节点');return}counters.comparisons+=1;record(`比较 ${target} 与 ${n.value}`,[n.id],target<n.value?'进入左子树':target>n.value?'进入右子树':'键值已存在');if(target===n.value){duplicate=true;return}rec(n,target<n.value?'left':'right');n=parent[side];update(n);const b=balance(n);if(Math.abs(b)<=1)return;record(`节点 ${n.value} 失衡，BF = ${b}`,[n.id],'检测到 |BF| > 1','warn');if(b>1){if(target>n.left.value){n.left=rotateLeft(n.left);counters.rotations+=1;record('先对左孩子执行左旋',[n.id,n.left.id],'LR：rotateLeft(left)')}parent[side]=rotateRight(n);counters.rotations+=1;record(`围绕 ${n.value} 执行右旋`,[parent[side].id,n.id],'rotateRight(node)','rotate')}else{if(target<n.right.value){n.right=rotateRight(n.right);counters.rotations+=1;record('先对右孩子执行右旋',[n.id,n.right.id],'RL：rotateRight(right)')}parent[side]=rotateLeft(n);counters.rotations+=1;record(`围绕 ${n.value} 执行左旋`,[parent[side].id,n.id],'rotateLeft(node)','rotate')}}
    rec(wrapper,'root');if(duplicate)record(`忽略重复键 ${target}`,[],'AVL 不保存重复键');else record('所有祖先高度与平衡因子已更新',[wrapper.root?.id].filter(Boolean),'平衡恢复');return steps}
  function buildSearch(target){const wrapper={root:clone(root)},steps=[],counters={rotations,comparisons},record=recordFactory(wrapper,steps,counters);let n=wrapper.root;while(n){counters.comparisons+=1;record(`比较 ${target} 与 ${n.value}`,[n.id],target===n.value?'键值相等':target<n.value?'进入左子树':'进入右子树');if(target===n.value){record(`找到键值 ${target}`,[n.id],'return node','success');return steps}n=target<n.value?n.left:n.right}record(`键值 ${target} 不在树中`,[],'current == null');return steps}
  function buildDelete(target){const wrapper={root:clone(root)},steps=[],counters={rotations,comparisons},record=recordFactory(wrapper,steps,counters);let found=false;
    function rebalance(parent,side){let n=parent[side];if(!n)return;update(n);const b=balance(n);if(Math.abs(b)<=1)return;record(`删除后节点 ${n.value} 失衡，BF = ${b}`,[n.id],'沿路径向上重新平衡','warn');if(b>1){if(balance(n.left)<0){n.left=rotateLeft(n.left);counters.rotations+=1;record('先对左孩子执行左旋',[n.id,n.left.id],'LR 修复')}parent[side]=rotateRight(n);counters.rotations+=1;record('执行右旋恢复平衡',[parent[side].id],'rotateRight(node)','rotate')}else{if(balance(n.right)>0){n.right=rotateRight(n.right);counters.rotations+=1;record('先对右孩子执行右旋',[n.id,n.right.id],'RL 修复')}parent[side]=rotateLeft(n);counters.rotations+=1;record('执行左旋恢复平衡',[parent[side].id],'rotateLeft(node)','rotate')}}
    function rec(parent,side,key){let n=parent[side];if(!n)return;counters.comparisons+=1;record(`比较 ${key} 与 ${n.value}`,[n.id],key<n.value?'进入左子树':key>n.value?'进入右子树':'定位删除节点');if(key<n.value)rec(n,'left',key);else if(key>n.value)rec(n,'right',key);else{found=true;if(!n.left||!n.right){parent[side]=n.left||n.right;record(n.left||n.right?'用唯一孩子替代目标':'移除叶节点',parent[side]?[parent[side].id]:[],'更新父节点引用','delete')}else{let successor=n.right;while(successor.left){successor=successor.left;counters.comparisons+=1;record(`寻找后继：${successor.value}`,[successor.id],'successor = successor.left')}const sv=successor.value;n.value=sv;record(`后继 ${sv} 替换目标`,[n.id,successor.id],'node.value = successor.value');rec(n,'right',sv)}}rebalance(parent,side)}
    rec(wrapper,'root',target);if(!found)record(`键值 ${target} 不在树中`,[],'无需删除');else record('删除完成，AVL 性质恢复',[wrapper.root?.id].filter(Boolean),'所有 |BF| ≤ 1');return steps}
  function positions(){const ordered=[];function walk(n,depth,parent){if(!n)return;walk(n.left,depth+1,n);ordered.push({node:n,depth,parent});walk(n.right,depth+1,n)}walk(root,0,null);const map=new Map(),top=width<760?118:135,bottom=92,maxDepth=Math.max(1,...ordered.map(x=>x.depth)),usable=Math.max(100,height-top-bottom);ordered.forEach((item,i)=>map.set(item.node.id,{x:ordered.length===1?width/2:36+i*(width-72)/(ordered.length-1),y:top+item.depth*usable/maxDepth}));return{ordered,map}}
  function render(){ctx.fillStyle='#111816';ctx.fillRect(0,0,width,height);const{ordered,map}=positions(),r=Math.max(15,Math.min(23,width/(Math.max(10,ordered.length)*2.2)));for(const item of ordered){if(!item.parent)continue;const a=map.get(item.parent.id),b=map.get(item.node.id);ctx.strokeStyle='#3b4a44';ctx.lineWidth=1.2;ctx.beginPath();ctx.moveTo(a.x,a.y+r*.65);ctx.lineTo(b.x,b.y-r*.65);ctx.stroke()}for(const item of ordered){const p=map.get(item.node.id),hot=active.focus?.includes(item.node.id),bf=balance(item.node),bad=Math.abs(bf)>1;ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.fillStyle=bad?'#3b3020':hot?'#203b31':'#18221f';ctx.fill();ctx.strokeStyle=bad?'#f1bd58':hot?'#78d9b2':'#45534d';ctx.lineWidth=bad||hot?2:1;ctx.stroke();ctx.fillStyle='#eff3eb';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`600 ${Math.max(11,r*.68)}px ui-monospace,Consolas`;ctx.fillText(item.node.value,p.x,p.y-2);ctx.fillStyle=bad?'#f1bd58':'#8c9a94';ctx.font='8px ui-monospace,Consolas';ctx.fillText(`BF ${bf}`,p.x,p.y+r+11)}if(!root){ctx.fillStyle='#718079';ctx.textAlign='center';ctx.font='12px ui-monospace,Consolas';ctx.fillText('EMPTY AVL TREE',width/2,height/2)}}
  function resize(){const r=canvas.getBoundingClientRect();width=Math.max(1,r.width);height=Math.max(1,r.height);dpr=Math.min(2,devicePixelRatio||1);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)}
  function reset(values=initial){root=null;nextId=1;values.forEach(v=>{root=insertSilent(root,makeNode(v))});rotations=0;comparisons=0;timeline=[];active={};running=false;setPaused(false);el('status').textContent='树处于平衡状态';el('operation-label').textContent='每个节点显示 BF = 左高 − 右高';el('step-label').textContent='READY';syncMetrics()}
  function demo(type){const cases={ll:[30,20,10],rr:[10,20,30],lr:[30,10,20],rl:[10,30,20]},values=cases[type];reset(values.slice(0,2));input.value=values[2];play(buildInsert(values[2]))}
  function frame(now){if(running&&!paused&&now-lastAdvance>=1550-speed*120)advance();render();requestAnimationFrame(frame)}function toggle(){if(running){setPaused(!paused);lastAdvance=performance.now()}}
  el('insert').onclick=()=>{if(count()>=15){el('status').textContent='最多演示 15 个节点';return}play(buildInsert(value()))};el('find').onclick=()=>play(buildSearch(value()));el('remove').onclick=()=>play(buildDelete(value()));el('reset').onclick=()=>reset();el('stage-reset').onclick=()=>reset();document.querySelectorAll('[data-demo]').forEach(button=>button.onclick=()=>demo(button.dataset.demo));el('pause').onclick=toggle;el('stage-pause').onclick=toggle;el('step').onclick=()=>{if(running){setPaused(true);advance()}};input.addEventListener('keydown',e=>{if(e.key==='Enter')el('insert').click()});el('speed').addEventListener('input',e=>{speed=Number(e.target.value);el('speed-value').textContent=speed;e.target.style.setProperty('--progress',`${(speed-1)/9*100}%`)});el('speed').dispatchEvent(new Event('input'));new ResizeObserver(resize).observe(canvas);reset();resize();requestAnimationFrame(frame);
})();
