(() => {
  'use strict';
  const MAX=500,canvas=document.getElementById('canvas'),ctx=canvas.getContext('2d',{alpha:false}),field=document.createElement('canvas'),fieldCtx=field.getContext('2d');
  const state={count:180,maxSpeed:.18,inertia:.72,cognitive:1.35,social:1.55,fn:'rastrigin',paused:false};
  const px=new Float32Array(MAX),py=new Float32Array(MAX),vx=new Float32Array(MAX),vy=new Float32Array(MAX),bestX=new Float32Array(MAX),bestY=new Float32Array(MAX),bestValue=new Float64Array(MAX),oldX=new Float32Array(MAX),oldY=new Float32Array(MAX);
  let width=1,height=1,dpr=1,globalX=0,globalY=0,globalValue=Infinity,iteration=0,metricFrame=0;
  const configs={
    rastrigin:{name:'Rastrigin 多峰函数',min:-5.12,max:5.12,fn:(x,y)=>20+x*x+y*y-10*(Math.cos(2*Math.PI*x)+Math.cos(2*Math.PI*y))},
    ackley:{name:'Ackley 环形函数',min:-5,max:5,fn:(x,y)=>-20*Math.exp(-.2*Math.sqrt((x*x+y*y)/2))-Math.exp((Math.cos(2*Math.PI*x)+Math.cos(2*Math.PI*y))/2)+Math.E+20},
    himmelblau:{name:'Himmelblau 四谷函数',min:-6,max:6,fn:(x,y)=>(x*x+y-11)**2+(x+y*y-7)**2},
    sphere:{name:'Sphere 凸函数',min:-5,max:5,fn:(x,y)=>x*x+y*y}
  };
  const controls={count:document.getElementById('count'),maxSpeed:document.getElementById('max-speed'),inertia:document.getElementById('inertia'),cognitive:document.getElementById('cognitive'),social:document.getElementById('social')};
  const outputs={count:document.getElementById('count-value'),maxSpeed:document.getElementById('max-speed-value'),inertia:document.getElementById('inertia-value'),cognitive:document.getElementById('cognitive-value'),social:document.getElementById('social-value')};
  const format={count:v=>Math.round(v),maxSpeed:v=>Number(v).toFixed(2),inertia:v=>Number(v).toFixed(2),cognitive:v=>Number(v).toFixed(2),social:v=>Number(v).toFixed(2)};
  function syncRange(key){const input=controls[key],min=+input.min,max=+input.max;input.style.setProperty('--progress',`${(+input.value-min)/(max-min)*100}%`);outputs[key].textContent=format[key](input.value)}
  function random(min,max){return min+Math.random()*(max-min)}
  function config(){return configs[state.fn]}
  function reset(){const c=config();globalValue=Infinity;iteration=0;for(let i=0;i<state.count;i++){px[i]=random(c.min,c.max);py[i]=random(c.min,c.max);vx[i]=random(-.04,.04);vy[i]=random(-.04,.04);bestX[i]=px[i];bestY[i]=py[i];bestValue[i]=c.fn(px[i],py[i]);if(bestValue[i]<globalValue){globalValue=bestValue[i];globalX=px[i];globalY=py[i]}}updateMetrics()}
  function resize(){const rect=canvas.getBoundingClientRect();width=Math.max(1,rect.width);height=Math.max(1,rect.height);dpr=Math.min(2,window.devicePixelRatio||1);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);buildField()}
  function mix(a,b,t){return Math.round(a+(b-a)*t)}
  function fieldColor(t){const stops=[[243,195,92],[117,217,229],[37,85,92],[18,25,27]],points=[0,.13,.48,1];let k=0;while(k<points.length-2&&t>points[k+1])k++;const u=(t-points[k])/(points[k+1]-points[k]);return[mix(stops[k][0],stops[k+1][0],u),mix(stops[k][1],stops[k+1][1],u),mix(stops[k][2],stops[k+1][2],u)]}
  function buildField(){const fw=Math.min(260,Math.max(120,Math.round(width/5))),fh=Math.min(180,Math.max(90,Math.round(height/5)));field.width=fw;field.height=fh;const c=config(),values=new Float64Array(fw*fh);let min=Infinity,max=-Infinity;for(let y=0;y<fh;y++)for(let x=0;x<fw;x++){const wx=c.min+x/(fw-1)*(c.max-c.min),wy=c.max-y/(fh-1)*(c.max-c.min),v=c.fn(wx,wy);values[y*fw+x]=v;min=Math.min(min,v);max=Math.max(max,v)}const image=fieldCtx.createImageData(fw,fh),range=Math.log1p(max-min);for(let i=0;i<values.length;i++){const t=Math.min(1,Math.log1p(values[i]-min)/range),color=fieldColor(t),o=i*4;image.data[o]=color[0];image.data[o+1]=color[1];image.data[o+2]=color[2];image.data[o+3]=255}fieldCtx.putImageData(image,0,0)}
  function update(){const c=config(),span=c.max-c.min;iteration++;for(let i=0;i<state.count;i++){oldX[i]=px[i];oldY[i]=py[i];vx[i]=state.inertia*vx[i]+state.cognitive*Math.random()*(bestX[i]-px[i])+state.social*Math.random()*(globalX-px[i]);vy[i]=state.inertia*vy[i]+state.cognitive*Math.random()*(bestY[i]-py[i])+state.social*Math.random()*(globalY-py[i]);const speed=Math.hypot(vx[i],vy[i]);if(speed>state.maxSpeed){vx[i]=vx[i]/speed*state.maxSpeed;vy[i]=vy[i]/speed*state.maxSpeed}px[i]+=vx[i];py[i]+=vy[i];if(px[i]<c.min||px[i]>c.max){px[i]=Math.max(c.min,Math.min(c.max,px[i]));vx[i]*=-.5}if(py[i]<c.min||py[i]>c.max){py[i]=Math.max(c.min,Math.min(c.max,py[i]));vy[i]*=-.5}const value=c.fn(px[i],py[i]);if(value<bestValue[i]){bestValue[i]=value;bestX[i]=px[i];bestY[i]=py[i];if(value<globalValue){globalValue=value;globalX=px[i];globalY=py[i]}}}if(iteration>240&&globalValue<1e-7){for(let i=0;i<Math.max(1,state.count*.015);i++){const j=Math.floor(Math.random()*state.count);vx[j]+=random(-span*.015,span*.015);vy[j]+=random(-span*.015,span*.015)}}}
  function screenX(x){const c=config();return(x-c.min)/(c.max-c.min)*width}function screenY(y){const c=config();return(c.max-y)/(c.max-c.min)*height}
  function render(){ctx.drawImage(field,0,0,width,height);ctx.lineCap='round';for(let i=0;i<state.count;i++){const x=screenX(px[i]),y=screenY(py[i]),ox=screenX(oldX[i]),oy=screenY(oldY[i]);ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(ox,oy);ctx.lineWidth=1;ctx.strokeStyle='rgba(238,119,104,.5)';ctx.stroke();ctx.beginPath();ctx.arc(x,y,width<600?1.5:2.3,0,Math.PI*2);ctx.fillStyle='rgba(237,245,244,.92)';ctx.fill()}const gx=screenX(globalX),gy=screenY(globalY);ctx.beginPath();ctx.arc(gx,gy,11,0,Math.PI*2);ctx.lineWidth=1.5;ctx.strokeStyle='#f3c35c';ctx.stroke();ctx.beginPath();ctx.moveTo(gx-16,gy);ctx.lineTo(gx+16,gy);ctx.moveTo(gx,gy-16);ctx.lineTo(gx,gy+16);ctx.lineWidth=.7;ctx.strokeStyle='rgba(243,195,92,.75)';ctx.stroke()}
  function updateMetrics(){let diversity=0;const c=config(),span=c.max-c.min;for(let i=0;i<state.count;i++)diversity+=Math.hypot(px[i]-globalX,py[i]-globalY);diversity=diversity/state.count/span*100;document.getElementById('best').textContent=globalValue<.001?globalValue.toExponential(2):globalValue.toFixed(4);document.getElementById('iteration').textContent=iteration;document.getElementById('diversity').textContent=`${Math.round(Math.min(99,diversity))}%`;document.getElementById('position').textContent=`BEST (${globalX.toFixed(2)}, ${globalY.toFixed(2)})`}
  function frame(){if(!state.paused)update();render();if(metricFrame++%12===0)updateMetrics();requestAnimationFrame(frame)}
  document.getElementById('functions').addEventListener('click',event=>{const button=event.target.closest('button[data-function]');if(!button)return;state.fn=button.dataset.function;document.querySelectorAll('#functions button').forEach(item=>item.setAttribute('aria-pressed',String(item===button)));document.getElementById('function-name').textContent=config().name;buildField();reset()});
  for(const[key,input]of Object.entries(controls)){syncRange(key);input.addEventListener('input',()=>{state[key]=+input.value;syncRange(key);if(key==='count')reset()})}
  canvas.addEventListener('pointerdown',event=>{const rect=canvas.getBoundingClientRect(),c=config(),wx=c.min+(event.clientX-rect.left)/rect.width*(c.max-c.min),wy=c.max-(event.clientY-rect.top)/rect.height*(c.max-c.min),amount=Math.min(36,state.count);for(let i=0;i<amount;i++){px[i]=wx+random(-.3,.3);py[i]=wy+random(-.3,.3);vx[i]=random(-.08,.08);vy[i]=random(-.08,.08);bestX[i]=px[i];bestY[i]=py[i];bestValue[i]=c.fn(px[i],py[i])}});
  document.getElementById('reset').addEventListener('click',reset);document.getElementById('pause').addEventListener('click',()=>{state.paused=!state.paused;document.getElementById('pause-icon').textContent=state.paused?'▶':'Ⅱ';document.getElementById('pause-label').textContent=state.paused?'继续':'暂停'});new ResizeObserver(resize).observe(canvas);resize();reset();requestAnimationFrame(frame);
})();
