(() => {
  'use strict';
  const canvas=document.getElementById('canvas'),ctx=canvas.getContext('2d',{alpha:false});
  const state={capacity:8,speed:1,paused:false,auto:true,values:[18,42,73],operations:0,status:'等待操作'};
  let width=1,height=1,dpr=1,active=null,autoDelay=0,last=performance.now();
  const valueInput=document.getElementById('value'),capacityInput=document.getElementById('capacity'),speedInput=document.getElementById('speed');
  function fitRange(input,output,format=v=>v){const sync=()=>{const n=+input.value;input.style.setProperty('--progress',`${(n-input.min)/(input.max-input.min)*100}%`);output.textContent=format(n)};input.addEventListener('input',sync);sync()}
  fitRange(capacityInput,document.getElementById('capacity-value'));fitRange(speedInput,document.getElementById('speed-value'),v=>`${v.toFixed(1)}×`);
  function metrics(){document.getElementById('status').textContent=state.status;document.getElementById('size').textContent=state.values.length;document.getElementById('free').textContent=state.capacity-state.values.length;document.getElementById('operations').textContent=state.operations;document.getElementById('top-label').textContent=`TOP = ${state.values.length-1}`}
  function begin(type,value){if(active)return false;if(type==='push'&&state.values.length>=state.capacity){state.status='栈已满 · Overflow';metrics();return false}if((type==='pop'||type==='peek')&&!state.values.length){state.status='栈为空 · Underflow';metrics();return false}if(type==='pop')value=state.values.pop();if(type==='peek')value=state.values[state.values.length-1];active={type,value,progress:0};state.operations++;state.status={push:`压入 ${value}`,pop:`弹出 ${value}`,peek:`读取栈顶 ${value}`}[type];metrics();return true}
  function finish(){if(active.type==='push')state.values.push(active.value);state.status=active.type==='peek'?`栈顶元素是 ${active.value}`:'等待操作';active=null;metrics()}
  function stepOperation(){if(active){active.progress=1;finish();return}const value=Math.max(0,Math.min(999,Math.round(+valueInput.value||0)));begin('push',value)}
  function autoOperation(){const room=state.values.length<state.capacity,has=state.values.length>0,r=Math.random();if(!has||room&&r<.56)begin('push',Math.floor(10+Math.random()*90));else if(r<.86)begin('pop');else begin('peek')}
  function resize(){const rect=canvas.getBoundingClientRect();width=Math.max(1,rect.width);height=Math.max(1,rect.height);dpr=Math.min(2,devicePixelRatio||1);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)}
  function layout(){const cellH=Math.min(54,Math.max(30,(height-190)/state.capacity)),cellW=Math.min(280,Math.max(150,width*.34));return{cellH,cellW,x:width*.5-cellW*.5,bottom:height-72}}
  function rounded(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
  function drawCell(value,index,alpha=1,offsetY=0,accent=false){const l=layout(),y=l.bottom-(index+1)*l.cellH+offsetY;ctx.globalAlpha=alpha;rounded(l.x,y+4,l.cellW,l.cellH-8,5);ctx.fillStyle=accent?'#70dfaa':'#1b2926';ctx.fill();ctx.strokeStyle=accent?'#70dfaa':'rgba(237,247,242,.18)';ctx.lineWidth=1;ctx.stroke();ctx.fillStyle=accent?'#101817':'#edf7f2';ctx.font='600 16px ui-monospace,Consolas,monospace';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(String(value),width*.5,y+l.cellH*.5);ctx.textAlign='left';ctx.font='10px ui-monospace,Consolas,monospace';ctx.fillStyle=accent?'#101817':'#8fa19b';ctx.fillText(`[${index}]`,l.x+14,y+l.cellH*.5);ctx.globalAlpha=1}
  function render(){ctx.fillStyle='#101817';ctx.fillRect(0,0,width,height);const l=layout();ctx.strokeStyle='rgba(237,247,242,.18)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(l.x-9,l.bottom-state.capacity*l.cellH);ctx.lineTo(l.x-9,l.bottom+1);ctx.lineTo(l.x+l.cellW+9,l.bottom+1);ctx.lineTo(l.x+l.cellW+9,l.bottom-state.capacity*l.cellH);ctx.stroke();for(let i=0;i<state.capacity;i++){const y=l.bottom-(i+1)*l.cellH;ctx.strokeStyle='rgba(237,247,242,.055)';ctx.strokeRect(l.x,y+4,l.cellW,l.cellH-8)}state.values.forEach((v,i)=>drawCell(v,i));if(active){if(active.type==='push'){const distance=(state.capacity-state.values.length+1)*l.cellH;drawCell(active.value,state.values.length,1,-distance*(1-active.progress),true)}else if(active.type==='pop'){drawCell(active.value,state.values.length,1,-l.cellH*2*active.progress,true)}else{const pulse=.55+.45*Math.sin(active.progress*Math.PI*4);drawCell(active.value,state.values.length-1,pulse,0,true)}}ctx.fillStyle='#8fa19b';ctx.font='10px ui-monospace,Consolas,monospace';ctx.textAlign='center';ctx.fillText('STACK MEMORY',width*.5,Math.max(120,l.bottom-state.capacity*l.cellH-24))}
  function frame(now){const dt=Math.min(40,now-last);last=now;if(!state.paused){if(active){active.progress=Math.min(1,active.progress+dt*.0012*state.speed);if(active.progress>=1)finish()}else if(state.auto&&(autoDelay+=dt)>1250/state.speed){autoDelay=0;autoOperation()}}render();requestAnimationFrame(frame)}
  document.getElementById('push').addEventListener('click',()=>begin('push',Math.max(0,Math.min(999,Math.round(+valueInput.value||0)))));document.getElementById('pop').addEventListener('click',()=>begin('pop'));document.getElementById('peek').addEventListener('click',()=>begin('peek'));document.getElementById('step').addEventListener('click',stepOperation);
  capacityInput.addEventListener('input',()=>{state.capacity=+capacityInput.value;if(state.values.length>state.capacity)state.values.length=state.capacity;active=null;metrics()});speedInput.addEventListener('input',()=>state.speed=+speedInput.value);document.getElementById('auto').addEventListener('change',e=>state.auto=e.target.checked);
  document.getElementById('pause').addEventListener('click',()=>{state.paused=!state.paused;document.getElementById('pause-icon').textContent=state.paused?'▶':'Ⅱ';document.getElementById('pause-label').textContent=state.paused?'继续':'暂停'});document.getElementById('reset').addEventListener('click',()=>{state.values=[18,42,73].slice(0,state.capacity);state.operations=0;state.status='等待操作';active=null;metrics()});
  new ResizeObserver(resize).observe(canvas);resize();metrics();requestAnimationFrame(frame);
})();
