(() => {
  'use strict';
  const canvas=document.getElementById('canvas'),ctx=canvas.getContext('2d',{alpha:false}),nodeInput=document.getElementById('nodes'),speedInput=document.getElementById('speed'),selectA=document.getElementById('node-a'),selectB=document.getElementById('node-b');
  const state={count:12,speed:1,paused:false,compression:true,auto:false,parent:[],rank:[],active:null,status:'等待操作',operations:0};let width=1,height=1,dpr=1,last=performance.now(),timer=0,autoTimer=0;
  function root(x){while(state.parent[x]!==x)x=state.parent[x];return x}function path(x){const result=[x];while(state.parent[x]!==x){x=state.parent[x];result.push(x)}return result}
  function directUnion(a,b){let ra=root(a),rb=root(b);if(ra===rb)return;if(state.rank[ra]<state.rank[rb])[ra,rb]=[rb,ra];state.parent[rb]=ra;if(state.rank[ra]===state.rank[rb])state.rank[ra]++}
  function populateSelects(){const fresh=selectA.options.length===0,valueA=fresh?Math.min(4,state.count-1):Math.min(+selectA.value||0,state.count-1),valueB=fresh?Math.min(8,state.count-1):Math.min(+selectB.value||1,state.count-1);selectA.innerHTML='';selectB.innerHTML='';for(let i=0;i<state.count;i++){selectA.add(new Option(String(i),String(i)));selectB.add(new Option(String(i),String(i)))}selectA.value=String(valueA);selectB.value=String(valueB===valueA?(valueA+1)%state.count:valueB)}
  function reset(){state.parent=Array.from({length:state.count},(_,i)=>i);state.rank=Array(state.count).fill(0);if(state.count>1)state.parent[1]=0;if(state.count>2)state.parent[2]=1;if(state.count>3)state.parent[3]=2;if(state.count>4)state.parent[4]=3;if(state.count>0)state.rank[0]=4;if(state.count>7)state.parent[7]=6;if(state.count>8)state.parent[8]=7;if(state.count>6)state.rank[6]=2;if(state.count>10){state.parent[10]=9;state.rank[9]=1}state.active=null;state.status='等待操作';state.operations=0;populateSelects();metrics()}
  function components(){return new Set(state.parent.map((_,i)=>root(i))).size}function maxDepth(){let max=0;for(let i=0;i<state.count;i++)max=Math.max(max,path(i).length-1);return max}
  function metrics(){document.getElementById('status').textContent=state.status;document.getElementById('components').textContent=components();document.getElementById('depth').textContent=maxDepth();document.getElementById('operations').textContent=state.operations;document.getElementById('path-label').textContent=state.active?.visited.length?`PATH ${state.active.visited.join(' → ')}`:'PATH --'}
  function stepsForFind(x,label){const p=path(x),steps=p.map(node=>({kind:'visit',node,label}));if(state.compression&&p.length>2)steps.push({kind:'compress',nodes:p.slice(0,-1),root:p[p.length-1],label});return{p,steps}}
  function start(type,a,b=a){if(state.active)return;const first=stepsForFind(a,'A'),steps=[...first.steps];let second=null;if(type!=='find'){second=stepsForFind(b,'B');steps.push(...second.steps)}if(type==='union')steps.push({kind:'union',aRoot:first.p.at(-1),bRoot:second.p.at(-1)});if(type==='connected')steps.push({kind:'connected',aRoot:first.p.at(-1),bRoot:second.p.at(-1)});state.active={type,a,b,steps,index:-1,visited:[],current:null,done:false};state.operations++;state.status={find:`查找节点 ${a} 的根`,union:`合并 ${a} 与 ${b}`,connected:`判断 ${a} 与 ${b}`}[type];timer=0;metrics()}
  function advance(){const a=state.active;if(!a)return;if(a.done){state.active=null;state.status='等待操作';metrics();return}a.index++;if(a.index>=a.steps.length){a.done=true;return metrics()}const step=a.steps[a.index];if(step.kind==='visit'){a.current=step.node;a.visited.push(step.node);state.status=`沿父指针访问 ${step.node}`}else if(step.kind==='compress'){step.nodes.forEach(node=>state.parent[node]=step.root);a.current=step.root;state.status=`路径压缩到根 ${step.root}`}else if(step.kind==='union'){let ra=root(step.aRoot),rb=root(step.bRoot);if(ra===rb)state.status='两个节点已经连通';else{if(state.rank[ra]<state.rank[rb])[ra,rb]=[rb,ra];state.parent[rb]=ra;if(state.rank[ra]===state.rank[rb])state.rank[ra]++;state.status=`将根 ${rb} 连接到根 ${ra}`}a.current=ra}else{const connected=root(step.aRoot)===root(step.bRoot);state.status=connected?'两个节点属于同一集合':'两个节点不连通'}metrics()}
  function randomUnion(){let a=Math.floor(Math.random()*state.count),b=Math.floor(Math.random()*state.count);if(a===b)b=(b+1)%state.count;start('union',a,b)}
  function resize(){const rect=canvas.getBoundingClientRect();width=Math.max(1,rect.width);height=Math.max(1,rect.height);dpr=Math.min(2,devicePixelRatio||1);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)}
  function positions(){const cx=width*.5,cy=height*.54,rx=Math.max(100,Math.min(width*.39,390)),ry=Math.max(100,Math.min((height-180)*.38,230));return Array.from({length:state.count},(_,i)=>{const angle=-Math.PI*.5+i*Math.PI*2/state.count;return{x:cx+Math.cos(angle)*rx,y:cy+Math.sin(angle)*ry}})}
  function render(){ctx.fillStyle='#15151b';ctx.fillRect(0,0,width,height);const pos=positions(),colors=['#a99af2','#68d2d2','#efc15c','#ee806f'];ctx.lineWidth=1.5;for(let i=0;i<state.count;i++){if(state.parent[i]===i)continue;const from=pos[i],to=pos[state.parent[i]],hot=state.active?.visited.includes(i);ctx.strokeStyle=hot?'#f4f3fb':'rgba(244,243,251,.22)';ctx.beginPath();ctx.moveTo(from.x,from.y);ctx.lineTo(to.x,to.y);ctx.stroke();const angle=Math.atan2(to.y-from.y,to.x-from.x),ax=to.x-Math.cos(angle)*25,ay=to.y-Math.sin(angle)*25;ctx.fillStyle=hot?'#f4f3fb':'#777783';ctx.beginPath();ctx.moveTo(ax,ay);ctx.lineTo(ax-Math.cos(angle-.55)*7,ay-Math.sin(angle-.55)*7);ctx.lineTo(ax-Math.cos(angle+.55)*7,ay-Math.sin(angle+.55)*7);ctx.closePath();ctx.fill()}for(let i=0;i<state.count;i++){const p=pos[i],r=root(i),color=colors[r%colors.length],hot=state.active?.current===i,rootNode=state.parent[i]===i;ctx.beginPath();ctx.arc(p.x,p.y,rootNode?24:20,0,Math.PI*2);ctx.fillStyle=hot?'#f4f3fb':'#20202a';ctx.fill();ctx.strokeStyle=hot?'#f4f3fb':color;ctx.lineWidth=rootNode?3:1.5;ctx.stroke();if(rootNode){ctx.beginPath();ctx.arc(p.x,p.y,18,0,Math.PI*2);ctx.strokeStyle=color;ctx.lineWidth=1;ctx.stroke()}ctx.fillStyle=hot?'#15151b':'#f4f3fb';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='600 12px ui-monospace,Consolas,monospace';ctx.fillText(String(i),p.x,p.y)}ctx.fillStyle='#9998a6';ctx.textAlign='center';ctx.font='10px ui-monospace,Consolas,monospace';ctx.fillText('箭头指向父节点 · 双环表示集合根',width*.5,Math.max(120,height*.54-Math.min((height-180)*.38,230)-48))}
  function frame(now){const dt=Math.min(50,now-last);last=now;if(!state.paused){if(state.active){timer+=dt;if(timer>650/state.speed){timer=0;advance()}}else if(state.auto&&(autoTimer+=dt)>1600/state.speed){autoTimer=0;randomUnion()}}render();requestAnimationFrame(frame)}
  const selected=()=>[+selectA.value,+selectB.value];document.getElementById('union').addEventListener('click',()=>{const[a,b]=selected();start('union',a,b)});document.getElementById('find-a').addEventListener('click',()=>start('find',+selectA.value));document.getElementById('connected').addEventListener('click',()=>{const[a,b]=selected();start('connected',a,b)});document.getElementById('step').addEventListener('click',()=>{if(state.active)advance();else start('find',+selectA.value)});nodeInput.addEventListener('input',()=>{state.count=+nodeInput.value;nodeInput.style.setProperty('--progress',`${(state.count-6)/12*100}%`);document.getElementById('nodes-value').textContent=state.count;reset()});speedInput.addEventListener('input',()=>{state.speed=+speedInput.value;speedInput.style.setProperty('--progress',`${(state.speed-.4)/2.2*100}%`);document.getElementById('speed-value').textContent=`${state.speed.toFixed(1)}×`});document.getElementById('compression').addEventListener('change',e=>state.compression=e.target.checked);document.getElementById('auto').addEventListener('change',e=>state.auto=e.target.checked);document.getElementById('reset').addEventListener('click',reset);document.getElementById('pause').addEventListener('click',()=>{state.paused=!state.paused;document.getElementById('pause-icon').textContent=state.paused?'▶':'Ⅱ';document.getElementById('pause-label').textContent=state.paused?'继续':'暂停'});
  nodeInput.dispatchEvent(new Event('input'));speedInput.dispatchEvent(new Event('input'));new ResizeObserver(resize).observe(canvas);resize();requestAnimationFrame(frame);
})();
