(() => {
  'use strict';
  const canvas=document.getElementById('canvas'),ctx=canvas.getContext('2d',{alpha:false});
  const state={capacity:8,speed:1,paused:false,auto:true,buffer:Array(8).fill(null),head:0,tail:3,size:3,status:'等待操作'};state.buffer[0]=24;state.buffer[1]=61;state.buffer[2]=37;
  let width=1,height=1,dpr=1,active=null,last=performance.now(),autoDelay=0;
  const valueInput=document.getElementById('value'),capacityInput=document.getElementById('capacity'),speedInput=document.getElementById('speed');
  function range(input,output,format=v=>v){const sync=()=>{const n=+input.value;input.style.setProperty('--progress',`${(n-input.min)/(input.max-input.min)*100}%`);output.textContent=format(n)};input.addEventListener('input',sync);sync()}range(capacityInput,document.getElementById('capacity-value'));range(speedInput,document.getElementById('speed-value'),v=>`${v.toFixed(1)}×`);
  function metrics(){document.getElementById('status').textContent=state.status;document.getElementById('size').textContent=state.size;document.getElementById('head').textContent=state.head;document.getElementById('tail').textContent=state.tail}
  function begin(type,value){if(active)return false;if(type==='enqueue'&&state.size===state.capacity){state.status='队列已满 · Overflow';metrics();return false}if((type==='dequeue'||type==='front')&&state.size===0){state.status='队列为空 · Underflow';metrics();return false}if(type!=='enqueue')value=state.buffer[state.head];active={type,value,index:type==='enqueue'?state.tail:state.head,progress:0};state.status={enqueue:`入队 ${value}`,dequeue:`出队 ${value}`,front:`读取队首 ${value}`}[type];metrics();return true}
  function finish(){if(active.type==='enqueue'){state.buffer[active.index]=active.value;state.tail=(state.tail+1)%state.capacity;state.size++}else if(active.type==='dequeue'){state.buffer[active.index]=null;state.head=(state.head+1)%state.capacity;state.size--}state.status=active.type==='front'?`队首元素是 ${active.value}`:'等待操作';active=null;metrics()}
  function autoOperation(){const r=Math.random();if(!state.size||state.size<state.capacity&&r<.6)begin('enqueue',Math.floor(10+Math.random()*90));else if(r<.88)begin('dequeue');else begin('front')}
  function resize(){const rect=canvas.getBoundingClientRect();width=Math.max(1,rect.width);height=Math.max(1,rect.height);dpr=Math.min(2,devicePixelRatio||1);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)}
  function layout(){const gap=Math.max(5,Math.min(11,width*.01)),cell=Math.min(82,Math.max(42,(width-90-gap*(state.capacity-1))/state.capacity)),total=cell*state.capacity+gap*(state.capacity-1);return{gap,cell,start:width*.5-total*.5,y:height*.52-cell*.5}}
  function cell(index,value,activeCell=false,offsetX=0,alpha=1){const l=layout(),x=l.start+index*(l.cell+l.gap)+offsetX;ctx.globalAlpha=alpha;ctx.beginPath();ctx.roundRect(x,l.y,l.cell,l.cell,6);ctx.fillStyle=activeCell?'#68bdec':'#1b252e';ctx.fill();ctx.strokeStyle=activeCell?'#68bdec':'rgba(240,245,250,.18)';ctx.stroke();ctx.fillStyle=activeCell?'#11171d':'#f0f5fa';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`600 ${Math.max(12,Math.min(18,l.cell*.25))}px ui-monospace,Consolas,monospace`;if(value!==null)ctx.fillText(String(value),x+l.cell*.5,l.y+l.cell*.5);ctx.font='9px ui-monospace,Consolas,monospace';ctx.fillStyle=activeCell?'#11171d':'#91a0ad';ctx.fillText(String(index),x+l.cell*.5,l.y+l.cell-10);ctx.globalAlpha=1}
  function marker(index,label,color,above){const l=layout(),x=l.start+index*(l.cell+l.gap)+l.cell*.5,y=above?l.y-34:l.y+l.cell+34;ctx.fillStyle=color;ctx.textAlign='center';ctx.font='600 10px ui-monospace,Consolas,monospace';ctx.fillText(label,x,y);ctx.beginPath();if(above){ctx.moveTo(x,y+8);ctx.lineTo(x-5,y+16);ctx.lineTo(x+5,y+16)}else{ctx.moveTo(x,y-8);ctx.lineTo(x-5,y-16);ctx.lineTo(x+5,y-16)}ctx.closePath();ctx.fill()}
  function render(){ctx.fillStyle='#11171d';ctx.fillRect(0,0,width,height);for(let i=0;i<state.capacity;i++)cell(i,state.buffer[i]);if(active){const l=layout();if(active.type==='enqueue')cell(active.index,active.value,true,l.cell*1.5*(1-active.progress));else if(active.type==='dequeue')cell(active.index,active.value,true,-l.cell*1.5*active.progress,1-active.progress*.35);else cell(active.index,active.value,true,0,.55+.45*Math.sin(active.progress*Math.PI*4))}marker(state.head,'HEAD','#f2c25f',true);marker(state.tail,'TAIL','#68bdec',false);ctx.fillStyle='#91a0ad';ctx.textAlign='center';ctx.font='10px ui-monospace,Consolas,monospace';ctx.fillText('CIRCULAR BUFFER',width*.5,Math.max(130,layout().y-72))}
  function frame(now){const dt=Math.min(40,now-last);last=now;if(!state.paused){if(active){active.progress=Math.min(1,active.progress+dt*.0012*state.speed);if(active.progress>=1)finish()}else if(state.auto&&(autoDelay+=dt)>1250/state.speed){autoDelay=0;autoOperation()}}render();requestAnimationFrame(frame)}
  document.getElementById('enqueue').addEventListener('click',()=>begin('enqueue',Math.max(0,Math.min(999,Math.round(+valueInput.value||0)))));document.getElementById('dequeue').addEventListener('click',()=>begin('dequeue'));document.getElementById('front').addEventListener('click',()=>begin('front'));document.getElementById('step').addEventListener('click',()=>{if(active){active.progress=1;finish()}else autoOperation()});capacityInput.addEventListener('input',()=>{state.capacity=+capacityInput.value;state.buffer=Array(state.capacity).fill(null);state.head=0;state.tail=0;state.size=0;active=null;state.status='容量已调整';metrics()});speedInput.addEventListener('input',()=>state.speed=+speedInput.value);document.getElementById('auto').addEventListener('change',e=>state.auto=e.target.checked);document.getElementById('pause').addEventListener('click',()=>{state.paused=!state.paused;document.getElementById('pause-icon').textContent=state.paused?'▶':'Ⅱ';document.getElementById('pause-label').textContent=state.paused?'继续':'暂停'});document.getElementById('reset').addEventListener('click',()=>{state.buffer=Array(state.capacity).fill(null);[24,61,37].slice(0,state.capacity).forEach((v,i)=>state.buffer[i]=v);state.head=0;state.size=Math.min(3,state.capacity);state.tail=state.size%state.capacity;active=null;state.status='等待操作';metrics()});
  new ResizeObserver(resize).observe(canvas);resize();metrics();requestAnimationFrame(frame);
})();
