(() => {
  'use strict';
  const canvas = document.getElementById('canvas'), ctx = canvas.getContext('2d', { alpha: false });
  const initial = [48, 26, 72, 14, 34, 61, 86, 30, 66];
  let root = null, nextId = 1, width = 1, height = 1, dpr = 1;
  let timeline = [], timelineIndex = -1, active = {}, running = false, paused = false, speed = 5, lastAdvance = 0, comparisons = 0;
  const el = id => document.getElementById(id), input = el('node-value');
  function node(value) { return { id: nextId++, value, left: null, right: null }; }
  function insertDirect(value) { const fresh = node(value); if (!root) { root = fresh; return fresh; } let current = root; while (true) { if (value === current.value) return null; const side = value < current.value ? 'left' : 'right'; if (!current[side]) { current[side] = fresh; return fresh; } current = current[side]; } }
  function count(current = root) { return current ? 1 + count(current.left) + count(current.right) : 0; }
  function treeHeight(current = root) { return current ? 1 + Math.max(treeHeight(current.left), treeHeight(current.right)) : 0; }
  function findById(id, current = root, parent = null) { if (!current) return null; if (current.id === id) return { node: current, parent }; return findById(id, current.left, current) || findById(id, current.right, current); }
  function syncMetrics() { el('metric-count').textContent = count(); el('metric-height').textContent = treeHeight(); el('metric-comparisons').textContent = comparisons; }
  function setPaused(value) { paused = value; for (const id of ['pause-icon','stage-pause-icon']) el(id).classList.toggle('play', paused); el('pause-label').textContent = paused ? '继续' : '暂停'; el('stage-pause-label').textContent = paused ? '继续' : '暂停'; el('live-dot').classList.toggle('paused', paused); }
  function advance() { if (!running) return; timelineIndex += 1; if (timelineIndex >= timeline.length) { running = false; active = {}; setPaused(false); el('status').textContent = '操作完成'; el('step-label').textContent = 'DONE'; return; } active = timeline[timelineIndex]; if (active.apply) active.apply(); el('status').textContent = active.message; el('operation-label').textContent = active.code; el('step-label').textContent = `${timelineIndex + 1} / ${timeline.length}`; lastAdvance = performance.now(); syncMetrics(); }
  function play(steps) { timeline = steps; timelineIndex = -1; running = true; setPaused(false); advance(); }
  function value() { const v = Number(input.value); return Math.max(0, Math.min(99, Number.isFinite(v) ? Math.round(v) : 0)); }
  function searchSteps(target) { const steps = []; let current = root; while (current) { const id = current.id, v = current.value; steps.push({ message: `比较 ${target} 与 ${v}`, focus: [id], code: target === v ? `${target} == ${v}` : target < v ? `${target} < ${v}，进入左子树` : `${target} > ${v}，进入右子树`, apply: () => { comparisons += 1; } }); if (target === v) break; current = target < v ? current.left : current.right; } return { steps, found: current }; }
  function insertValue() { const target = value(); if (count() >= 15) { el('status').textContent = '最多演示 15 个节点'; return; } if (!root) { const fresh = node(target); play([{ message: `建立根节点 ${target}`, focus:[fresh.id], code:'root = new Node', apply:()=>{root=fresh;} }]); return; } const { steps, found } = searchSteps(target); if (found) { steps.push({ message:`键值 ${target} 已存在`, focus:[found.id], code:'忽略重复键' }); play(steps); return; } let parent = root; while (target < parent.value ? parent.left : parent.right) parent = target < parent.value ? parent.left : parent.right; const side = target < parent.value ? 'left' : 'right', fresh = node(target); steps.push({ message:`找到空的${side === 'left' ? '左' : '右'}孩子位置`, focus:[parent.id], code:`parent.${side} == null` }); steps.push({ message:`插入节点 ${target}`, focus:[parent.id,fresh.id], edge:[parent.id,fresh.id], code:`parent.${side} = new Node`, apply:()=>{parent[side]=fresh;} }); play(steps); }
  function findValue() { const target = value(), result = searchSteps(target); result.steps.push(result.found ? { message:`找到键值 ${target}`, focus:[result.found.id], code:'return node' } : { message:`键值 ${target} 不在树中`, code:'current == null' }); if (!result.steps.length) result.steps.push({message:'树为空',code:'root == null'}); play(result.steps); }
  function detach(id) { const found = findById(id); if (!found) return; const child = found.node.left || found.node.right; if (!found.parent) root = child; else if (found.parent.left === found.node) found.parent.left = child; else found.parent.right = child; }
  function removeValue() { const target = value(), result = searchSteps(target), targetNode = result.found; if (!targetNode) { result.steps.push({message:`键值 ${target} 不在树中`,code:'无需删除'}); play(result.steps.length ? result.steps : [{message:'树为空',code:'root == null'}]); return; } result.steps.push({message:`定位删除目标 ${target}`,focus:[targetNode.id],deleting:targetNode.id,code:'delete current'}); if (!targetNode.left || !targetNode.right) { const child = targetNode.left || targetNode.right; result.steps.push({message:child ? '用唯一孩子替代目标' : '移除叶节点',focus:child?[targetNode.id,child.id]:[targetNode.id],deleting:targetNode.id,code:child?'parent.child = current.child':'parent.child = null',apply:()=>detach(targetNode.id)}); } else { let successor = targetNode.right; while (successor.left) { successor = successor.left; const id=successor.id; result.steps.push({message:`寻找中序后继：${successor.value}`,focus:[id],code:'successor = successor.left',apply:()=>{comparisons+=1;}}); } const successorId=successor.id, successorValue=successor.value; result.steps.push({message:`复制后继 ${successorValue} 到目标`,focus:[targetNode.id,successorId],code:'current.value = successor.value',apply:()=>{targetNode.value=successorValue;}}); result.steps.push({message:'删除原后继节点',focus:[successorId],deleting:successorId,code:'remove successor',apply:()=>detach(successorId)}); } play(result.steps); }
  function positions() { const ordered=[]; function walk(n,depth,parent){if(!n)return;walk(n.left,depth+1,n);ordered.push({node:n,depth,parent});walk(n.right,depth+1,n)} walk(root,0,null); const map=new Map(), top=width<760?118:135, bottom=65, usableH=Math.max(100,height-top-bottom), maxDepth=Math.max(1,...ordered.map(x=>x.depth)); ordered.forEach((item,index)=>map.set(item.node.id,{x:ordered.length===1?width/2:35+index*(width-70)/(ordered.length-1),y:top+item.depth*usableH/maxDepth,depth:item.depth})); return {ordered,map}; }
  function render() { ctx.fillStyle='#111816';ctx.fillRect(0,0,width,height);const {ordered,map}=positions(),radius=Math.max(15,Math.min(23,width/(Math.max(10,ordered.length)*2.2)));for(const item of ordered){if(!item.parent)continue;const a=map.get(item.parent.id),b=map.get(item.node.id),hot=active.edge&&active.edge[0]===item.parent.id&&active.edge[1]===item.node.id;ctx.strokeStyle=hot?'#f1bd58':'#3b4a44';ctx.lineWidth=hot?2:1.2;ctx.beginPath();ctx.moveTo(a.x,a.y+radius*.65);ctx.lineTo(b.x,b.y-radius*.65);ctx.stroke();}for(const item of ordered){const p=map.get(item.node.id),focused=active.focus?.includes(item.node.id),deleting=active.deleting===item.node.id;ctx.beginPath();ctx.arc(p.x,p.y,radius,0,Math.PI*2);ctx.fillStyle=deleting?'#3b2421':focused?'#203b31':'#18221f';ctx.fill();ctx.strokeStyle=deleting?'#ef7968':focused?'#78d9b2':'#45534d';ctx.lineWidth=focused||deleting?2:1;ctx.stroke();ctx.fillStyle='#eff3eb';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`600 ${Math.max(11,radius*.68)}px ui-monospace,Consolas`;ctx.fillText(item.node.value,p.x,p.y);if(!item.parent){ctx.fillStyle='#f1bd58';ctx.font='9px ui-monospace,Consolas';ctx.fillText('ROOT',p.x,p.y-radius-12);}}if(!root){ctx.fillStyle='#718079';ctx.textAlign='center';ctx.font='12px ui-monospace,Consolas';ctx.fillText('EMPTY TREE',width/2,height/2);}}
  function resize(){const r=canvas.getBoundingClientRect();width=Math.max(1,r.width);height=Math.max(1,r.height);dpr=Math.min(2,devicePixelRatio||1);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)}
  function reset(values=initial){root=null;nextId=1;values.forEach(insertDirect);timeline=[];active={};running=false;comparisons=0;setPaused(false);el('status').textContent='等待操作';el('operation-label').textContent='较小向左，较大向右';el('step-label').textContent='READY';syncMetrics()}
  function randomize(){const values=[];while(values.length<9){const v=10+Math.floor(Math.random()*80);if(!values.includes(v))values.push(v)}reset(values)}
  function frame(now){if(running&&!paused&&now-lastAdvance>=1450-speed*115)advance();render();requestAnimationFrame(frame)}
  function toggle(){if(running){setPaused(!paused);lastAdvance=performance.now()}}
  el('insert').onclick=insertValue;el('find').onclick=findValue;el('remove').onclick=removeValue;el('randomize').onclick=randomize;el('reset').onclick=()=>reset();el('stage-reset').onclick=()=>reset();el('pause').onclick=toggle;el('stage-pause').onclick=toggle;el('step').onclick=()=>{if(running){setPaused(true);advance()}};input.addEventListener('keydown',e=>{if(e.key==='Enter')insertValue()});el('speed').addEventListener('input',e=>{speed=Number(e.target.value);el('speed-value').textContent=speed;e.target.style.setProperty('--progress',`${(speed-1)/9*100}%`)});el('speed').dispatchEvent(new Event('input'));new ResizeObserver(resize).observe(canvas);reset();resize();requestAnimationFrame(frame);
})();
