(() => {
  'use strict';
  const MAX=9000,TAU=Math.PI*2,canvas=document.getElementById('canvas'),ctx=canvas.getContext('2d',{alpha:false});
  const state={count:3500,speed:1.8,fade:.08,scale:1.4,turns:2.2,evolution:.35,vectors:false,tool:'vortex',paused:false};
  const x=new Float32Array(MAX),y=new Float32Array(MAX),oldX=new Float32Array(MAX),oldY=new Float32Array(MAX),vx=new Float32Array(MAX),vy=new Float32Array(MAX),age=new Uint16Array(MAX),life=new Uint16Array(MAX);
  let width=1,height=1,dpr=1,time=0,last=performance.now(),fpsTime=last,fpsFrames=0,pointer={x:0,y:0,active:false,inside:false};
  const permutation=new Uint8Array(512),source=Array.from({length:256},(_,i)=>i);for(let i=255;i>0;i--){const j=Math.floor(Math.random()*(i+1));[source[i],source[j]]=[source[j],source[i]]}for(let i=0;i<512;i++)permutation[i]=source[i&255];
  const controls={count:document.getElementById('count'),speed:document.getElementById('speed'),fade:document.getElementById('fade'),scale:document.getElementById('scale'),turns:document.getElementById('turns'),evolution:document.getElementById('evolution')};
  const outputs={count:document.getElementById('count-value'),speed:document.getElementById('speed-value'),fade:document.getElementById('fade-value'),scale:document.getElementById('scale-value'),turns:document.getElementById('turns-value'),evolution:document.getElementById('evolution-value')};
  const format={count:v=>Math.round(v),speed:v=>Number(v).toFixed(1),fade:v=>`${Math.round(v)}%`,scale:v=>Number(v).toFixed(1),turns:v=>Number(v).toFixed(1),evolution:v=>Number(v).toFixed(2)};
  function syncRange(key){const input=controls[key],min=+input.min,max=+input.max;input.style.setProperty('--progress',`${(+input.value-min)/(max-min)*100}%`);outputs[key].textContent=format[key](input.value)}
  function fade(t){return t*t*t*(t*(t*6-15)+10)}function lerp(a,b,t){return a+(b-a)*t}function grad(hash,gx,gy,gz){const h=hash&15,u=h<8?gx:gy,v=h<4?gy:h===12||h===14?gx:gz;return((h&1)?-u:u)+((h&2)?-v:v)}
  function noise(nx,ny,nz){const X=Math.floor(nx)&255,Y=Math.floor(ny)&255,Z=Math.floor(nz)&255,xf=nx-Math.floor(nx),yf=ny-Math.floor(ny),zf=nz-Math.floor(nz),u=fade(xf),v=fade(yf),w=fade(zf),A=permutation[X]+Y,AA=permutation[A]+Z,AB=permutation[A+1]+Z,B=permutation[X+1]+Y,BA=permutation[B]+Z,BB=permutation[B+1]+Z;return lerp(lerp(lerp(grad(permutation[AA],xf,yf,zf),grad(permutation[BA],xf-1,yf,zf),u),lerp(grad(permutation[AB],xf,yf-1,zf),grad(permutation[BB],xf-1,yf-1,zf),u),v),lerp(lerp(grad(permutation[AA+1],xf,yf,zf-1),grad(permutation[BA+1],xf-1,yf,zf-1),u),lerp(grad(permutation[AB+1],xf,yf-1,zf-1),grad(permutation[BB+1],xf-1,yf-1,zf-1),u),v),w)}
  function seedParticle(i,randomAge=false){x[i]=Math.random()*width;y[i]=Math.random()*height;oldX[i]=x[i];oldY[i]=y[i];vx[i]=0;vy[i]=0;life[i]=180+Math.random()*520;age[i]=randomAge?Math.random()*life[i]:0}
  function reset(){for(let i=0;i<state.count;i++)seedParticle(i,true);ctx.fillStyle='#12191b';ctx.fillRect(0,0,width,height)}
  function resize(){const rect=canvas.getBoundingClientRect(),ow=width,oh=height;width=Math.max(1,rect.width);height=Math.max(1,rect.height);dpr=Math.min(1.6,window.devicePixelRatio||1);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);if(ow>1&&oh>1)for(let i=0;i<state.count;i++){x[i]=x[i]/ow*width;y[i]=y[i]/oh*height}ctx.fillStyle='#12191b';ctx.fillRect(0,0,width,height)}
  function update(dt){time+=state.evolution*dt*.003;const aspect=width/height;for(let i=0;i<state.count;i++){oldX[i]=x[i];oldY[i]=y[i];const nx=x[i]/width*state.scale*3*aspect,ny=y[i]/height*state.scale*3,n=noise(nx,ny,time),angle=n*Math.PI*state.turns,tx=Math.cos(angle)*state.speed,ty=Math.sin(angle)*state.speed;vx[i]=vx[i]*.72+tx*.28;vy[i]=vy[i]*.72+ty*.28;if(pointer.active&&state.tool!=='none'){const dx=pointer.x-x[i],dy=pointer.y-y[i],dist=Math.hypot(dx,dy)||1,radius=190;if(dist<radius){const strength=(1-dist/radius)*.7;if(state.tool==='attract'){vx[i]+=dx/dist*strength;vy[i]+=dy/dist*strength}else if(state.tool==='repel'){vx[i]-=dx/dist*strength;vy[i]-=dy/dist*strength}else{vx[i]+=-dy/dist*strength;vy[i]+=dx/dist*strength}}}x[i]+=vx[i]*dt;y[i]+=vy[i]*dt;age[i]++;if(x[i]<0||x[i]>width||y[i]<0||y[i]>height||age[i]>life[i])seedParticle(i,false)}}
  function drawGroup(start,step,color){ctx.beginPath();for(let i=start;i<state.count;i+=step){ctx.moveTo(oldX[i],oldY[i]);ctx.lineTo(x[i],y[i])}ctx.strokeStyle=color;ctx.lineWidth=1;ctx.stroke()}
  function drawVectors(){const gap=48;ctx.lineWidth=.7;ctx.strokeStyle='rgba(237,245,244,.24)';for(let gy=110;gy<height-25;gy+=gap)for(let gx=25;gx<width-25;gx+=gap){const n=noise(gx/width*state.scale*3*(width/height),gy/height*state.scale*3,time),angle=n*Math.PI*state.turns,len=10;ctx.beginPath();ctx.moveTo(gx-Math.cos(angle)*len*.5,gy-Math.sin(angle)*len*.5);ctx.lineTo(gx+Math.cos(angle)*len*.5,gy+Math.sin(angle)*len*.5);ctx.stroke()}}
  function render(){if(!state.paused){ctx.fillStyle=`rgba(18,25,27,${state.fade})`;ctx.fillRect(0,0,width,height)}ctx.lineCap='round';drawGroup(0,1,'rgba(237,245,244,.22)');drawGroup(2,7,'rgba(117,217,229,.58)');drawGroup(11,31,'rgba(243,195,92,.7)');if(state.vectors)drawVectors();if(pointer.inside&&state.tool!=='none'){ctx.beginPath();ctx.arc(pointer.x,pointer.y,34,0,TAU);ctx.setLineDash([3,6]);ctx.strokeStyle='rgba(117,217,229,.55)';ctx.stroke();ctx.setLineDash([])}}
  function frame(now){const dt=Math.min(2,(now-last)/16.667);last=now;if(!state.paused)update(dt);render();fpsFrames++;if(now-fpsTime>500){document.getElementById('fps').textContent=Math.round(fpsFrames*1000/(now-fpsTime));document.getElementById('field-time').textContent=time.toFixed(2);fpsFrames=0;fpsTime=now}requestAnimationFrame(frame)}
  for(const[key,input]of Object.entries(controls)){syncRange(key);input.addEventListener('input',()=>{const raw=+input.value;state[key]=key==='fade'?raw/100:raw;syncRange(key);if(key==='count'){const old=state.count;state.count=raw;for(let i=old;i<state.count;i++)seedParticle(i,true);document.getElementById('metric-count').textContent=state.count}})}
  document.getElementById('vectors').addEventListener('change',event=>state.vectors=event.target.checked);document.getElementById('tools').addEventListener('click',event=>{const button=event.target.closest('button[data-tool]');if(!button)return;state.tool=button.dataset.tool;document.querySelectorAll('#tools button').forEach(item=>item.setAttribute('aria-pressed',String(item===button)));const labels={vortex:'涡旋力场',attract:'吸引力场',repel:'排斥力场',none:'鼠标力场关闭'};document.getElementById('tool-label').textContent=labels[state.tool]});
  function pointerPos(event){const rect=canvas.getBoundingClientRect();pointer.x=event.clientX-rect.left;pointer.y=event.clientY-rect.top}canvas.addEventListener('pointerenter',event=>{pointer.inside=true;pointerPos(event)});canvas.addEventListener('pointermove',pointerPos);canvas.addEventListener('pointerleave',()=>{pointer.inside=false;pointer.active=false});canvas.addEventListener('pointerdown',event=>{pointerPos(event);pointer.active=true;canvas.setPointerCapture(event.pointerId)});canvas.addEventListener('pointerup',event=>{pointer.active=false;if(canvas.hasPointerCapture(event.pointerId))canvas.releasePointerCapture(event.pointerId)});
  document.getElementById('reset').addEventListener('click',reset);document.getElementById('pause').addEventListener('click',()=>{state.paused=!state.paused;document.getElementById('pause-icon').textContent=state.paused?'▶':'Ⅱ';document.getElementById('pause-label').textContent=state.paused?'继续':'暂停'});new ResizeObserver(resize).observe(canvas);resize();reset();requestAnimationFrame(frame);
})();
