(() => {
  'use strict';
  const canvas=document.getElementById('canvas'),ctx=canvas.getContext('2d',{alpha:false}),keyInput=document.getElementById('key'),valueInput=document.getElementById('value'),bucketInput=document.getElementById('buckets'),speedInput=document.getElementById('speed');
  const state={bucketCount:11,speed:1,paused:false,auto:false,table:[],active:null,status:'等待操作',comparisons:0};let width=1,height=1,dpr=1,last=performance.now(),timer=0,autoTimer=0;
  function hash(key){let h=0;for(let i=0;i<key.length;i++)h=(h*31+key.charCodeAt(i))>>>0;return h%state.bucketCount}
  function seed(randomize=false){state.table=Array.from({length:state.bucketCount},()=>[]);const source=randomize?['sun','tree','grid','path','data','heap','blue','sort','edge','loop','root','wave'].sort(()=>Math.random()-.5).slice(0,8).map(key=>[key,Math.floor(10+Math.random()*90)]):[['cat',18],['lime',72],['node',41],['map',25],['hash',89],['key',34],['code',63],['array',52]];source.forEach(([key,value])=>state.table[hash(key)].push({key,value}));state.active=null;state.status=randomize?'已生成新的键分布':'等待操作';state.comparisons=0;metrics()}
  function count(){return state.table.reduce((sum,b)=>sum+b.length,0)}function collisions(){return state.table.reduce((sum,b)=>sum+Math.max(0,b.length-1),0)}
  function metrics(){document.getElementById('status').textContent=state.status;document.getElementById('load').textContent=(count()/state.bucketCount).toFixed(2);document.getElementById('collisions').textContent=collisions();document.getElementById('comparisons').textContent=state.comparisons;document.getElementById('formula').textContent=`hash(key) mod ${state.bucketCount}`;document.getElementById('bucket-label').textContent=state.active?`BUCKET ${state.active.bucket}`:'BUCKET --'}
  function start(type,key,value){key=String(key).trim();if(!key||state.active)return;const bucket=hash(key);state.active={type,key,value,bucket,index:-1,done:false};state.comparisons=0;state.status=`哈希定位到桶 ${bucket}`;timer=0;metrics()}
  function advance(){const a=state.active;if(!a)return;const chain=state.table[a.bucket];if(a.index+1<chain.length){a.index++;state.comparisons++;state.status=`比较键 ${chain[a.index].key}`;if(chain[a.index].key===a.key){if(a.type==='insert'){chain[a.index].value=a.value;state.status=`更新 ${a.key} = ${a.value}`}else if(a.type==='search')state.status=`找到 ${a.key} = ${chain[a.index].value}`;else{chain.splice(a.index,1);state.status=`已删除 ${a.key}`}a.done=true}metrics();return}if(a.type==='insert'){chain.push({key:a.key,value:a.value});a.index=chain.length-1;state.status=`插入 ${a.key} = ${a.value}`}else state.status=`未找到键 ${a.key}`;a.done=true;metrics()}
  function finishIfDone(){if(state.active?.done){state.active=null;timer=0;metrics();return true}return false}
  function randomOperation(){const keys=['sun','tree','grid','path','data','heap','blue','sort','edge','loop','root','wave'],key=keys[Math.floor(Math.random()*keys.length)],r=Math.random();if(r<.55)start('insert',key,Math.floor(10+Math.random()*90));else if(r<.82)start('search',key);else start('remove',key)}
  function resize(){const rect=canvas.getBoundingClientRect();width=Math.max(1,rect.width);height=Math.max(1,rect.height);dpr=Math.min(2,devicePixelRatio||1);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)}
  function render(){ctx.fillStyle='#171713';ctx.fillRect(0,0,width,height);const top=118,bottom=65,usable=height-top-bottom,rowH=Math.max(22,Math.min(45,usable/state.bucketCount)),bucketW=Math.max(42,Math.min(58,width*.07)),nodeW=Math.max(72,Math.min(112,width*.13)),gap=23,startX=Math.max(28,width*.09);ctx.font='10px ui-monospace,Consolas,monospace';ctx.textBaseline='middle';for(let i=0;i<state.bucketCount;i++){const y=top+i*rowH,hot=state.active?.bucket===i;ctx.beginPath();ctx.roundRect(startX,y,bucketW,rowH-5,4);ctx.fillStyle=hot?'#cae65b':'#22221c';ctx.fill();ctx.strokeStyle=hot?'#cae65b':'rgba(246,246,237,.16)';ctx.stroke();ctx.fillStyle=hot?'#171713':'#9a9a8f';ctx.textAlign='center';ctx.fillText(String(i),startX+bucketW*.5,y+(rowH-5)*.5);let x=startX+bucketW+gap;const chain=state.table[i];for(let j=0;j<chain.length;j++){ctx.strokeStyle=hot?'rgba(202,230,91,.65)':'rgba(246,246,237,.15)';ctx.beginPath();ctx.moveTo(x-gap,y+(rowH-5)*.5);ctx.lineTo(x,y+(rowH-5)*.5);ctx.stroke();const active=hot&&state.active.index===j;ctx.beginPath();ctx.roundRect(x,y,nodeW,rowH-5,4);ctx.fillStyle=active?'#6ed5ce':'#25251e';ctx.fill();ctx.strokeStyle=active?'#6ed5ce':'rgba(246,246,237,.16)';ctx.stroke();ctx.fillStyle=active?'#171713':'#f6f6ed';ctx.textAlign='left';ctx.fillText(chain[j].key,x+10,y+(rowH-5)*.5);ctx.fillStyle=active?'#171713':'#9a9a8f';ctx.textAlign='right';ctx.fillText(String(chain[j].value),x+nodeW-9,y+(rowH-5)*.5);x+=nodeW+gap}}ctx.fillStyle='#9a9a8f';ctx.textAlign='left';ctx.fillText('BUCKETS',startX,Math.max(104,top-18));ctx.fillText('SEPARATE CHAINS',startX+bucketW+gap,Math.max(104,top-18))}
  function frame(now){const dt=Math.min(50,now-last);last=now;if(!state.paused){if(state.active){timer+=dt;if(timer>700/state.speed){timer=0;if(!finishIfDone())advance()}}else if(state.auto&&(autoTimer+=dt)>1500/state.speed){autoTimer=0;randomOperation()}}render();requestAnimationFrame(frame)}
  const key=()=>keyInput.value.trim(),value=()=>Math.max(0,Math.min(999,Math.round(+valueInput.value||0)));document.getElementById('insert').addEventListener('click',()=>start('insert',key(),value()));document.getElementById('search').addEventListener('click',()=>start('search',key()));document.getElementById('remove').addEventListener('click',()=>start('remove',key()));document.getElementById('step').addEventListener('click',()=>{if(state.active?.done)finishIfDone();else if(state.active)advance();else start('search',key())});bucketInput.addEventListener('change',()=>{state.bucketCount=+bucketInput.value;seed()});speedInput.addEventListener('input',()=>{state.speed=+speedInput.value;speedInput.style.setProperty('--progress',`${(state.speed-.4)/2.2*100}%`);document.getElementById('speed-value').textContent=`${state.speed.toFixed(1)}×`});document.getElementById('auto').addEventListener('change',e=>state.auto=e.target.checked);document.getElementById('random').addEventListener('click',()=>seed(true));document.getElementById('pause').addEventListener('click',()=>{state.paused=!state.paused;document.getElementById('pause-icon').textContent=state.paused?'▶':'Ⅱ';document.getElementById('pause-label').textContent=state.paused?'继续':'暂停'});
  speedInput.dispatchEvent(new Event('input'));new ResizeObserver(resize).observe(canvas);resize();seed();requestAnimationFrame(frame);
})();
