(function(){"use strict";
const canvas=document.getElementById("canvas"),ctx=canvas.getContext("2d",{alpha:false});
const el={input:document.getElementById("custom-data"),apply:document.getElementById("apply-data"),target:document.getElementById("target"),speed:document.getElementById("speed"),speedValue:document.getElementById("speed-value"),validation:document.getElementById("validation"),play:document.getElementById("play"),playIcon:document.getElementById("play-icon"),playLabel:document.getElementById("play-label"),step:document.getElementById("step"),comparisons:document.getElementById("comparisons"),remaining:document.getElementById("remaining"),result:document.getElementById("result"),phase:document.getElementById("phase-label"),status:document.getElementById("status-text"),bounds:document.getElementById("bounds")};
const state={data:[],target:63,low:0,high:0,current:null,found:null,comparisons:0,running:false,completed:false,speed:1,width:0,height:0,dpr:1,lastStep:0,history:[]};
function parseData(text){const values=text.split(/[\s,，;；]+/).filter(Boolean).map(Number).filter(Number.isFinite);return [...new Set(values)].sort((a,b)=>a-b).slice(0,64)}
function reset(){state.target=Number(el.target.value);if(!Number.isFinite(state.target)){state.target=0;el.target.value="0"}state.low=0;state.high=state.data.length-1;state.current=null;state.found=null;state.comparisons=0;state.completed=false;state.running=false;state.lastStep=0;state.history=[];updateUI()}
function applyData(){const values=parseData(el.input.value);if(values.length<2){el.validation.textContent="请输入至少两个有效数字";return}el.validation.textContent="";state.data=values;el.input.value=values.join(", ");reset()}
function step(){if(state.completed)return;if(state.low>state.high){state.completed=true;state.found=-1;state.running=false;updateUI();return}const mid=Math.floor((state.low+state.high)/2),value=state.data[mid];state.comparisons++;let relation="equal";if(value<state.target)relation="less";else if(value>state.target)relation="greater";state.current={low:state.low,high:state.high,mid,value,relation};state.history.push({...state.current});if(relation==="equal"){state.found=mid;state.completed=true;state.running=false}else if(relation==="less")state.low=mid+1;else state.high=mid-1;if(state.low>state.high&&!state.completed){state.completed=true;state.found=-1;state.running=false}updateUI()}
function updateUI(){el.comparisons.textContent=state.comparisons;el.remaining.textContent=state.completed?0:Math.max(0,state.high-state.low+1);el.result.textContent=state.found===null?"--":state.found<0?"未找到":state.found;el.bounds.textContent=state.completed?(state.found>=0?`FOUND AT ${state.found}`:"EMPTY RANGE"):`LOW ${state.low} · HIGH ${state.high}`;el.status.textContent=`目标 ${state.target}`;el.phase.textContent=state.completed?(state.found>=0?"查找完成":"目标不存在"):state.current?`比较 ${state.current.value} 与 ${state.target}`:"准备查找";el.playIcon.textContent=state.running?"Ⅱ":"▶";el.playLabel.textContent=state.running?"暂停":state.completed?"重播":"播放"}
function togglePlay(){if(state.completed)reset();state.running=!state.running;state.lastStep=0;updateUI()}
function randomize(){const count=Math.floor(Math.random()*18)+14,values=[];let value=Math.floor(Math.random()*5);for(let i=0;i<count;i++){value+=Math.floor(Math.random()*8)+2;values.push(value)}state.data=values;const hit=Math.random()<.72;state.target=hit?values[Math.floor(Math.random()*values.length)]:value+Math.floor(Math.random()*8)+1;el.input.value=values.join(", ");el.target.value=state.target;reset()}
function resize(){const r=canvas.getBoundingClientRect();state.width=r.width;state.height=r.height;state.dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(r.width*state.dpr);canvas.height=Math.round(r.height*state.dpr)}
function roundRect(x,y,w,h,r){const radius=Math.min(r,w/2,h/2);ctx.beginPath();ctx.roundRect(x,y,w,h,radius)}
function draw(){const w=state.width,h=state.height,dpr=state.dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle="#11181a";ctx.fillRect(0,0,w,h);ctx.strokeStyle="rgba(255,255,255,.035)";ctx.lineWidth=1;for(let gx=0;gx<w;gx+=44){ctx.beginPath();ctx.moveTo(gx,0);ctx.lineTo(gx,h);ctx.stroke()}for(let gy=0;gy<h;gy+=44){ctx.beginPath();ctx.moveTo(0,gy);ctx.lineTo(w,gy);ctx.stroke()}
const n=state.data.length;if(!n)return;const pad=Math.max(22,Math.min(60,w*.06)),gap=n>32?2:5,available=w-pad*2,cellW=Math.min(66,(available-gap*(n-1))/n),gridW=cellW*n+gap*(n-1),startX=(w-gridW)/2,cellH=Math.max(42,Math.min(68,h*.1)),y=Math.max(170,h*.42-cellH/2);ctx.textAlign="center";ctx.textBaseline="middle";
for(let i=0;i<n;i++){const px=startX+i*(cellW+gap),inRange=!state.completed&&i>=state.low&&i<=state.high,isMid=state.current&&i===state.current.mid,isFound=state.found===i;let fill=inRange?"rgba(116,215,223,.16)":"rgba(255,255,255,.045)",stroke=inRange?"rgba(116,215,223,.52)":"rgba(255,255,255,.09)";if(isMid){fill="#efbd58";stroke="#efbd58"}if(isFound){fill="#76d3a5";stroke="#76d3a5"}roundRect(px,y,cellW,cellH,4);ctx.fillStyle=fill;ctx.fill();ctx.strokeStyle=stroke;ctx.stroke();ctx.fillStyle=(isMid||isFound)?"#11181a":inRange?"#edf4ee":"#687375";ctx.font=`600 ${cellW<28?9:12}px ui-monospace,Consolas,monospace`;ctx.fillText(String(state.data[i]),px+cellW/2,y+cellH/2);if(cellW>=20){ctx.fillStyle="#687375";ctx.font="9px ui-monospace,Consolas,monospace";ctx.fillText(String(i),px+cellW/2,y+cellH+15)}}
if(state.current){const px=startX+state.current.mid*(cellW+gap)+cellW/2;ctx.strokeStyle="#efbd58";ctx.beginPath();ctx.moveTo(px,y-42);ctx.lineTo(px,y-10);ctx.stroke();ctx.fillStyle="#efbd58";ctx.font="10px ui-monospace,Consolas,monospace";ctx.fillText("MID",px,y-53)}
const histY=y+cellH+74;ctx.textAlign="left";ctx.fillStyle="#91a0a1";ctx.font="9px ui-monospace,Consolas,monospace";ctx.fillText("SEARCH TRACE",pad,histY);state.history.slice(-5).forEach((s,k)=>{const yy=histY+25+k*22,sign=s.relation==="equal"?"=":s.relation==="less"?"<":">";ctx.fillStyle=k===Math.min(4,state.history.length-1)?"#edf4ee":"#697577";ctx.fillText(`${String(k+Math.max(1,state.history.length-4)).padStart(2,"0")}   [${s.low}, ${s.high}]   MID ${s.mid}   ${s.value} ${sign} ${state.target}`,pad,yy)})}
function frame(now){if(state.running&&!state.completed&&(state.lastStep===0||now-state.lastStep>700/state.speed)){step();state.lastStep=now}draw();requestAnimationFrame(frame)}
el.apply.addEventListener("click",applyData);el.target.addEventListener("change",reset);el.speed.addEventListener("input",()=>{state.speed=Number(el.speed.value);el.speedValue.textContent=`${state.speed.toFixed(1)}×`;el.speed.style.setProperty("--progress",`${(state.speed-.25)/2.75*100}%`)});el.play.addEventListener("click",togglePlay);el.step.addEventListener("click",()=>{state.running=false;if(state.completed)reset();step()});document.getElementById("randomize").addEventListener("click",randomize);window.addEventListener("resize",resize,{passive:true});state.data=parseData(el.input.value);resize();reset();el.speed.dispatchEvent(new Event("input"));requestAnimationFrame(frame);
})();
